/**
 * Utilities for detecting auto-generated APIM resource IDs.
 *
 * APIM auto-generates 24-character lowercase hex IDs for certain resources:
 * - ApiSchema: when importing OpenAPI/WSDL specs, schemas get auto-generated IDs
 * - NamedValue: logger credentials (e.g., EventHub connection strings)
 *
 * These auto-generated resources should typically be skipped during publish
 * because APIM recreates them when the parent resource is published.
 */

/**
 * Pattern matching auto-generated 24-character lowercase hex IDs that APIM creates.
 * Examples: "69f15c3c10a45d29d855583a", "69f16ad1ee7da61d543198f7"
 */
const AUTO_GENERATED_ID_PATTERN = /^[0-9a-f]{24}$/;

/**
 * Checks if a resource name/ID is an auto-generated 24-character hex ID.
 *
 * APIM auto-generates these IDs for:
 * - ApiSchema resources when importing OpenAPI/WSDL specifications
 * - NamedValue resources for logger credentials (EventHub, etc.)
 *
 * @param name - The resource name or ID to check
 * @returns true if the name matches the auto-generated pattern
 *
 * @example
 * isAutoGeneratedId('69f15c3c10a45d29d855583a') // true
 * isAutoGeneratedId('src-rest-schema-item')      // false
 * isAutoGeneratedId('my-named-value')            // false
 */
export function isAutoGeneratedId(name: string): boolean {
  return AUTO_GENERATED_ID_PATTERN.test(name);
}
