// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
/**
 * T032: API publisher with revision handling
 * Create root API first, then revisions in numeric order with forced revision numbers.
 * Publish operations, policies, schemas, releases, resolvers, tag descriptions, wikis per FR-024.
 * Handle SOAP/WSDL import via ?import=true&format=wsdl-link query parameter.
 */

import type { IApimClient } from '../clients/iapim-client.js';
import type { IArtifactStore } from '../clients/iartifact-store.js';
import type { ApimServiceContext, ResourceDescriptor } from '../models/types.js';
import type { PublishConfig } from '../models/config.js';
import * as yaml from 'js-yaml';
import { ResourceType } from '../models/resource-types.js';
import { publishResource, type ResourcePublishResult } from './resource-publisher.js';
import { runParallel } from '../lib/parallel-runner.js';
import { applyOverrides } from './override-merger.js';
import { logger } from '../lib/logger.js';
import { getNamePart, getPublishTier } from '../lib/resource-path.js';
import { isAutoGeneratedId } from '../lib/auto-generated.js';

/**
 * API child resource types that should be published after the API itself
 */
const API_CHILD_TYPES: ResourceType[] = [
  ResourceType.ApiPolicy,
  ResourceType.ApiTag,
  ResourceType.ApiDiagnostic,
  ResourceType.ApiOperation,
  ResourceType.ApiOperationPolicy,
  ResourceType.ApiSchema,
  ResourceType.ApiRelease,
  ResourceType.ApiTagDescription,
  ResourceType.ApiWiki,
  ResourceType.McpServer,
  ResourceType.GraphQLResolver,
  ResourceType.GraphQLResolverPolicy,
];

/**
 * Publish an API with all its revisions and child resources.
 * Creates root API first, then revisions in numeric order.
 * Handles SOAP/WSDL import via ?import=true&format=wsdl-link.
 */
export async function publishApi(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<ResourcePublishResult> {
  try {
    // Step 1: Publish root API (with spec import if available)
    const rootResult = await publishRootApi(client, store, context, descriptor, config);
    if (rootResult.status !== 'success') {
      return rootResult;
    }

    if (rootResult.specImported && rootResult.operationIdsWithNullDescription?.length) {
      await alignImportedOperationDescriptions(
        client,
        context,
        descriptor,
        rootResult.operationIdsWithNullDescription
      );
    }

    // Step 2: Find and publish revisions in numeric order
    const publishedRevisionCount = await publishApiRevisions(client, store, context, descriptor, config);

    // Step 2b: Align root API only when source marks it as current.
    // Source of truth is properties.isCurrent in root apiInformation.json.
    if (publishedRevisionCount > 0 && rootResult.isCurrent === true) {
      const alignResult = await alignActiveRevisionWithSource(
        client,
        store,
        context,
        descriptor,
        config
      );
      if (alignResult.status !== 'success') {
        return alignResult;
      }
    }

    // Step 3: Publish child resources in parallel
    // When a spec was imported, operations and schemas are auto-created by APIM
    await publishApiChildren(client, store, context, descriptor, config, rootResult.specImported);

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Maps spec file format to APIM ContentFormat for inline import.
 */
function getImportFormat(specFormat: string, _apiType?: string): string | undefined {
  const apiType = _apiType?.toLowerCase();
  if (apiType === 'a2a') {
    return undefined;
  }

  switch (specFormat) {
    case 'yaml':
      return 'openapi';
    case 'json':
      // Swagger 2.0 uses swagger-json, OpenAPI 3.x uses openapi+json.
      // Default to openapi+json as the more modern format — APIM accepts both.
      return 'openapi+json';
    case 'wsdl':
      return 'wsdl';
    case 'wadl':
      return 'wadl-xml';
    case 'graphql':
      // GraphQL schemas are managed via the ApiSchema resource, not via
      // the import properties. Return undefined so we skip injection.
      return undefined;
    default:
      return undefined;
  }
}

interface RootApiResult {
  status: 'success' | 'skipped';
  specImported: boolean;
  operationIdsWithNullDescription?: string[];
  isCurrent?: boolean;
}

interface PublishRootApiOptions {
  includeSpecification?: boolean;
}

/**
 * Publish the root API (apiInformation.json).
 * When a specification file exists alongside the API metadata, injects
 * `properties.format` and `properties.value` into the PUT body so APIM
 * imports the spec and auto-creates operations + schemas.
 */
async function publishRootApi(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  options?: PublishRootApiOptions
): Promise<RootApiResult & ResourcePublishResult> {
  let json = await store.readResource(config.sourceDir, descriptor);
  if (!json) {
    return {
      descriptor,
      status: 'skipped',
      action: 'noop',
      specImported: false,
    };
  }

  // Apply overrides
  json = applyOverrides(descriptor, json, config.overrides);
  const isCurrent = getApiIsCurrent(json);

  // Try to read the specification file for this API
  let specImported = false;
  let operationIdsWithNullDescription: string[] = [];
  const includeSpecification = options?.includeSpecification ?? true;
  const specResult = includeSpecification
    ? await store.readContent(config.sourceDir, descriptor, 'specification')
    : undefined;
  if (specResult) {
    const properties = json.properties as Record<string, unknown> | undefined;
    const apiType = properties?.type as string | undefined;
    const importFormat = getImportFormat(specResult.format ?? 'yaml', apiType);

    if (importFormat) {
      // Strip null-valued properties that cause validation errors in
      // APIM's spec-import mode (e.g. "backendId": null → HTTP 400).
      const cleanProps: Record<string, unknown> = {};
      for (const [key, val] of Object.entries(properties ?? {})) {
        if (val !== null) {
          cleanProps[key] = val;
        }
      }

      // The `type` property from GET is read-only and ignored on PUT.
      // APIM uses `apiType` to determine the API kind during spec import.
      // Always set it explicitly (valid values include http, soap, websocket, graphql, odata, grpc, mcp, a2a).
      if (apiType) {
        cleanProps.apiType = apiType;
      }

      // Inject the spec into the PUT body for APIM to import
      json = {
        ...json,
        properties: {
          ...cleanProps,
          format: importFormat,
          value: specResult.content,
        },
      };

      if (importFormat === 'openapi' || importFormat === 'openapi+json') {
        operationIdsWithNullDescription = getOpenApiOperationIdsWithNullDescription(
          specResult.content,
          specResult.format
        );
      }

      specImported = true;
      logger.info(`Including ${specResult.format} specification in API import for "${getNamePart(descriptor.nameParts, 0)}"`);
    }
  }

  // PUT the API resource to APIM
  await client.putResource(context, descriptor, json);

  return {
    descriptor,
    status: 'success',
    action: 'put',
    specImported,
    operationIdsWithNullDescription,
    isCurrent,
  };
}

async function alignActiveRevisionWithSource(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<RootApiResult & ResourcePublishResult> {
  logger.debug(
    `Source marks "${getNamePart(descriptor.nameParts, 0)}" as current; re-applying root metadata to align active revision`
  );

  return publishRootApi(client, store, context, descriptor, config, {
    includeSpecification: false,
  });
}

/**
 * Find and publish API revisions in numeric order
 */
async function publishApiRevisions(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  apiDescriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<number> {
  // List all resources from store
  const allDescriptors = await store.listResources(config.sourceDir);

  // Find revision descriptors for this API
  const revisionDescriptors = allDescriptors.filter(
    (d) =>
      d.type === ResourceType.Api &&
      getNamePart(d.nameParts, 0).startsWith(`${getNamePart(apiDescriptor.nameParts, 0)};rev=`)
  );

  // Sort revisions by revision number
  const sortedRevisions = revisionDescriptors.sort((a, b) => {
    const revA = extractRevisionNumber(getNamePart(a.nameParts, 0));
    const revB = extractRevisionNumber(getNamePart(b.nameParts, 0));
    return revA - revB;
  });

  // Publish each revision in order
  for (const revDescriptor of sortedRevisions) {
    await publishResource(client, store, context, revDescriptor, config);
  }

  return sortedRevisions.length;
}

/**
 * Resource types that are auto-created by APIM when importing a spec.
 * Both ApiOperation and ApiSchema are initially excluded, but we selectively
 * re-add: operations with schema references, and explicitly named schemas
 * (non-auto-generated 24-char hex IDs).
 */
const SPEC_MANAGED_CHILD_TYPES = new Set<ResourceType>([
  ResourceType.ApiOperation,
  ResourceType.ApiSchema,
]);

/**
 * Publish all child resources of an API in parallel.
 * When specImported is true, skips ApiSchema and ApiOperation since APIM
 * auto-creates those from the imported specification. However:
 * - Operations with schema references are re-PUT explicitly so APIM preserves those links
 * - Explicitly named schemas (non-24-char-hex IDs) are also re-published
 */
async function publishApiChildren(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  apiDescriptor: ResourceDescriptor,
  config: PublishConfig,
  specImported: boolean = false
): Promise<void> {
  // List all resources from store
  const allDescriptors = await store.listResources(config.sourceDir);

  // Find child descriptors for this API
  let childDescriptors = allDescriptors.filter(
    (d) =>
      API_CHILD_TYPES.includes(d.type) &&
      getNamePart(d.nameParts, 0) === getNamePart(apiDescriptor.nameParts, 0) &&
      !(specImported && SPEC_MANAGED_CHILD_TYPES.has(d.type))
  );

  // When a spec was imported, APIM auto-creates operations and schemas but loses
  // schemaId/typeName references in representations. Re-include operations that
  // carry such references so those links are explicitly restored via PUT.
  if (specImported) {
    // In incremental mode, avoid re-publishing operation artifacts after spec
    // import. This prevents stale operation JSON from overwriting newly
    // imported OpenAPI operation metadata (for example descriptions).
    const shouldRepublishSchemaRefOps = !config.commitId;

    const operationDescriptors = allDescriptors.filter(
      (d) =>
        d.type === ResourceType.ApiOperation &&
        getNamePart(d.nameParts, 0) === getNamePart(apiDescriptor.nameParts, 0)
    );

    if (shouldRepublishSchemaRefOps) {
      const schemaRefOps = await filterOperationsWithSchemaRefs(
        store,
        config.sourceDir,
        operationDescriptors
      );

      if (schemaRefOps.length > 0) {
        logger.debug(
          `Re-publishing ${schemaRefOps.length} operation(s) with schema references after spec import for "${getNamePart(apiDescriptor.nameParts, 0)}"`
        );
        childDescriptors = [...childDescriptors, ...schemaRefOps];
      }
    } else {
      logger.debug(
        `Skipping schema-reference operation re-publish for "${getNamePart(apiDescriptor.nameParts, 0)}" in incremental mode`
      );
    }

    // Re-include explicitly named schemas (non-auto-generated IDs).
    // Auto-generated schemas have 24-char hex names and are recreated by spec import.
    // Explicitly named schemas (like "src-rest-schema-item") must be published.
    const explicitSchemas = allDescriptors.filter(
      (d) =>
        d.type === ResourceType.ApiSchema &&
        getNamePart(d.nameParts, 0) === getNamePart(apiDescriptor.nameParts, 0) &&
        !isAutoGeneratedId(getNamePart(d.nameParts, 1))
    );

    if (explicitSchemas.length > 0) {
      logger.debug(
        `Re-publishing ${explicitSchemas.length} explicit schema(s) after spec import for "${getNamePart(apiDescriptor.nameParts, 0)}"`
      );
      childDescriptors = [...childDescriptors, ...explicitSchemas];
    }
  }

  // Group resources by publish tier for dependency ordering.
  // Lower tiers are published first (parents before children, operations before policies).
  // Resources in the same tier can be published in parallel.
  const tierMap = new Map<number, ResourceDescriptor[]>();
  for (const d of childDescriptors) {
    const tier = getPublishTier(d.type);
    const existing = tierMap.get(tier) ?? [];
    existing.push(d);
    tierMap.set(tier, existing);
  }

  // Publish each tier in order (lowest to highest)
  const sortedTiers = [...tierMap.keys()].sort((a, b) => a - b);
  for (const tier of sortedTiers) {
    const descriptors = tierMap.get(tier) ?? [];
    if (descriptors.length > 0) {
      const tasks = descriptors.map(
        (descriptor) => () =>
          publishResource(client, store, context, descriptor, config)
      );
      await runParallel(tasks, 5);
    }
  }
}

/**
 * Returns the subset of operation descriptors whose stored artifact contains
 * at least one representation with a schemaId or typeName property.
 * These operations must be re-PUT after a spec import so APIM retains the
 * schema linkage that the import path discards.
 */
async function filterOperationsWithSchemaRefs(
  store: IArtifactStore,
  sourceDir: string,
  operationDescriptors: ResourceDescriptor[]
): Promise<ResourceDescriptor[]> {
  const result: ResourceDescriptor[] = [];

  for (const descriptor of operationDescriptors) {
    const json = await store.readResource(sourceDir, descriptor);
    if (json && operationHasSchemaRefs(json)) {
      result.push(descriptor);
    }
  }

  return result;
}

/**
 * Returns true if the operation JSON contains at least one representation
 * (in request or any response) that has a schemaId or typeName property.
 */
function operationHasSchemaRefs(json: Record<string, unknown>): boolean {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) return false;

  const representationGroups: unknown[] = [];

  const request = props.request as Record<string, unknown> | undefined;
  if (request?.representations) {
    representationGroups.push(request.representations);
  }

  const responses = props.responses as unknown[] | undefined;
  if (Array.isArray(responses)) {
    for (const response of responses) {
      const r = response as Record<string, unknown>;
      if (r.representations) {
        representationGroups.push(r.representations);
      }
    }
  }

  for (const group of representationGroups) {
    if (!Array.isArray(group)) continue;
    for (const rep of group) {
      const r = rep as Record<string, unknown>;
      if (r.schemaId != null || r.typeName != null) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Extract revision number from API name (e.g., "my-api;rev=2" -> 2)
 */
function extractRevisionNumber(apiName: string): number {
  const match = /;rev=(\d+)/.exec(apiName);
  return match ? parseInt(match[1], 10) : 0;
}

function getApiIsCurrent(json: Record<string, unknown>): boolean | undefined {
  const properties = json.properties as Record<string, unknown> | undefined;
  const isCurrent = properties?.isCurrent;
  return typeof isCurrent === 'boolean' ? isCurrent : undefined;
}

async function alignImportedOperationDescriptions(
  client: IApimClient,
  context: ApimServiceContext,
  apiDescriptor: ResourceDescriptor,
  operationIdsWithNullDescription: string[]
): Promise<void> {
  const apiName = getNamePart(apiDescriptor.nameParts, 0);

  for (const operationName of operationIdsWithNullDescription) {
    const operationDescriptor: ResourceDescriptor = {
      type: ResourceType.ApiOperation,
      nameParts: [apiName, operationName],
      workspace: apiDescriptor.workspace,
    };

    const operation = await client.getResource(context, operationDescriptor);
    if (!operation) {
      continue;
    }

    const props = operation.properties as Record<string, unknown> | undefined;
    if (!props || props.description === null) {
      continue;
    }

    await client.putResource(context, operationDescriptor, {
      ...operation,
      properties: {
        ...props,
        description: null,
      },
    });
  }
}

function getOpenApiOperationIdsWithNullDescription(
  specContent: string,
  specFormat?: string
): string[] {
  try {
    const parsed: unknown =
      specFormat === 'json'
        ? JSON.parse(specContent)
        : yaml.load(specContent);

    if (!parsed || typeof parsed !== 'object') {
      return [];
    }

    const parsedRecord = parsed as Record<string, unknown>;
    const pathsValue = parsedRecord.paths;
    if (!pathsValue || typeof pathsValue !== 'object') {
      return [];
    }

    const paths = pathsValue as Record<string, unknown>;

    const methods = new Set(['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']);
    const operationIds = new Set<string>();

    for (const pathItem of Object.values(paths)) {
      if (!pathItem || typeof pathItem !== 'object') {
        continue;
      }

      for (const [methodName, operation] of Object.entries(pathItem as Record<string, unknown>)) {
        if (!methods.has(methodName.toLowerCase()) || !operation || typeof operation !== 'object') {
          continue;
        }

        const operationRecord = operation as Record<string, unknown>;
        const operationId = operationRecord.operationId;
        if (typeof operationId !== 'string' || operationId.length === 0) {
          continue;
        }

        if (!Object.hasOwn(operationRecord, 'description') || operationRecord.description == null) {
          operationIds.add(operationId);
        }
      }
    }

    return [...operationIds];
  } catch {
    return [];
  }
}
