// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
/**
 * API publisher with revision handling
 * Create root API first, then revisions in numeric order with forced revision numbers.
 * Publish operations, policies, schemas, releases, resolvers, tag descriptions, wikis per FR-024.
 * Handle SOAP/WSDL import via ?import=true&format=wsdl-link query parameter.
 */

import type { IApimClient, ApiSpecDialect } from '../clients/iapim-client.js';
import type { IArtifactStore } from '../clients/iartifact-store.js';
import type { ApimServiceContext, ResourceDescriptor } from '../models/types.js';
import type { PublishConfig } from '../models/config.js';
import * as yaml from 'js-yaml';
import { ResourceType } from '../models/resource-types.js';
import {
  applyApiPathPrefix,
  normalizeMcpToolOperationIds,
  normalizeApiVersionSetId,
  publishResource,
  type ResourcePublishResult,
} from './resource-publisher.js';
import { mapDescriptor } from './env-mapper.js';
import { runParallel } from '../lib/parallel-runner.js';
import { applyOverrides } from './override-merger.js';
import { logger } from '../lib/logger.js';
import {
  getNamePart,
  getPublishTier,
  getResourceDescriptorKey,
} from '../lib/resource-path.js';
import { isAutoGeneratedId } from '../lib/auto-generated.js';
import { resolveWorkspaceFilter, shouldIncludeResource } from './filter-service.js';

/**
 * API child resource types that should be published after the API itself
 */
export const API_CHILD_TYPES: ResourceType[] = [
  ResourceType.ApiPolicy,
  ResourceType.ApiTag,
  ResourceType.ApiDiagnostic,
  ResourceType.ApiOperation,
  ResourceType.ApiOperationPolicy,
  ResourceType.ApiSchema,
  ResourceType.ApiRelease,
  ResourceType.ApiTagDescription,
  ResourceType.ApiWiki,
  ResourceType.GraphQLResolver,
  ResourceType.GraphQLResolverPolicy,
];

export interface ApiPatchPlan {
  descriptor: ResourceDescriptor;
  payload: Record<string, unknown>;
}

export interface ApiPublicationPlan {
  importSpecification: boolean;
  revisions: ResourceDescriptor[];
  alignActiveRevision: boolean;
  childPuts: ResourceDescriptor[];
  operationDescriptionPuts: ResourceDescriptor[];
  operationPatches: ApiPatchPlan[];
}

/**
 * Publish an API with all its revisions and child resources.
 * Creates root API first, then revisions in numeric order.
 * Handles SOAP/WSDL import via ?import=true&format=wsdl-link.
 */
export async function publishApi(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  allowedDescriptors?: ResourceDescriptor[]
): Promise<ResourcePublishResult> {
  let publicationPlan: ApiPublicationPlan;
  let rootPublished = false;
  try {
    publicationPlan = await planApiPublication(
      store,
      descriptor,
      config,
      allowedDescriptors
    );
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }

  try {
    // Step 1: Publish root API (with spec import if available)
    const rootResult = await publishRootApi(client, store, context, descriptor, config, {
      includeSpecification: publicationPlan.importSpecification,
    });
    if (rootResult.status !== 'success') {
      return rootResult;
    }
    rootPublished = true;

    const relatedResults: ResourcePublishResult[] = [];
    if (rootResult.specImported && publicationPlan.operationDescriptionPuts.length > 0) {
      relatedResults.push(...await alignImportedOperationDescriptions(
        client,
        context,
        publicationPlan.operationDescriptionPuts,
        config
      ));
    }

    // Step 2: Find and publish revisions in numeric order
    const revisionResults = await publishApiRevisions(
      client,
      store,
      context,
      config,
      publicationPlan.revisions
    );
    relatedResults.push(...revisionResults);

    // Step 2b: Align root API only when source marks it as current.
    // Source of truth is properties.isCurrent in root apiInformation.json.
    if (publicationPlan.alignActiveRevision && rootResult.isCurrent === true) {
      let alignResult: ResourcePublishResult;
      try {
        alignResult = await alignActiveRevisionWithSource(
          client,
          store,
          context,
          descriptor,
          config
        );
      } catch (error) {
        alignResult = {
          descriptor,
          status: 'failed',
          action: 'put',
          error: error instanceof ApiPutAttemptError
            ? error.originalError
            : error instanceof Error
              ? error
              : new Error(String(error)),
        };
      }
      relatedResults.push(alignResult);
      if (alignResult.status !== 'success') {
        return {
          descriptor,
          status: 'success',
          action: 'put',
          relatedResults,
        };
      }
    }

    // Step 3: Publish child resources in parallel
    // When a spec was imported, operations and schemas are auto-created by APIM
    relatedResults.push(...await publishApiChildren(
      client,
      store,
      context,
      config,
      publicationPlan
    ));

    return {
      descriptor,
      status: 'success',
      action: 'put',
      relatedResults,
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: rootPublished || error instanceof ApiPutAttemptError ? 'put' : 'noop',
      error: error instanceof ApiPutAttemptError
        ? error.originalError
        : error instanceof Error
          ? error
          : new Error(String(error)),
    };
  }
}

export async function planApiPublication(
  store: IArtifactStore,
  apiDescriptor: ResourceDescriptor,
  config: PublishConfig,
  allowedDescriptors?: ResourceDescriptor[]
): Promise<ApiPublicationPlan> {
  const allDescriptors = await store.listResources(config.sourceDir);
  const apiName = getNamePart(apiDescriptor.nameParts, 0);
  const managedChildren = allDescriptors.filter(
    (descriptor) =>
      SPEC_MANAGED_CHILD_TYPES.has(descriptor.type) &&
      getNamePart(descriptor.nameParts, 0).toLowerCase() === apiName.toLowerCase() &&
      descriptor.workspace === apiDescriptor.workspace
  );
  const effectiveFilter = apiDescriptor.workspace
    ? resolveWorkspaceFilter(apiDescriptor.workspace, config.filter)
    : config.filter;
  const subFilter = Object.entries(effectiveFilter?.apiSubFilters ?? {}).find(
    ([name]) => name.toLowerCase() === apiName.toLowerCase()
  )?.[1];
  const allowed = allowedDescriptors
    ? new Set(allowedDescriptors.map(getResourceDescriptorKey))
    : undefined;
  const rootName = apiName.toLowerCase();
  const revisions = allDescriptors
    .filter(
      (descriptor) =>
        descriptor.type === ResourceType.Api &&
        descriptor.workspace === apiDescriptor.workspace &&
        getNamePart(descriptor.nameParts, 0).toLowerCase().startsWith(`${rootName};rev=`) &&
        (
          !allowed ||
          allowed.has(getResourceDescriptorKey(descriptor)) ||
          (config.commitId !== undefined && shouldIncludeResource(descriptor, effectiveFilter))
        )
    )
    .sort(
      (left, right) =>
        extractRevisionNumber(getNamePart(left.nameParts, 0)) -
        extractRevisionNumber(getNamePart(right.nameParts, 0))
    );
  const apiJson = await store.readResource(config.sourceDir, apiDescriptor);
  const mergedApiJson = apiJson
    ? applyOverrides(apiDescriptor, apiJson, config.overrides)
    : undefined;
  const specificationAllowed =
    subFilter?.operations === undefined &&
    subFilter?.schemas === undefined &&
    (
      !allowed ||
      managedChildren.length === 0 ||
      (config.filter
        ? managedChildren.every((descriptor) =>
            shouldIncludeResource(descriptor, effectiveFilter)
          )
        : managedChildren.every((descriptor) =>
            allowed.has(getResourceDescriptorKey(descriptor))
          ))
    );

  let importSpecification = false;
  let operationDescriptionPuts: ResourceDescriptor[] = [];
  if (specificationAllowed) {
    const specification = await store.readContent(config.sourceDir, apiDescriptor, 'specification');
    if (mergedApiJson && specification) {
      const properties = mergedApiJson.properties as Record<string, unknown> | undefined;
      const apiType = properties?.type as string | undefined;
      const dialect = detectSpecDialect(specification.content, specification.format);
      importSpecification =
        getImportFormat(specification.format ?? 'yaml', apiType, dialect) !== undefined;
      if (importSpecification) {
        operationDescriptionPuts = getOpenApiOperationIdsWithNullDescription(
          specification.content,
          specification.format
        ).map((operationName) => ({
          type: ResourceType.ApiOperation,
          nameParts: [apiName, operationName],
          workspace: apiDescriptor.workspace,
        }));
      }
    }
  }

  let childPuts = allDescriptors.filter(
    (descriptor) =>
      API_CHILD_TYPES.includes(descriptor.type) &&
      getNamePart(descriptor.nameParts, 0).toLowerCase() === apiName.toLowerCase() &&
      descriptor.workspace === apiDescriptor.workspace &&
      !(importSpecification && SPEC_MANAGED_CHILD_TYPES.has(descriptor.type))
  );
  if (allowed) {
    childPuts = childPuts.filter(
      (descriptor) =>
        allowed.has(getResourceDescriptorKey(descriptor)) ||
        (config.commitId !== undefined && shouldIncludeResource(descriptor, effectiveFilter))
    );
  }

  if (importSpecification) {
    const explicitSchemas = allDescriptors.filter(
      (descriptor) =>
        descriptor.type === ResourceType.ApiSchema &&
        getNamePart(descriptor.nameParts, 0).toLowerCase() === apiName.toLowerCase() &&
        descriptor.workspace === apiDescriptor.workspace &&
        !isAutoGeneratedId(getNamePart(descriptor.nameParts, 1))
    );
    const filteredExplicitSchemas = config.filter
      ? explicitSchemas.filter((descriptor) =>
          shouldIncludeResource(descriptor, effectiveFilter)
        )
      : allowed
        ? explicitSchemas.filter((descriptor) =>
            allowed.has(getResourceDescriptorKey(descriptor))
          )
        : explicitSchemas;
    childPuts = [...childPuts, ...filteredExplicitSchemas];
  }

  let operationDescriptors = importSpecification
    ? managedChildren.filter(
        (descriptor) =>
          descriptor.type === ResourceType.ApiOperation &&
          !isAutoGeneratedId(getNamePart(descriptor.nameParts, 1))
      )
    : [];
  if (config.filter) {
    operationDescriptors = operationDescriptors.filter((descriptor) =>
      shouldIncludeResource(descriptor, effectiveFilter)
    );
  } else if (allowed) {
    operationDescriptors = operationDescriptors.filter((descriptor) =>
      allowed.has(getResourceDescriptorKey(descriptor))
    );
  }

  const operationPatches = (
    await Promise.all(
      operationDescriptors.map(async (descriptor): Promise<ApiPatchPlan | undefined> => {
        const payload = await buildOperationPatchPayload(store, descriptor, config);
        return payload ? { descriptor, payload } : undefined;
      })
    )
  ).filter((plan): plan is ApiPatchPlan => plan !== undefined);

  return {
    importSpecification,
    revisions,
    alignActiveRevision:
      revisions.length > 0 &&
      mergedApiJson !== undefined &&
      getApiIsCurrent(mergedApiJson) === true,
    childPuts: deduplicateDescriptors(childPuts),
    operationDescriptionPuts,
    operationPatches,
  };
}

/**
 * Maps spec file format to APIM ContentFormat for inline import.
 * @param specDialect - The spec dialect of a JSON spec. Swagger 2.0 ('swagger2')
 *   must be imported via `swagger-json` so its native format (and schema/operation
 *   metadata) is preserved; OpenAPI 3.x ('openapi3') uses `openapi+json`.
 */
function getImportFormat(specFormat: string, _apiType?: string, specDialect?: ApiSpecDialect): string | undefined {
  const apiType = _apiType?.toLowerCase();
  if (apiType === 'a2a') {
    return undefined;
  }

  switch (specFormat) {
    case 'yaml':
      return 'openapi';
    case 'json':
      // Match the source dialect: Swagger 2.0 uses swagger-json, OpenAPI 3.x uses
      // openapi+json. APIM accepts both, but importing a Swagger 2.0 document as
      // openapi+json would convert it to OpenAPI 3.0 and lose fidelity.
      return specDialect === 'swagger2' ? 'swagger-json' : 'openapi+json';
    case 'wsdl':
      return 'wsdl';
    case 'wadl':
      return 'wadl-xml';
    case 'graphql':
      // GraphQL schemas are managed via the ApiSchema resource, not via
      // the import properties. Return undefined so we skip injection.
      return undefined;
    default:
      return undefined;
  }
}

interface RootApiResult {
  status: 'success' | 'skipped';
  specImported: boolean;
  isCurrent?: boolean;
}

interface PublishRootApiOptions {
  includeSpecification?: boolean;
}

/**
 * Publish the root API (apiInformation.json).
 * When a specification file exists alongside the API metadata, injects
 * `properties.format` and `properties.value` into the PUT body so APIM
 * imports the spec and auto-creates operations + schemas.
 */
async function publishRootApi(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  options?: PublishRootApiOptions
): Promise<RootApiResult & ResourcePublishResult> {
  let json = await store.readResource(config.sourceDir, descriptor);
  if (!json) {
    return {
      descriptor,
      status: 'skipped',
      action: 'noop',
      specImported: false,
    };
  }

  // Root APIs publish through api-publisher rather than publishResource, so
  // they need the same pre-override MCP tool normalization here that revision
  // APIs receive in resource-publisher.
  json = normalizeMcpToolOperationIds(json, context, config.envMapping);

  // Apply overrides
  json = applyOverrides(descriptor, json, config.overrides);
  const isCurrent = getApiIsCurrent(json);

  // Try to read the specification file for this API
  let specImported = false;
  const includeSpecification = options?.includeSpecification ?? true;
  const specResult = includeSpecification
    ? await store.readContent(config.sourceDir, descriptor, 'specification')
    : undefined;
  if (specResult) {
    const properties = json.properties as Record<string, unknown> | undefined;
    const apiType = properties?.type as string | undefined;
    const specDialect = detectSpecDialect(specResult.content, specResult.format);
    const importFormat = getImportFormat(specResult.format ?? 'yaml', apiType, specDialect);

    if (importFormat) {
      // Strip null-valued properties that cause validation errors in
      // APIM's spec-import mode (e.g. "backendId": null → HTTP 400).
      const cleanProps: Record<string, unknown> = {};
      for (const [key, val] of Object.entries(properties ?? {})) {
        if (val !== null) {
          cleanProps[key] = val;
        }
      }

      // The `type` property from GET is read-only and ignored on PUT.
      // APIM uses `apiType` to determine the API kind during spec import.
      // Always set it explicitly (valid values include http, soap, websocket, graphql, odata, grpc, mcp, a2a).
      if (apiType) {
        cleanProps.apiType = apiType;
      }

      // Sanitize the spec before import (e.g. inject missing path parameters)
      const sanitizedContent = sanitizeOpenApiSpec(specResult.content, specResult.format, descriptor);

      // Inject the spec into the PUT body for APIM to import
      json = {
        ...json,
        properties: {
          ...cleanProps,
          format: importFormat,
          value: sanitizedContent,
        },
      };

      specImported = true;
      logger.info(`Including ${specResult.format} specification in API import for "${getNamePart(descriptor.nameParts, 0)}"`);
    }
  }

  json = applyApiPathPrefix(json, descriptor, config);
  json = normalizeApiVersionSetId(
    json,
    context,
    descriptor.workspace,
    config.envMapping
  );
  const deployedDescriptor = config.envMapping
    ? mapDescriptor(descriptor, config.envMapping)
    : descriptor;

  // PUT the API resource to APIM
  try {
    await client.putResource(context, deployedDescriptor, json);
  } catch (error) {
    throw new ApiPutAttemptError(error);
  }

  return {
    descriptor,
    status: 'success',
    action: 'put',
    specImported,
    isCurrent,
  };
}

async function alignActiveRevisionWithSource(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<RootApiResult & ResourcePublishResult> {
  logger.debug(
    `Source marks "${getNamePart(descriptor.nameParts, 0)}" as current; re-applying root metadata to align active revision`
  );

  return publishRootApi(client, store, context, descriptor, config, {
    includeSpecification: false,
  });
}

/**
 * Find and publish API revisions in numeric order
 */
async function publishApiRevisions(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  config: PublishConfig,
  revisionDescriptors: ResourceDescriptor[]
): Promise<ResourcePublishResult[]> {
  // Publish each revision in order
  const results: ResourcePublishResult[] = [];
  for (const revDescriptor of revisionDescriptors) {
    results.push(await publishResource(client, store, context, revDescriptor, config));
  }

  return results;
}

/**
 * Properties allowed in operation PATCH bodies.
 * Restricted to fields that are valid for all API types (HTTP, SOAP, GraphQL, WebSocket, A2A).
 * Avoids sending fields APIM rejects on non-HTTP API types.
 */
const OPERATION_PATCH_ALLOWLIST: ReadonlySet<string> = new Set([
  'displayName',
  'description',
  'method',
  'urlTemplate',
  'templateParameters',
  'request',
  'responses',
  'policies',
]);

/**
 * Resource types that are auto-created by APIM when importing a spec.
 * Both ApiOperation and ApiSchema are initially excluded, but we selectively
 * re-add: explicitly named schemas (non-auto-generated 24-char hex IDs).
 * Operations are always reconciled via PATCH after spec import.
 */
const SPEC_MANAGED_CHILD_TYPES = new Set<ResourceType>([
  ResourceType.ApiOperation,
  ResourceType.ApiSchema,
]);

/**
 * Publish all child resources of an API in parallel.
 * When specImported is true, skips ApiSchema and ApiOperation since APIM
 * auto-creates those from the imported specification. However:
 * - All operations are reconciled via PATCH after spec import to restore
 *   persisted metadata (description, schema references, etc.)
 * - Explicitly named schemas (non-24-char-hex IDs) are also re-published
 */
async function publishApiChildren(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  config: PublishConfig,
  plan: ApiPublicationPlan
): Promise<ResourcePublishResult[]> {
  const results: ResourcePublishResult[] = [];
  // Group resources by publish tier for dependency ordering.
  // Lower tiers are published first (parents before children, operations before policies).
  // Resources in the same tier can be published in parallel.
  const tierMap = new Map<number, ResourceDescriptor[]>();
  for (const d of plan.childPuts) {
    const tier = getPublishTier(d.type);
    const existing = tierMap.get(tier) ?? [];
    existing.push(d);
    tierMap.set(tier, existing);
  }

  // Publish each tier in order (lowest to highest)
  const sortedTiers = [...tierMap.keys()].sort((a, b) => a - b);
  for (const tier of sortedTiers) {
    const descriptors = tierMap.get(tier) ?? [];
    if (descriptors.length > 0) {
      const tasks = descriptors.map((descriptor) => async () => {
        return publishResource(client, store, context, descriptor, config);
      });
      const taskResults = await runParallel(tasks, 5);
      for (const [index, taskResult] of (taskResults ?? []).entries()) {
        if (taskResult.status === 'fulfilled' && taskResult.value) {
          results.push(taskResult.value);
        } else if (taskResult.status === 'rejected') {
          const childDescriptor = descriptors[index];
          if (childDescriptor) {
            results.push({
              descriptor: childDescriptor,
              status: 'failed',
              action: 'put',
              error: taskResult.reason,
            });
          }
        }
      }
    }
  }

  results.push(...await reconcileOperationsAfterSpecImport(
    client,
    context,
    plan.operationPatches,
    config
  ));
  return results;
}

/**
 * Reconcile all API operations after a spec import by PATCHing each operation
 * with its persisted metadata. Only allow-listed properties are sent in the
 * PATCH body so APIM does not reject the request for non-HTTP API types.
 *
 * Skips operations with auto-generated IDs (24-char hex) — these are SOAP
 * operations recreated by the WSDL importer; their persisted JSON, if any,
 * should not override the importer's result.
 */
async function reconcileOperationsAfterSpecImport(
  client: IApimClient,
  context: ApimServiceContext,
  operationPatches: ApiPatchPlan[],
  config: PublishConfig
): Promise<ResourcePublishResult[]> {
  const tasks = operationPatches.map(({ descriptor, payload }) => async () => {
    try {
      const deployedDescriptor = config.envMapping
        ? mapDescriptor(descriptor, config.envMapping)
        : descriptor;
      await client.patchResource(context, deployedDescriptor, payload);
      logger.debug(`Reconciled operation "${getNamePart(descriptor.nameParts, 1)}" after spec import`);
      const result: ResourcePublishResult = {
        descriptor,
        status: 'success',
        action: 'patch',
      };
      return result;
    } catch (error) {
      logger.warn(
        `Failed to reconcile operation "${getNamePart(descriptor.nameParts, 1)}" after spec import: ${(error as Error).message}`
      );
      const result: ResourcePublishResult = {
        descriptor,
        status: 'failed',
        action: 'patch',
        error: error instanceof Error ? error : new Error(String(error)),
      };
      return result;
    }
  });

  if (tasks.length > 0) {
    logger.debug(
      `Reconciling ${tasks.length} operation(s) after spec import`
    );
    const taskResults = await runParallel(tasks, 5);
    return (taskResults ?? []).flatMap((taskResult, index) => {
      if (taskResult.status === 'fulfilled' && taskResult.value) {
        return [taskResult.value];
      }
      const patch = operationPatches[index];
      return patch
        ? [{
            descriptor: patch.descriptor,
            status: 'failed' as const,
            action: 'patch' as const,
            error: taskResult.reason,
          }]
        : [];
    });
  }
  return [];
}

async function buildOperationPatchPayload(
  store: IArtifactStore,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<Record<string, unknown> | undefined> {
  const json = await store.readResource(config.sourceDir, descriptor);
  if (!json) return undefined;
  const mergedJson = applyOverrides(descriptor, json, config.overrides);
  const props = mergedJson.properties as Record<string, unknown> | undefined;
  if (!props) return undefined;

  const patchProps: Record<string, unknown> = {};
  for (const key of OPERATION_PATCH_ALLOWLIST) {
    if (Object.hasOwn(props, key)) {
      patchProps[key] = props[key];
    }
  }

  if (hasSchemaBoundRepresentations(patchProps)) {
    delete patchProps.request;
    delete patchProps.responses;
  }
  stripRepresentationSchemaRefs(patchProps);

  return Object.keys(patchProps).length > 0
    ? { properties: patchProps }
    : undefined;
}

/**
 * Check whether any request/responses representation carries a schema binding
 * (schemaId or typeName). Such operations are fully owned by the spec import
 * and must not have request/responses re-sent in the reconcile PATCH.
 */
function hasSchemaBoundRepresentations(patchProps: Record<string, unknown>): boolean {
  const hasRef = (items: unknown): boolean =>
    Array.isArray(items) &&
    items.some(
      (item: unknown) =>
        item !== null &&
        typeof item === 'object' &&
        (Object.hasOwn(item, 'schemaId') || Object.hasOwn(item, 'typeName')) &&
        ((item as Record<string, unknown>).schemaId != null ||
          (item as Record<string, unknown>).typeName != null)
    );

  const request = patchProps.request;
  if (request && typeof request === 'object' && hasRef((request as Record<string, unknown>).representations)) {
    return true;
  }

  const responses = patchProps.responses;
  if (Array.isArray(responses)) {
    for (const response of responses) {
      if (response && typeof response === 'object' && hasRef((response as Record<string, unknown>).representations)) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Strip source schema refs from operation parameters and representations
 * before PATCH. APIM assigns new schema IDs on spec import, so stale IDs
 * from the source instance would cause "Operation references schema that
 * does not exist" validation errors.
 */
function stripRepresentationSchemaRefs(patchProps: Record<string, unknown>): void {
  const SCHEMA_REF_FIELDS = ['schemaId', 'typeName'];

  function stripFromItems(items: unknown): void {
    if (!Array.isArray(items)) return;
    for (const item of items) {
      if (item && typeof item === 'object') {
        for (const field of SCHEMA_REF_FIELDS) {
          delete (item as Record<string, unknown>)[field];
        }
      }
    }
  }

  // Strip schema refs from top-level templateParameters.
  stripFromItems(patchProps.templateParameters);

  // Strip schema refs from request parameters and representations.
  const request = patchProps.request;
  if (request && typeof request === 'object') {
    const req = request as Record<string, unknown>;
    stripFromItems(req.representations);
    stripFromItems(req.queryParameters);
    stripFromItems(req.headers);
  }

  // Strip schema refs from responses[].representations and headers.
  const responses = patchProps.responses;
  if (Array.isArray(responses)) {
    for (const response of responses) {
      if (response && typeof response === 'object') {
        const resp = response as Record<string, unknown>;
        stripFromItems(resp.representations);
        stripFromItems(resp.headers);
      }
    }
  }
}

/**
 * Extract revision number from API name (e.g., "my-api;rev=2" -> 2)
 */
function extractRevisionNumber(apiName: string): number {
  const match = /;rev=(\d+)/.exec(apiName);
  return match ? parseInt(match[1], 10) : 0;
}

function getApiIsCurrent(json: Record<string, unknown>): boolean | undefined {
  const properties = json.properties as Record<string, unknown> | undefined;
  const isCurrent = properties?.isCurrent;
  return typeof isCurrent === 'boolean' ? isCurrent : undefined;
}

async function alignImportedOperationDescriptions(
  client: IApimClient,
  context: ApimServiceContext,
  operationDescriptors: ResourceDescriptor[],
  config: PublishConfig
): Promise<ResourcePublishResult[]> {
  const results: ResourcePublishResult[] = [];
  for (const operationDescriptor of operationDescriptors) {
    const deployedDescriptor = config.envMapping
      ? mapDescriptor(operationDescriptor, config.envMapping)
      : operationDescriptor;
    let operation: Record<string, unknown> | undefined;
    try {
      operation = await client.getResource(context, deployedDescriptor);
    } catch (error) {
      results.push({
        descriptor: operationDescriptor,
        status: 'failed',
        action: 'noop',
        error: error instanceof Error ? error : new Error(String(error)),
      });
      continue;
    }
    if (!operation) {
      results.push({
        descriptor: operationDescriptor,
        status: 'skipped',
        action: 'noop',
      });
      continue;
    }

    const props = operation.properties as Record<string, unknown> | undefined;
    if (!props) {
      results.push({
        descriptor: operationDescriptor,
        status: 'skipped',
        action: 'noop',
      });
      continue;
    }

    try {
      await client.putResource(context, deployedDescriptor, {
        ...operation,
        properties: {
          ...props,
          description: null,
        },
      });
      results.push({
        descriptor: operationDescriptor,
        status: 'success',
        action: 'put',
      });
    } catch (error) {
      results.push({
        descriptor: operationDescriptor,
        status: 'failed',
        action: 'put',
        error: error instanceof Error ? error : new Error(String(error)),
      });
    }
  }
  return results;
}

class ApiPutAttemptError extends Error {
  readonly originalError: Error;

  constructor(error: unknown) {
    const originalError = error instanceof Error ? error : new Error(String(error));
    super(originalError.message, { cause: originalError });
    this.name = 'ApiPutAttemptError';
    this.originalError = originalError;
  }
}

function deduplicateDescriptors(descriptors: ResourceDescriptor[]): ResourceDescriptor[] {
  const seen = new Set<string>();
  return descriptors.filter((descriptor) => {
    const key = getResourceDescriptorKey(descriptor);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function getOpenApiOperationIdsWithNullDescription(
  specContent: string,
  specFormat?: string
): string[] {
  try {
    const parsed: unknown =
      specFormat === 'json'
        ? JSON.parse(specContent)
        : yaml.load(specContent);

    if (!parsed || typeof parsed !== 'object') {
      return [];
    }

    const parsedRecord = parsed as Record<string, unknown>;
    const pathsValue = parsedRecord.paths;
    if (!pathsValue || typeof pathsValue !== 'object') {
      return [];
    }

    const paths = pathsValue as Record<string, unknown>;

    const methods = new Set(['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']);
    const operationIds = new Set<string>();

    for (const pathItem of Object.values(paths)) {
      if (!pathItem || typeof pathItem !== 'object') {
        continue;
      }

      for (const [methodName, operation] of Object.entries(pathItem as Record<string, unknown>)) {
        if (!methods.has(methodName.toLowerCase()) || !operation || typeof operation !== 'object') {
          continue;
        }

        const operationRecord = operation as Record<string, unknown>;
        const operationId = operationRecord.operationId;
        if (typeof operationId !== 'string' || operationId.length === 0) {
          continue;
        }

        if (!Object.hasOwn(operationRecord, 'description') || operationRecord.description == null) {
          operationIds.add(operationId);
        }
      }
    }

    return [...operationIds];
  } catch {
    return [];
  }
}

/**
 * Detects the spec dialect of a JSON spec document. Returns 'swagger2' when the
 * content is a Swagger 2.0 JSON document (top-level `"swagger": "2.0"`),
 * otherwise 'openapi3'. Only JSON specs are inspected because APIM's Swagger 2.0
 * inline import (`swagger-json`) accepts JSON only; YAML specs are treated as
 * OpenAPI 3.x.
 */
function detectSpecDialect(content: string, format: string | undefined): ApiSpecDialect {
  const isJson =
    !format ||
    format.toLowerCase().includes('json') ||
    content.trimStart().startsWith('{');
  if (!isJson) return 'openapi3';
  try {
    const spec = JSON.parse(content) as Record<string, unknown>;
    return spec.swagger === '2.0' ? 'swagger2' : 'openapi3';
  } catch {
    return 'openapi3';
  }
}

/**
 * Sanitize an OpenAPI spec before importing into APIM.
 * Currently handles:
 *  - Missing path parameter declarations: APIM rejects specs where a URL
 *    template contains `{param}` placeholders that are not declared in the
 *    operation's `parameters` array.  We auto-inject the missing declarations
 *    using the document's native parameter shape — OpenAPI 3.x uses
 *    `{ ..., schema: { type: "string" } }` while Swagger 2.0 uses
 *    `{ ..., type: "string" }` — and log a warning for each one.
 */
function sanitizeOpenApiSpec(
  content: string,
  format: string | undefined,
  descriptor: ResourceDescriptor
): string {
  // Only process JSON-based OpenAPI specs (openapi+json, json)
  const isJson =
    !format ||
    format.toLowerCase().includes('json') ||
    content.trimStart().startsWith('{');
  if (!isJson) return content;

  let spec: Record<string, unknown>;
  try {
    spec = JSON.parse(content) as Record<string, unknown>;
  } catch {
    return content; // Not valid JSON — return as-is
  }

  // Swagger 2.0 path parameters are declared inline (`type: string`) rather
  // than wrapped in a `schema` object as in OpenAPI 3.x. Inject the matching
  // shape so the document stays valid for its native import format.
  const isSwagger2 = spec.swagger === '2.0';

  const paths = spec.paths as Record<string, Record<string, unknown>> | undefined;
  if (!paths) return content;

  const apiLabel = getNamePart(descriptor.nameParts, 0);
  let modified = false;

  for (const [pathTemplate, pathItem] of Object.entries(paths)) {
    // Extract placeholders from the path template
    const placeholders = pathTemplate.match(/\{([^}]+)\}/g);
    if (!placeholders) continue;
    const placeholderNames = placeholders.map((p) => p.slice(1, -1));

    for (const [method, operation] of Object.entries(pathItem)) {
      // Skip non-operation keys (e.g. "summary", "parameters", "servers")
      if (typeof operation !== 'object' || operation === null) continue;
      if (!['get', 'put', 'post', 'delete', 'patch', 'head', 'options', 'trace'].includes(method)) continue;

      const op = operation as Record<string, unknown>;
      const params = (op.parameters ?? []) as Array<Record<string, unknown>>;
      const declaredPathParams = new Set(
        params
          .filter((p) => p.in === 'path')
          .map((p) => p.name as string)
      );

      for (const name of placeholderNames) {
        if (!declaredPathParams.has(name)) {
          // Inject the missing parameter declaration using the document's
          // native parameter shape (Swagger 2.0 vs OpenAPI 3.x).
          const newParam: Record<string, unknown> = isSwagger2
            ? { name, in: 'path', required: true, type: 'string' }
            : { name, in: 'path', required: true, schema: { type: 'string' } };
          const updatedParams = [...params, newParam];
          op.parameters = updatedParams;
          // Update params reference for subsequent placeholder checks on this operation
          params.push(newParam);
          declaredPathParams.add(name);
          modified = true;

          const opSummary = (op.summary ?? op.operationId ?? `${method.toUpperCase()} ${pathTemplate}`) as string;
          logger.warn(
            `API "${apiLabel}": auto-injected missing path parameter "{${name}}" for operation "${opSummary}"`
          );
        }
      }
    }
  }

  return modified ? JSON.stringify(spec) : content;
}
