// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Compare service orchestrator
 * Coordinates resource enumeration, normalization, and comparison
 */

import type { IApimClient } from '../clients/iapim-client.js';
import type { IArtifactStore } from '../clients/iartifact-store.js';
import { logger } from '../lib/logger.js';
import {
  normalizeResource,
  isAutoGeneratedName,
  isSecretNamedValue,
  isLoggerWithCredentials,
  NormalizeContext,
} from '../lib/compare-normalizer.js';
import {
  compareNormalizedResources,
  ResourceDiff,
} from '../lib/compare-differ.js';
import { RESOURCE_TYPE_METADATA, ResourceType } from '../models/resource-types.js';
import { ApimServiceContext, ResourceDescriptor } from '../models/types.js';
import { CompareConfig, OverrideConfig } from '../models/config.js';
import { LogLevel } from '../lib/logger.js';
import { getRelativeResourceId } from '../lib/resource-uri.js';
import { loadLocalArtifacts } from './local-artifact-loader.js';

const resolveRelativeResourceId = getRelativeResourceId;

export interface CompareResult {
  sourceResourceId?: string;
  targetResourceId?: string;
  totalDifferences: number;
  differences: ComparisonDifference[];
}

export interface ComparisonDifference {
  instance?: 'source' | 'target';
  resourceType: string;
  resourceName: string;
  displayName?: string;
  relativeResourceId?: string;
  diffType: 'missing' | 'extra' | 'property-diff';
  diffs?: ResourceDiff[];
}
/**
 * Compares two APIM instances and returns differences
 */
export async function compareApimInstances(
  config: CompareConfig,
): Promise<CompareResult> {
  const shouldLogInfo = config.format !== 'json';
  if (shouldLogInfo) {
    logger.info(
      `Comparing ${config.source.serviceName} → ${config.target.serviceName}`,
    );
  }

  const normalizeContext: NormalizeContext = {
    sourceServiceName: config.source.serviceName,
    targetServiceName: config.target.serviceName,
    sourceSubscriptionId: config.source.subscriptionId,
    targetSubscriptionId: config.target.subscriptionId,
    sourceResourceGroup: config.source.resourceGroup,
    targetResourceGroup: config.target.resourceGroup,
  };

  const differences: ComparisonDifference[] = [];

  // Get clients from config
  const sourceClient: IApimClient = config.sourceClient;
  const targetClient: IApimClient = config.targetClient;

  // Top-level resource types
  const topLevelTypes: ReadonlyArray<{
    readonly type: ResourceType;
    readonly exclude?: Set<string>;
    readonly skipSecretValues?: boolean;
    readonly skipLoggerCreds?: boolean;
  }> = [
    { type: ResourceType.NamedValue, skipSecretValues: true },
    { type: ResourceType.Tag },
    { type: ResourceType.Gateway },
    { type: ResourceType.VersionSet },
    { type: ResourceType.Backend },
    { type: ResourceType.Group },
    { type: ResourceType.PolicyFragment },
    { type: ResourceType.GlobalSchema },
    { type: ResourceType.Logger, skipLoggerCreds: true },
    { type: ResourceType.Diagnostic },
    { type: ResourceType.ServicePolicy },
    { type: ResourceType.Product },
    { type: ResourceType.Subscription },
    // Note: Workspace types not yet defined in ResourceType enum
    // { type: ResourceType.Workspace },
    { type: ResourceType.Documentation },
    { type: ResourceType.PolicyRestriction },
  ];

  // Compare top-level types
  for (const typeConfig of topLevelTypes) {
    const typeDiffs = await compareResourceType(
      typeConfig.type,
      sourceClient,
      targetClient,
      normalizeContext,
      config.source,
      config.target,
      typeConfig.exclude,
      typeConfig.skipSecretValues ?? false,
      typeConfig.skipLoggerCreds ?? false,
    );
    differences.push(...typeDiffs);
  }

  // Compare APIs
  const apiDiffs = await compareResourceType(
    ResourceType.Api,
    sourceClient,
    targetClient,
    normalizeContext,
    config.source,
    config.target,
  );
  differences.push(...apiDiffs);

  // Enumerate APIs for child resource comparison
  const sourceApis = await safeListResources(
    sourceClient,
    ResourceType.Api,
    config.source,
  );
  const apiNames = sourceApis
    .map((api) => {
      const id = api.id;
      if (typeof id !== 'string') return '';
      return extractResourceName(id);
    })
    .filter(Boolean);

  // Compare API children
  for (const apiName of apiNames) {
    const apiChildTypes: readonly ResourceType[] = [
      ResourceType.ApiOperation,
      ResourceType.ApiPolicy,
      ResourceType.ApiSchema,
      ResourceType.ApiTag,
      ResourceType.ApiDiagnostic,
      ResourceType.GraphQLResolver,
      ResourceType.ApiRelease,
      ResourceType.ApiWiki,
      ResourceType.ApiTagDescription,
    ];

    for (const childType of apiChildTypes) {
      const childDiffs = await compareApiChildType(
        apiName,
        childType,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...childDiffs);
    }

    // API Operation Policies
    const operations = await safeListResources(
      sourceClient,
      ResourceType.ApiOperation,
      config.source,
      { type: ResourceType.Api, nameParts: [apiName] },
    );
    for (const op of operations) {
      const opId = op.id;
      if (typeof opId !== 'string') continue;
      const opName = extractResourceName(opId);
      const opPolicyDiffs = await compareApiOperationPolicy(
        apiName,
        opName,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...opPolicyDiffs);
    }

    // API Resolver Policies
    const resolvers = await safeListResources(
      sourceClient,
      ResourceType.GraphQLResolver,
      config.source,
      { type: ResourceType.Api, nameParts: [apiName] },
    );
    for (const resolver of resolvers) {
      const resolverId = resolver.id;
      if (typeof resolverId !== 'string') continue;
      const resolverName = extractResourceName(resolverId);
      const resolverPolicyDiffs = await compareApiResolverPolicy(
        apiName,
        resolverName,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...resolverPolicyDiffs);
    }
  }

  // Compare Products and their children
  const sourceProducts = await safeListResources(
    sourceClient,
    ResourceType.Product,
    config.source,
  );
  const productNames = sourceProducts
    .map((p) => {
      const id = p.id;
      if (typeof id !== 'string') return '';
      return extractResourceName(id);
    })
    .filter(Boolean);

  for (const productName of productNames) {
    const productChildTypes: readonly ResourceType[] = [
      ResourceType.ProductPolicy,
      ResourceType.ProductApi,
      ResourceType.ProductGroup,
      ResourceType.ProductTag,
      ResourceType.ProductWiki,
    ];

    for (const childType of productChildTypes) {
      const childDiffs = await compareProductChildType(
        productName,
        childType,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...childDiffs);
    }
  }

  // Compare Gateway APIs
  const sourceGateways = await safeListResources(
    sourceClient,
    ResourceType.Gateway,
    config.source,
  );
  for (const gateway of sourceGateways) {
    const gatewayId = gateway.id;
    if (typeof gatewayId !== 'string') continue;
    const gatewayName = extractResourceName(gatewayId);
    const gatewayApiDiffs = await compareGatewayApis(
      gatewayName,
      sourceClient,
      targetClient,
      normalizeContext,
      config.source,
      config.target,
    );
    differences.push(...gatewayApiDiffs);
  }

  // Note: Workspace comparison disabled - Workspace types not yet defined in ResourceType enum
  /*
  // Compare Workspaces and their children
  const sourceWorkspaces = await safeListResources(
    sourceClient,
    ResourceType.Workspace,
    config.source,
  );
  for (const workspace of sourceWorkspaces) {
    const wsId = workspace.id;
    if (typeof wsId !== 'string') continue;
    const wsName = extractResourceName(wsId);
    const wsChildTypes: readonly ResourceType[] = [
      ResourceType.WorkspaceApi,
      ResourceType.WorkspaceProduct,
      ResourceType.WorkspaceBackend,
      ResourceType.WorkspaceNamedValue,
      ResourceType.WorkspaceTag,
      ResourceType.WorkspaceGroup,
      ResourceType.WorkspacePolicyFragment,
      ResourceType.WorkspaceSchema,
      ResourceType.WorkspaceLogger,
      ResourceType.WorkspaceDiagnostic,
      ResourceType.WorkspacePolicy,
      ResourceType.WorkspaceSubscription,
      ResourceType.WorkspaceApiVersionSet,
    ];

    for (const childType of wsChildTypes) {
      const childDiffs = await compareWorkspaceChildType(
        wsName,
        childType,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...childDiffs);
    }
  }
  */

  const totalDifferences = differences.filter(
    (d) => d.diffType !== 'property-diff' || (d.diffs && d.diffs.length > 0),
  ).length;

  return {
    sourceResourceId: config.source.baseUrl,
    targetResourceId: config.target.baseUrl,
    totalDifferences,
    differences,
  };
}

/**
 * Compares a single resource type between source and target
 */
async function compareResourceType(
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
  excludeNames?: Set<string>,
  skipSecretValues = false,
  skipLoggerCreds = false,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel: string = metadata.armResourceType;

  logger.debug(`Comparing ${typeLabel}...`);

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
    excludeNames,
    skipSecretValues,
    skipLoggerCreds,
  );
}

/**
 * Compares API child resources
 */
async function compareApiChildType(
  apiName: string,
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel: string = `${apiName}/${metadata.armResourceType}`;

  const apiDescriptor: ResourceDescriptor = {
    type: ResourceType.Api,
    nameParts: [apiName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
    apiDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
    apiDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares API operation policies
 */
async function compareApiOperationPolicy(
  apiName: string,
  operationName: string,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const typeLabel = `${apiName}/operations/${operationName}/policies`;

  const operationDescriptor: ResourceDescriptor = {
    type: ResourceType.ApiOperation,
    nameParts: [apiName, operationName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    ResourceType.ApiOperationPolicy,
    sourceContext,
    operationDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    ResourceType.ApiOperationPolicy,
    targetContext,
    operationDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares API resolver policies
 */
async function compareApiResolverPolicy(
  apiName: string,
  resolverName: string,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const typeLabel = `${apiName}/resolvers/${resolverName}/policies`;

  const resolverDescriptor: ResourceDescriptor = {
    type: ResourceType.GraphQLResolver,
    nameParts: [apiName, resolverName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    ResourceType.GraphQLResolverPolicy,
    sourceContext,
    resolverDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    ResourceType.GraphQLResolverPolicy,
    targetContext,
    resolverDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares Product child resources
 */
async function compareProductChildType(
  productName: string,
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel: string = `${productName}/${metadata.armResourceType}`;

  const productDescriptor: ResourceDescriptor = {
    type: ResourceType.Product,
    nameParts: [productName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
    productDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
    productDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares Gateway APIs
 */
async function compareGatewayApis(
  gatewayName: string,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const typeLabel = `${gatewayName}/apis`;

  const gatewayDescriptor: ResourceDescriptor = {
    type: ResourceType.Gateway,
    nameParts: [gatewayName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    ResourceType.GatewayApi,
    sourceContext,
    gatewayDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    ResourceType.GatewayApi,
    targetContext,
    gatewayDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares Workspace child resources (DISABLED - Workspace types not yet in ResourceType enum)
 */
/*
async function compareWorkspaceChildType(
  workspaceName: string,
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel: string = `${workspaceName}/${metadata.armResourceType}`;

  const workspaceDescriptor: ResourceDescriptor = {
    type: ResourceType.Workspace,
    nameParts: [workspaceName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
    workspaceDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
    workspaceDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares two resource lists and returns differences
 */
function compareResourceLists(
  typeLabel: string,
  sourceResources: Array<Record<string, unknown>>,
  targetResources: Array<Record<string, unknown>>,
  normalizeContext: NormalizeContext,
  excludeNames?: Set<string>,
  skipSecretValues = false,
  skipLoggerCreds = false,
): ComparisonDifference[] {
  const differences: ComparisonDifference[] = [];

  // Build resource maps, handling auto-generated IDs
  const sourceMap = buildResourceMap(
    sourceResources,
    normalizeContext,
    excludeNames,
  );
  const targetMap = buildResourceMap(
    targetResources,
    normalizeContext,
    excludeNames,
  );

  // Find missing resources (in source but not in target)
  for (const name of sourceMap.keys()) {
    if (!targetMap.has(name)) {
      const sourceResource = sourceMap.get(name)!;
      const displayName = getComparisonDisplayName(sourceResource);
      const sourceResourceId =
        typeof sourceResource.id === 'string' ? sourceResource.id : undefined;
      const relativeResourceId = resolveRelativeResourceId(
        sourceResourceId ?? '',
        normalizeContext.sourceServiceName,
      );

      differences.push({
        resourceType: typeLabel,
        resourceName: name,
        diffType: 'missing',
        ...(displayName === undefined ? {} : { displayName }),
        ...(relativeResourceId === undefined
          ? {}
          : { relativeResourceId }),
        instance: 'source',
      });
    }
  }

  // Find extra resources (in target but not in source)
  for (const name of targetMap.keys()) {
    if (!sourceMap.has(name)) {
      const targetResource = targetMap.get(name)!;
      const displayName = getComparisonDisplayName(targetResource);
      const targetResourceId =
        typeof targetResource.id === 'string' ? targetResource.id : undefined;
      const relativeResourceId = resolveRelativeResourceId(
        targetResourceId ?? '',
        normalizeContext.targetServiceName,
      );

      differences.push({
        resourceType: typeLabel,
        resourceName: name,
        diffType: 'extra',
        ...(displayName === undefined ? {} : { displayName }),
        ...(relativeResourceId === undefined
          ? {}
          : { relativeResourceId }),
        instance: 'target',
      });
    }
  }

  // Compare matched resources
  for (const name of sourceMap.keys()) {
    if (!targetMap.has(name)) continue;

    const sourceResource = sourceMap.get(name)!;
    const targetResource = targetMap.get(name)!;
    const displayName =
      getComparisonDisplayName(sourceResource) ??
      getComparisonDisplayName(targetResource);
    const sourceResourceId =
      typeof sourceResource.id === 'string' ? sourceResource.id : undefined;
    const targetResourceId =
      typeof targetResource.id === 'string' ? targetResource.id : undefined;
    const relativeResourceId =
      resolveRelativeResourceId(sourceResourceId ?? '', normalizeContext.sourceServiceName) ??
      resolveRelativeResourceId(targetResourceId ?? '', normalizeContext.targetServiceName);

    const sourceNorm = normalizeResource(sourceResource, normalizeContext);
    const targetNorm = normalizeResource(targetResource, normalizeContext);

    // Skip secret named-value .value
    if (skipSecretValues && isSecretNamedValue(sourceResource)) {
      if (
        sourceNorm.properties &&
        typeof sourceNorm.properties === 'object'
      ) {
        const props = sourceNorm.properties as Record<string, unknown>;
        delete props.value;
      }
      if (
        targetNorm.properties &&
        typeof targetNorm.properties === 'object'
      ) {
        const props = targetNorm.properties as Record<string, unknown>;
        delete props.value;
      }
    }

    // Skip Event Hub/App Insights logger credentials
    if (skipLoggerCreds && isLoggerWithCredentials(sourceResource)) {
      if (
        sourceNorm.properties &&
        typeof sourceNorm.properties === 'object'
      ) {
        const props = sourceNorm.properties as Record<string, unknown>;
        delete props.credentials;
      }
      if (
        targetNorm.properties &&
        typeof targetNorm.properties === 'object'
      ) {
        const props = targetNorm.properties as Record<string, unknown>;
        delete props.credentials;
      }
    }

    const diffs = compareNormalizedResources(sourceNorm, targetNorm);
    if (diffs.length > 0) {
      differences.push({
        resourceType: typeLabel,
        resourceName: name,
        diffType: 'property-diff',
        ...(displayName === undefined ? {} : { displayName }),
        ...(relativeResourceId === undefined
          ? {}
          : { relativeResourceId }),
        diffs,
      });
    }
  }

  return differences;
}

function getComparisonDisplayName(
  resource: Record<string, unknown>,
): string | undefined {
  const properties = resource.properties;
  if (typeof properties === 'object' && properties !== null) {
    const displayName = (properties as Record<string, unknown>).displayName;
    if (typeof displayName === 'string' && displayName.length > 0) {
      return displayName;
    }
  }

  const displayName = resource.displayName;
  if (typeof displayName === 'string' && displayName.length > 0) {
    return displayName;
  }

  return undefined;
}

/**
 * Builds a resource map keyed by name, handling auto-generated IDs
 */
function buildResourceMap(
  resources: Array<Record<string, unknown>>,
  normalizeContext: NormalizeContext,
  excludeNames?: Set<string>,
): Map<string, Record<string, unknown>> {
  const map = new Map<string, Record<string, unknown>>();
  const autoIdItems: Array<{
    resource: Record<string, unknown>;
    normalizedJson: string;
  }> = [];

  for (const resource of resources) {
    const id = resource.id;
    if (typeof id !== 'string') continue;
    const name = extractResourceName(id);
    if (excludeNames?.has(name)) continue;

    // Auto-generated IDs: key by normalized content
    if (isAutoGeneratedName(name)) {
      const normalized = normalizeResource(resource, normalizeContext);
      const normalizedJson = JSON.stringify(normalized);
      autoIdItems.push({ resource, normalizedJson });
    } else {
      map.set(name, resource);
    }
  }

  // Sort auto-ID items by normalized JSON and assign positional keys
  autoIdItems.sort((a, b) => a.normalizedJson.localeCompare(b.normalizedJson));
  autoIdItems.forEach((item, index) => {
    map.set(`{{auto-id-${index}}}`, item.resource);
  });

  return map;
}

/**
 * Safely lists resources, returning empty array on error
 */
async function safeListResources(
  client: IApimClient,
  resourceType: ResourceType,
  context: ApimServiceContext,
  parent?: ResourceDescriptor,
): Promise<Array<Record<string, unknown>>> {
  try {
    const resources: Array<Record<string, unknown>> = [];
    const iterable = client.listResources(context, resourceType, parent);
    for await (const resource of iterable) {
      resources.push(resource);
    }
    return resources;
  } catch (error) {
    logger.debug(
      `Failed to list ${resourceType}: ${error instanceof Error ? error.message : String(error)}`,
    );
    return [];
  }
}

/**
 * Extracts resource name from ARM resource ID
 */
function extractResourceName(resourceId: string): string {
  const parts = resourceId.split('/');
  return parts[parts.length - 1] || '';
}

/**
 * Compares local artifact directories
 */
export async function compareLocalArtifacts(
  artifactStore: IArtifactStore,
  sourceDir: string,
  targetDir: string,
  overrides?: OverrideConfig,
  _format: 'text' | 'json' | 'table' = 'text',
  _logLevel?: LogLevel,
): Promise<CompareResult> {
  const shouldLogInfo = _format !== 'json';
  if (shouldLogInfo) {
    logger.info(`Comparing local artifacts: ${sourceDir} → ${targetDir}`);
  }

  // Load artifacts from both directories
  const sourceArtifacts = await loadLocalArtifacts(
    artifactStore,
    sourceDir,
    overrides,
  );
  const targetArtifacts = await loadLocalArtifacts(
    artifactStore,
    targetDir,
    undefined, // No overrides for target
  );

  // Create a normalized context with placeholder values
  // For local compare, we use placeholders since there are no actual subscriptions/RGs
  const normalizeContext: NormalizeContext = {
    sourceServiceName: 'source',
    targetServiceName: 'target',
    sourceSubscriptionId: '00000000-0000-0000-0000-000000000000',
    targetSubscriptionId: '00000000-0000-0000-0000-000000000000',
    sourceResourceGroup: 'source-rg',
    targetResourceGroup: 'target-rg',
  };

  const differences: ComparisonDifference[] = [];

  // Get all unique resource types from both sources
  const allTypes = new Set<string>();
  sourceArtifacts.forEach((_, type) => allTypes.add(type));
  targetArtifacts.forEach((_, type) => allTypes.add(type));

  // Compare each resource type
  for (const resourceType of allTypes) {
    const sourceResources = sourceArtifacts.get(resourceType) ?? [];
    const targetResources = targetArtifacts.get(resourceType) ?? [];

    // Determine skip flags based on resource type (string comparison)
    const skipSecretValues = resourceType === String(ResourceType.NamedValue);
    const skipLoggerCreds = resourceType === String(ResourceType.Logger);

    const typeDiffs = compareResourceLists(
      resourceType,
      sourceResources,
      targetResources,
      normalizeContext,
      undefined, // No exclusions for local compare
      skipSecretValues,
      skipLoggerCreds,
    );

    differences.push(...typeDiffs);
  }

  const totalDifferences = differences.filter(
    (d) => d.diffType !== 'property-diff' || (d.diffs && d.diffs.length > 0),
  ).length;

  return {
    totalDifferences,
    differences,
  };
}
