// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Compare service orchestrator
 * Coordinates resource enumeration, normalization, and comparison
 */

import { IApimClient } from '../clients/iapim-client.js';
import { logger } from '../lib/logger.js';
import {
  normalizeResource,
  isAutoGeneratedName,
  isSecretNamedValue,
  isLoggerWithCredentials,
  NormalizeContext,
} from '../lib/compare-normalizer.js';
import {
  compareNormalizedResources,
  ResourceDiff,
} from '../lib/compare-differ.js';
import { RESOURCE_TYPE_METADATA, ResourceType } from '../models/resource-types.js';
import { ApimServiceContext, ResourceDescriptor } from '../models/types.js';

export interface CompareConfig {
  source: ApimServiceContext;
  target: ApimServiceContext;
  format: 'text' | 'json' | 'table';
}

export interface CompareResult {
  totalTypes: number;
  totalResources: number;
  totalDifferences: number;
  differences: ComparisonDifference[];
}

export interface ComparisonDifference {
  resourceType: string;
  resourceName: string;
  diffType: 'missing' | 'extra' | 'property-diff';
  diffs?: ResourceDiff[];
}

// Built-in resources to exclude from comparison
const EXCLUDE_GROUPS = new Set(['administrators', 'developers', 'guests']);
const EXCLUDE_PRODUCTS = new Set(['starter', 'unlimited']);
const EXCLUDE_SUBSCRIPTIONS = new Set(['master']);
const EXCLUDE_APIS = new Set(['echo-api']);

/**
 * Compares two APIM instances and returns differences
 */
export async function compareApimInstances(
  config: CompareConfig,
): Promise<CompareResult> {
  logger.info(
    `Comparing ${config.source.serviceName} → ${config.target.serviceName}`,
  );

  const normalizeContext: NormalizeContext = {
    sourceServiceName: config.source.serviceName,
    targetServiceName: config.target.serviceName,
    sourceSubscriptionId: config.source.subscriptionId,
    targetSubscriptionId: config.target.subscriptionId,
    sourceResourceGroup: config.source.resourceGroup,
    targetResourceGroup: config.target.resourceGroup,
  };

  const differences: ComparisonDifference[] = [];
  let totalTypes = 0;
  let totalResources = 0;

  // Create clients
  const sourceClient = config.sourceClient;
  const targetClient = config.targetClient;

  // Top-level resource types
  const topLevelTypes: Array<{
    type: ResourceType;
    exclude?: Set<string>;
    skipSecretValues?: boolean;
    skipLoggerCreds?: boolean;
  }> = [
    { type: ResourceType.NamedValue, skipSecretValues: true },
    { type: ResourceType.Tag },
    { type: ResourceType.Gateway },
    { type: ResourceType.ApiVersionSet },
    { type: ResourceType.Backend },
    { type: ResourceType.Group, exclude: EXCLUDE_GROUPS },
    { type: ResourceType.PolicyFragment },
    { type: ResourceType.GlobalSchema },
    { type: ResourceType.Logger, skipLoggerCreds: true },
    { type: ResourceType.Diagnostic },
    { type: ResourceType.ServicePolicy },
    { type: ResourceType.Product, exclude: EXCLUDE_PRODUCTS },
    { type: ResourceType.Subscription, exclude: EXCLUDE_SUBSCRIPTIONS },
    { type: ResourceType.Workspace },
    { type: ResourceType.Documentation },
    { type: ResourceType.PolicyRestriction },
  ];

  // Compare top-level types
  for (const typeConfig of topLevelTypes) {
    const typeDiffs = await compareResourceType(
      typeConfig.type,
      sourceClient,
      targetClient,
      normalizeContext,
      config.source,
      config.target,
      typeConfig.exclude,
      typeConfig.skipSecretValues ?? false,
      typeConfig.skipLoggerCreds ?? false,
    );
    differences.push(...typeDiffs);
    totalTypes++;
    totalResources += typeDiffs.length;
  }

  // Compare APIs
  const apiDiffs = await compareResourceType(
    ResourceType.Api,
    sourceClient,
    targetClient,
    normalizeContext,
    config.source,
    config.target,
    EXCLUDE_APIS,
  );
  differences.push(...apiDiffs);
  totalTypes++;
  totalResources += apiDiffs.length;

  // Enumerate APIs for child resource comparison
  const sourceApis = await safeListResources(
    sourceClient,
    ResourceType.Api,
    config.source,
  );
  const apiNames = sourceApis
    .map((api) => extractResourceName(api.id as string))
    .filter((name) => !EXCLUDE_APIS.has(name));

  // Compare API children
  for (const apiName of apiNames) {
    const apiChildTypes = [
      ResourceType.ApiOperation,
      ResourceType.ApiPolicy,
      ResourceType.ApiSchema,
      ResourceType.ApiTag,
      ResourceType.ApiDiagnostic,
      ResourceType.ApiResolver,
      ResourceType.ApiRelease,
      ResourceType.ApiWiki,
      ResourceType.ApiTagDescription,
    ];

    for (const childType of apiChildTypes) {
      const childDiffs = await compareApiChildType(
        apiName,
        childType,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...childDiffs);
      totalTypes++;
      totalResources += childDiffs.length;
    }

    // API Operation Policies
    const operations = await safeListResources(
      sourceClient,
      ResourceType.ApiOperation,
      config.source,
      { type: ResourceType.Api, nameParts: [apiName] },
    );
    for (const op of operations) {
      const opName = extractResourceName(op.id as string);
      const opPolicyDiffs = await compareApiOperationPolicy(
        apiName,
        opName,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...opPolicyDiffs);
      totalTypes++;
      totalResources += opPolicyDiffs.length;
    }

    // API Resolver Policies
    const resolvers = await safeListResources(
      sourceClient,
      ResourceType.ApiResolver,
      config.source,
      { type: ResourceType.Api, nameParts: [apiName] },
    );
    for (const resolver of resolvers) {
      const resolverName = extractResourceName(resolver.id as string);
      const resolverPolicyDiffs = await compareApiResolverPolicy(
        apiName,
        resolverName,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...resolverPolicyDiffs);
      totalTypes++;
      totalResources += resolverPolicyDiffs.length;
    }
  }

  // Compare Products and their children
  const sourceProducts = await safeListResources(
    sourceClient,
    ResourceType.Product,
    config.source,
  );
  const productNames = sourceProducts
    .map((p) => extractResourceName(p.id as string))
    .filter((name) => !EXCLUDE_PRODUCTS.has(name));

  for (const productName of productNames) {
    const productChildTypes = [
      ResourceType.ProductPolicy,
      ResourceType.ProductApi,
      ResourceType.ProductGroup,
      ResourceType.ProductTag,
      ResourceType.ProductWiki,
    ];

    for (const childType of productChildTypes) {
      const childDiffs = await compareProductChildType(
        productName,
        childType,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...childDiffs);
      totalTypes++;
      totalResources += childDiffs.length;
    }
  }

  // Compare Gateway APIs
  const sourceGateways = await safeListResources(
    sourceClient,
    ResourceType.Gateway,
    config.source,
  );
  for (const gateway of sourceGateways) {
    const gatewayName = extractResourceName(gateway.id as string);
    const gatewayApiDiffs = await compareGatewayApis(
      gatewayName,
      sourceClient,
      targetClient,
      normalizeContext,
      config.source,
      config.target,
    );
    differences.push(...gatewayApiDiffs);
    totalTypes++;
    totalResources += gatewayApiDiffs.length;
  }

  // Compare Workspaces and their children
  const sourceWorkspaces = await safeListResources(
    sourceClient,
    ResourceType.Workspace,
    config.source,
  );
  for (const workspace of sourceWorkspaces) {
    const wsName = extractResourceName(workspace.id as string);
    const wsChildTypes = [
      ResourceType.WorkspaceApi,
      ResourceType.WorkspaceProduct,
      ResourceType.WorkspaceBackend,
      ResourceType.WorkspaceNamedValue,
      ResourceType.WorkspaceTag,
      ResourceType.WorkspaceGroup,
      ResourceType.WorkspacePolicyFragment,
      ResourceType.WorkspaceSchema,
      ResourceType.WorkspaceLogger,
      ResourceType.WorkspaceDiagnostic,
      ResourceType.WorkspacePolicy,
      ResourceType.WorkspaceSubscription,
      ResourceType.WorkspaceApiVersionSet,
    ];

    for (const childType of wsChildTypes) {
      const childDiffs = await compareWorkspaceChildType(
        wsName,
        childType,
        sourceClient,
        targetClient,
        normalizeContext,
        config.source,
        config.target,
      );
      differences.push(...childDiffs);
      totalTypes++;
      totalResources += childDiffs.length;
    }
  }

  const totalDifferences = differences.filter(
    (d) => d.diffType !== 'property-diff' || (d.diffs && d.diffs.length > 0),
  ).length;

  return {
    totalTypes,
    totalResources,
    totalDifferences,
    differences,
  };
}

/**
 * Compares a single resource type between source and target
 */
async function compareResourceType(
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
  excludeNames?: Set<string>,
  skipSecretValues = false,
  skipLoggerCreds = false,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel = metadata.armResourceType;

  logger.debug(`Comparing ${typeLabel}...`);

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
    excludeNames,
    skipSecretValues,
    skipLoggerCreds,
  );
}

/**
 * Compares API child resources
 */
async function compareApiChildType(
  apiName: string,
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel = `${apiName}/${metadata.armResourceType}`;

  const apiDescriptor: ResourceDescriptor = {
    type: ResourceType.Api,
    nameParts: [apiName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
    apiDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
    apiDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares API operation policies
 */
async function compareApiOperationPolicy(
  apiName: string,
  operationName: string,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const typeLabel = `${apiName}/operations/${operationName}/policies`;

  const operationDescriptor: ResourceDescriptor = {
    type: ResourceType.ApiOperation,
    nameParts: [apiName, operationName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    ResourceType.ApiOperationPolicy,
    sourceContext,
    operationDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    ResourceType.ApiOperationPolicy,
    targetContext,
    operationDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares API resolver policies
 */
async function compareApiResolverPolicy(
  apiName: string,
  resolverName: string,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const typeLabel = `${apiName}/resolvers/${resolverName}/policies`;

  const resolverDescriptor: ResourceDescriptor = {
    type: ResourceType.GraphQLResolver,
    nameParts: [apiName, resolverName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    ResourceType.GraphQLResolverPolicy,
    sourceContext,
    resolverDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    ResourceType.GraphQLResolverPolicy,
    targetContext,
    resolverDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares Product child resources
 */
async function compareProductChildType(
  productName: string,
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel = `${productName}/${metadata.armResourceType}`;

  const productDescriptor: ResourceDescriptor = {
    type: ResourceType.Product,
    nameParts: [productName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
    productDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
    productDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares Gateway APIs
 */
async function compareGatewayApis(
  gatewayName: string,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const typeLabel = `${gatewayName}/apis`;

  const gatewayDescriptor: ResourceDescriptor = {
    type: ResourceType.Gateway,
    nameParts: [gatewayName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    ResourceType.GatewayApi,
    sourceContext,
    gatewayDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    ResourceType.GatewayApi,
    targetContext,
    gatewayDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares Workspace child resources
 */
async function compareWorkspaceChildType(
  workspaceName: string,
  resourceType: ResourceType,
  sourceClient: IApimClient,
  targetClient: IApimClient,
  normalizeContext: NormalizeContext,
  sourceContext: ApimServiceContext,
  targetContext: ApimServiceContext,
): Promise<ComparisonDifference[]> {
  const metadata = RESOURCE_TYPE_METADATA[resourceType];
  const typeLabel = `${workspaceName}/${metadata.armResourceType}`;

  const workspaceDescriptor: ResourceDescriptor = {
    type: ResourceType.Workspace,
    nameParts: [workspaceName],
  };

  const sourceResources = await safeListResources(
    sourceClient,
    resourceType,
    sourceContext,
    workspaceDescriptor,
  );
  const targetResources = await safeListResources(
    targetClient,
    resourceType,
    targetContext,
    workspaceDescriptor,
  );

  return compareResourceLists(
    typeLabel,
    sourceResources,
    targetResources,
    normalizeContext,
  );
}

/**
 * Compares two resource lists and returns differences
 */
function compareResourceLists(
  typeLabel: string,
  sourceResources: Array<Record<string, unknown>>,
  targetResources: Array<Record<string, unknown>>,
  normalizeContext: NormalizeContext,
  excludeNames?: Set<string>,
  skipSecretValues = false,
  skipLoggerCreds = false,
): ComparisonDifference[] {
  const differences: ComparisonDifference[] = [];

  // Build resource maps, handling auto-generated IDs
  const sourceMap = buildResourceMap(
    sourceResources,
    normalizeContext,
    excludeNames,
  );
  const targetMap = buildResourceMap(
    targetResources,
    normalizeContext,
    excludeNames,
  );

  // Find missing resources (in source but not in target)
  for (const name of sourceMap.keys()) {
    if (!targetMap.has(name)) {
      differences.push({
        resourceType: typeLabel,
        resourceName: name,
        diffType: 'missing',
      });
    }
  }

  // Find extra resources (in target but not in source)
  for (const name of targetMap.keys()) {
    if (!sourceMap.has(name)) {
      differences.push({
        resourceType: typeLabel,
        resourceName: name,
        diffType: 'extra',
      });
    }
  }

  // Compare matched resources
  for (const name of sourceMap.keys()) {
    if (!targetMap.has(name)) continue;

    const sourceResource = sourceMap.get(name)!;
    const targetResource = targetMap.get(name)!;

    const sourceNorm = normalizeResource(sourceResource, normalizeContext);
    const targetNorm = normalizeResource(targetResource, normalizeContext);

    // Skip secret named-value .value
    if (skipSecretValues && isSecretNamedValue(sourceResource)) {
      if (
        sourceNorm.properties &&
        typeof sourceNorm.properties === 'object'
      ) {
        const props = sourceNorm.properties as Record<string, unknown>;
        delete props.value;
      }
      if (
        targetNorm.properties &&
        typeof targetNorm.properties === 'object'
      ) {
        const props = targetNorm.properties as Record<string, unknown>;
        delete props.value;
      }
    }

    // Skip Event Hub/App Insights logger credentials
    if (skipLoggerCreds && isLoggerWithCredentials(sourceResource)) {
      if (
        sourceNorm.properties &&
        typeof sourceNorm.properties === 'object'
      ) {
        const props = sourceNorm.properties as Record<string, unknown>;
        delete props.credentials;
      }
      if (
        targetNorm.properties &&
        typeof targetNorm.properties === 'object'
      ) {
        const props = targetNorm.properties as Record<string, unknown>;
        delete props.credentials;
      }
    }

    const diffs = compareNormalizedResources(sourceNorm, targetNorm);
    if (diffs.length > 0) {
      differences.push({
        resourceType: typeLabel,
        resourceName: name,
        diffType: 'property-diff',
        diffs,
      });
    }
  }

  return differences;
}

/**
 * Builds a resource map keyed by name, handling auto-generated IDs
 */
function buildResourceMap(
  resources: Array<Record<string, unknown>>,
  normalizeContext: NormalizeContext,
  excludeNames?: Set<string>,
): Map<string, Record<string, unknown>> {
  const map = new Map<string, Record<string, unknown>>();
  const autoIdItems: Array<{
    resource: Record<string, unknown>;
    normalizedJson: string;
  }> = [];

  for (const resource of resources) {
    const name = extractResourceName(resource.id as string);
    if (excludeNames?.has(name)) continue;

    // Auto-generated IDs: key by normalized content
    if (isAutoGeneratedName(name)) {
      const normalized = normalizeResource(resource, normalizeContext);
      const normalizedJson = JSON.stringify(normalized);
      autoIdItems.push({ resource, normalizedJson });
    } else {
      map.set(name, resource);
    }
  }

  // Sort auto-ID items by normalized JSON and assign positional keys
  autoIdItems.sort((a, b) => a.normalizedJson.localeCompare(b.normalizedJson));
  autoIdItems.forEach((item, index) => {
    map.set(`{{auto-id-${index}}}`, item.resource);
  });

  return map;
}

/**
 * Safely lists resources, returning empty array on error
 */
async function safeListResources(
  client: IApimClient,
  resourceType: ResourceType,
  context: ApimServiceContext,
  parent?: ResourceDescriptor,
): Promise<Array<Record<string, unknown>>> {
  try {
    const resources: Array<Record<string, unknown>> = [];
    const iterable = client.listResources(context, resourceType, parent);
    for await (const resource of iterable) {
      resources.push(resource);
    }
    return resources;
  } catch (error) {
    logger.debug(
      `Failed to list ${resourceType}: ${error instanceof Error ? error.message : String(error)}`,
    );
    return [];
  }
}

/**
 * Extracts resource name from ARM resource ID
 */
function extractResourceName(resourceId: string): string {
  const parts = resourceId.split('/');
  return parts[parts.length - 1] || '';
}
