// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
/**
 * Publish orchestration service
 * Coordinates PUT/DELETE across dependency tiers in topological order
 * PUTs in dependency order (tier 1-4), DELETEs in reverse order (tier 4-1)
 */

import { IApimClient } from '../clients/iapim-client.js';
import { IArtifactStore } from '../clients/iartifact-store.js';
import { PublishConfig, OverrideConfig } from '../models/config.js';
import { ApimServiceContext, ResourceDescriptor } from '../models/types.js';
import { ResourceType } from '../models/resource-types.js';
import { getResourceTier } from '../lib/dependency-graph.js';
import { runParallel } from '../lib/parallel-runner.js';
import { logger } from '../lib/logger.js';
import { isAutoGeneratedId } from '../lib/auto-generated.js';
import { EXIT_SUCCESS, EXIT_PARTIAL, EXIT_FATAL } from '../lib/exit-codes.js';
import { buildResourceLabel } from '../lib/resource-uri.js';
import { getNamePart, isChildType, isTopLevelSingleton } from '../lib/resource-path.js';

// Import from other agents' files (will be created in parallel)
import { publishResource, ResourcePublishResult } from './resource-publisher.js';
import { publishApi } from './api-publisher.js';
import { publishProduct } from './product-publisher.js';
import { generateDryRunReport, DryRunReport } from './dry-run-reporter.js';
import { computeDeleteActions } from './delete-unmatched-service.js';
import { computeGitDiff } from './git-diff-service.js';
import { scanForRedactionMarkers } from './secret-redaction-guard.js';
import { hasNamedValueOverride } from './override-merger.js';
import { REDACTION_MARKER } from './secret-redactor.js';

/**
 * The APIM Backend properties.type value that identifies a pool backend.
 * Pool backends reference other Backend resources and must be published
 * after the individual backends they aggregate.
 */
const POOL_BACKEND_TYPE = 'pool';

export interface PublishActionResult {
  descriptor: ResourceDescriptor;
  action: 'put' | 'delete' | 'noop';
  status: 'success' | 'failed' | 'skipped';
  error?: Error;
}

export interface PublishResult {
  totalPuts: number;
  totalDeletes: number;
  totalErrors: number;
  totalSkipped: number;
  exitCode: number; // 0=success, 1=partial failure, 2=fatal
  actions: PublishActionResult[];
  dryRunReport?: DryRunReport;
}

interface PublishTargets {
  targetDescriptors: ResourceDescriptor[];
  deletedDescriptors: ResourceDescriptor[];
}

/**
 * Main publish orchestration function.
 * Coordinates PUT/DELETE operations across dependency tiers.
 */
export async function runPublish(
  client: IApimClient,
  store: IArtifactStore,
  config: PublishConfig
): Promise<PublishResult> {
  try {
    // Step 0: Pre-flight validation — ensure the resource group and APIM service exist
    await client.validatePreFlight(config.service);

    // Step 1: Determine target descriptors based on incremental mode
    const { targetDescriptors, deletedDescriptors } = await determinePublishTargets(
      store,
      config
    );

    logger.debug(
      `Publishing ${targetDescriptors.length} resources (dry-run: ${config.dryRun})`
    );

    // Step 1b: Redaction pre-flight gate.
    // Scan every artifact that would be published for leftover redaction markers
    // ('*** REDACTED ***'). A single leftover marker aborts the ENTIRE publish
    // before any PUT is issued — and also fails dry-run — so a service can never
    // be left partially published with placeholder secrets.
    const redactionFindings = await scanForRedactionMarkers(
      store,
      config,
      targetDescriptors
    );
    if (redactionFindings.length > 0) {
      logger.error(
        `Publish aborted: ${redactionFindings.length} artifact(s) still contain the redaction marker '${REDACTION_MARKER}'. ` +
        'Replace inline secrets with named values or KeyVault references before publishing: ' +
        'https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-properties'
      );
      const actions: PublishActionResult[] = redactionFindings.map((finding) => {
        logger.error(`  - ${finding.label} (${finding.location})`);
        return {
          descriptor: finding.descriptor,
          action: 'noop',
          status: 'failed',
          error: new Error(
            `${finding.label} contains '${REDACTION_MARKER}' in ${finding.location}`
          ),
        };
      });

      return {
        totalPuts: 0,
        totalDeletes: 0,
        totalErrors: actions.length,
        totalSkipped: 0,
        exitCode: EXIT_FATAL,
        actions,
      };
    }

    // Step 2: Handle dry-run mode
    if (config.dryRun) {
      const dryRunReport = await generateDryRunReport(
        store,
        client,
        config.service,
        config,
        targetDescriptors,
        deletedDescriptors
      );

      return {
        totalPuts: dryRunReport.summary.creates,
        totalDeletes: dryRunReport.summary.deletes,
        totalErrors: 0,
        totalSkipped: dryRunReport.summary.skips,
        exitCode: EXIT_SUCCESS,
        actions: [],
        dryRunReport,
      };
    }

    // Step 3: Execute PUTs in dependency order (tier 1 → tier 4)
    const putResults = await executePuts(
      client,
      store,
      config.service,
      config,
      targetDescriptors
    );

    // Step 4: Execute DELETEs in reverse dependency order (tier 4 → tier 1) if requested
    let deleteResults: PublishActionResult[] = [];
    if (deletedDescriptors.length > 0) {
      deleteResults = await executeDeletesForDescriptors(
        client,
        config.service,
        deletedDescriptors
      );
    } else if (config.deleteUnmatched) {
      deleteResults = await executeDeletes(
        client,
        store,
        config.service,
        config
      );
    }

    // Step 5: Combine results and determine exit code
    const allResults = [...putResults, ...deleteResults];
    const totalPuts = putResults.length;
    const totalDeletes = deleteResults.length;
    const totalErrors = allResults.filter((r) => r.status === 'failed').length;
    const totalSkipped = allResults.filter((r) => r.status === 'skipped').length;

    const exitCode = determineExitCode(allResults);

    return {
      totalPuts,
      totalDeletes,
      totalErrors,
      totalSkipped,
      exitCode,
      actions: allResults,
    };
  } catch (error) {
    logger.error('Fatal error during publish:', error);
    return {
      totalPuts: 0,
      totalDeletes: 0,
      totalErrors: 1,
      totalSkipped: 0,
      exitCode: EXIT_FATAL,
      actions: [],
    };
  }
}

/**
 * Determine which resources to publish based on incremental mode.
 */
async function determinePublishTargets(
  store: IArtifactStore,
  config: PublishConfig
): Promise<PublishTargets> {
  if (config.commitId) {
    // Incremental mode: use git diff
    logger.debug(
      `Using incremental publish mode with commit ID: ${config.commitId}`
    );
    const diffResult = await computeGitDiff(config.sourceDir, config.commitId);
    return {
      targetDescriptors: diffResult.changedDescriptors,
      deletedDescriptors: diffResult.deletedDescriptors,
    };
  } else {
    // Full mode: publish all artifacts
    logger.debug('Using full publish mode (all artifacts)');
    return {
      targetDescriptors: await store.listResources(config.sourceDir),
      deletedDescriptors: [],
    };
  }
}

/**
 * Execute PUT operations in dependency order (tier 1 → tier 4).
 */
async function executePuts(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  config: PublishConfig,
  targetDescriptors: ResourceDescriptor[]
): Promise<PublishActionResult[]> {
  const results: PublishActionResult[] = [];

  // Group descriptors by tier
  const tierGroups = new Map<number, ResourceDescriptor[]>();
  for (const descriptor of targetDescriptors) {
    const tier = getResourceTier(descriptor.type);
    if (!tierGroups.has(tier)) {
      tierGroups.set(tier, []);
    }
    tierGroups.get(tier)!.push(descriptor);
  }

  // Build a map of parent type → Set of parent names being published in tier 2.
  // Top-level types (not child types) handle their children internally,
  // so we exclude those children from tiers 3/4 to avoid double-publishing.
  const parentNamesByType = new Map<ResourceType, Set<string>>();
  for (const d of tierGroups.get(2) || []) {
    // Top-level singletons such as ServicePolicy do not participate in
    // parent-name child filtering.
    if (isTopLevelSingleton(d.type)) {
      continue;
    }

    // Top-level types are those that are NOT child types
    if (!isChildType(d.type)) {
      if (!parentNamesByType.has(d.type)) {
        parentNamesByType.set(d.type, new Set());
      }
      parentNamesByType.get(d.type)!.add(getNamePart(d.nameParts, 0));
    }
  }

  // Execute each tier in order (1, 2, 3, 4)
  for (const tier of [1, 2, 3, 4]) {
    const descriptors = tierGroups.get(tier) || [];
    if (descriptors.length === 0) continue;

    logger.debug(`Publishing tier ${tier}: ${descriptors.length} resources`);

    if (tier === 1) {
      const { workspaces, nonWorkspaceTier1 } = splitWorkspaces(descriptors);

      if (workspaces.length > 0) {
        logger.debug(`Publishing ${workspaces.length} workspace container(s) first (wave 0 of tier 1)`);
        await publishAndOutput(client, store, context, config, workspaces, results);
      }

      // Within Tier 1 we publish in three ordered waves to satisfy implicit
      // runtime dependencies:
      //
      // Wave 1 — NamedValues only.
      //   Loggers and backends may reference named values by name in their
      //   configuration (e.g. AppInsights instrumentation key stored as a
      //   named value). Publishing named values first ensures they exist
      //   before any resource that references them.
      //
      // Wave 2 — All remaining Tier 1 resources except pool backends.
      //   Loggers, tags, gateways, etc. can now reference named values safely.
      //
      // Wave 3 — Pool backends.
      //   Pool backends reference individual Backend resources and must be
      //   published after the backends they aggregate (see pool backend
      //   ordering comments in splitPoolBackends).
      const { namedValues, otherTier1 } = splitNamedValues(nonWorkspaceTier1, config.overrides);

      if (namedValues.length > 0) {
        logger.debug(`Publishing ${namedValues.length} named value(s) first (wave 1 of tier 1)`);
        await publishAndOutput(client, store, context, config, namedValues, results);
      }

      const { poolBackends, regularTier1 } = await splitPoolBackends(
        store,
        config.sourceDir,
        otherTier1
      );
      await publishAndOutput(client, store, context, config, regularTier1, results);
      if (poolBackends.length > 0) {
        logger.debug(
          `Publishing ${poolBackends.length} pool backend(s) after regular backends`
        );
        await publishAndOutput(
          client,
          store,
          context,
          config,
          poolBackends,
          results
        );
      }
    } else if (tier === 2) {
      const tier2Descriptors = filterApiRevisionsHandledByRootApis(descriptors);

      const { mcpApis, regularTier2 } = await splitMcpApis(
        store,
        config.sourceDir,
        tier2Descriptors
      );

      await publishAndOutput(client, store, context, config, regularTier2, results);

      if (mcpApis.length > 0) {
        logger.debug(`Publishing ${mcpApis.length} MCP API resource(s) after regular tier 2 resources`);
        await publishAndOutput(client, store, context, config, mcpApis, results);
      }
    } else {
      // For tiers 3/4, exclude child resources whose parent is being published
      // in tier 2 (publishApi/publishProduct handle their children internally).
      // Use getParentType() to dynamically determine parent-child relationships.
      let tierDescriptors = descriptors;

      if (parentNamesByType.size > 0) {
        const countBefore = tierDescriptors.length;
        tierDescriptors = tierDescriptors.filter((d) => {
          // Top-level types have no parent to check
          if (!isChildType(d.type)) return true;

          // Child resources have the parent name as nameParts[0]
          const owningParent = getNamePart(d.nameParts, 0);

          // Skip if this parent name is being published in tier 2
          for (const parentNames of parentNamesByType.values()) {
            if (parentNames.has(owningParent)) return false;
          }
          return true;
        });
        const skipped = countBefore - tierDescriptors.length;
        if (skipped > 0) {
          logger.debug(`Skipping ${skipped} child resource(s) in tier ${tier} (handled by parent publisher)`);
        }
      }

      await publishAndOutput(client, store, context, config, tierDescriptors, results);
    }
  }

  return results;
}

function splitWorkspaces(
  descriptors: ResourceDescriptor[]
): { workspaces: ResourceDescriptor[]; nonWorkspaceTier1: ResourceDescriptor[] } {
  const workspaces: ResourceDescriptor[] = [];
  const nonWorkspaceTier1: ResourceDescriptor[] = [];

  for (const descriptor of descriptors) {
    if (descriptor.type === ResourceType.Workspace) {
      workspaces.push(descriptor);
    } else {
      nonWorkspaceTier1.push(descriptor);
    }
  }

  return { workspaces, nonWorkspaceTier1 };
}

/**
 * Publish a batch of descriptors and write their status lines to stdout/stderr.
 */
async function publishAndOutput(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  config: PublishConfig,
  descriptors: ResourceDescriptor[],
  results: PublishActionResult[]
): Promise<void> {
  if (descriptors.length === 0) return;
  const tierResults = await publishTier(client, store, context, config, descriptors);
  results.push(...tierResults);
  for (const result of tierResults) {
    outputActionStatus(result);
  }
}

/**
 * Separates NamedValue descriptors from all other descriptors in the supplied list.
 *
 * NamedValues must be published before loggers, backends, and other Tier 1
 * resources that may reference them by name in their configuration (e.g. a
 * Logger that stores its instrumentation key as a named value).
 *
 * Auto-generated NamedValues (24-char hex IDs like Logger credentials) are
 * filtered out because APIM recreates them when the referencing Logger is
 * published. Publishing them would create orphan duplicates.
 *
 * However, if the user has provided an explicit override for an auto-generated
 * named value, it is published normally. This supports publishing to fresh
 * environments where APIM cannot recreate the named value automatically.
 */
function splitNamedValues(
  descriptors: ResourceDescriptor[],
  overrides?: OverrideConfig
): { namedValues: ResourceDescriptor[]; otherTier1: ResourceDescriptor[] } {
  const namedValues: ResourceDescriptor[] = [];
  const otherTier1: ResourceDescriptor[] = [];

  for (const descriptor of descriptors) {
    if (descriptor.type === ResourceType.NamedValue) {
      const name = getNamePart(descriptor.nameParts, 0);
      if (isAutoGeneratedId(name) && !hasNamedValueOverride(name, overrides)) {
        logger.debug(`Skipping auto-generated named value: ${name}`);
        continue;
      }
      namedValues.push(descriptor);
    } else {
      otherTier1.push(descriptor);
    }
  }

  return { namedValues, otherTier1 };
}

/**
 * Separates Backend descriptors that are pool backends (properties.type === "Pool")
 * from all other descriptors in the supplied list.
 *
 * Pool backends reference individual Backend resources and must therefore be
 * published *after* those backends are created. Reading the artifact JSON is
 * the only reliable way to detect pool backends at publish time because the
 * ResourceType enum treats all backends as the same type.
 */
async function splitPoolBackends(
  store: IArtifactStore,
  sourceDir: string,
  descriptors: ResourceDescriptor[]
): Promise<{ poolBackends: ResourceDescriptor[]; regularTier1: ResourceDescriptor[] }> {
  const poolBackends: ResourceDescriptor[] = [];
  const regularTier1: ResourceDescriptor[] = [];

  for (const descriptor of descriptors) {
    if (descriptor.type === ResourceType.Backend) {
      const json = await store.readResource(sourceDir, descriptor);
      const props = json?.properties as Record<string, unknown> | undefined;
      const backendType = props?.type;
      if (typeof backendType === 'string' && backendType.toLowerCase() === POOL_BACKEND_TYPE) {
        poolBackends.push(descriptor);
        continue;
      }
    }
    regularTier1.push(descriptor);
  }

  return { poolBackends, regularTier1 };
}

async function splitMcpApis(
  store: IArtifactStore,
  sourceDir: string,
  descriptors: ResourceDescriptor[]
): Promise<{ mcpApis: ResourceDescriptor[]; regularTier2: ResourceDescriptor[] }> {
  const mcpApis: ResourceDescriptor[] = [];
  const regularTier2: ResourceDescriptor[] = [];

  for (const descriptor of descriptors) {
    if (descriptor.type === ResourceType.Api) {
      const json = await store.readResource(sourceDir, descriptor);
      const props = json?.properties as Record<string, unknown> | undefined;
      const mcpTools = props?.mcpTools;
      if (Array.isArray(mcpTools) && mcpTools.length > 0) {
        mcpApis.push(descriptor);
        continue;
      }
    }

    regularTier2.push(descriptor);
  }

  return { mcpApis, regularTier2 };
}

/**
 * Publish a single tier of resources in parallel.
 */
async function publishTier(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  config: PublishConfig,
  descriptors: ResourceDescriptor[]
): Promise<PublishActionResult[]> {
  const tasks = descriptors.map((descriptor) => async () => {
    try {
      let publishResult: ResourcePublishResult;
      const apiName = descriptor.type === ResourceType.Api
        ? getNamePart(descriptor.nameParts, 0)
        : undefined;
      const isApiRevision = typeof apiName === 'string' && isApiRevisionName(apiName);

      // Use specialized publishers for Api and Product types
      if (descriptor.type === ResourceType.Api && !isApiRevision) {
        publishResult = await publishApi(client, store, context, descriptor, config);
      } else if (descriptor.type === ResourceType.Product) {
        publishResult = await publishProduct(client, store, context, descriptor, config);
      } else {
        publishResult = await publishResource(
          client,
          store,
          context,
          descriptor,
          config
        );
      }

      return convertToActionResult(publishResult);
    } catch (error) {
      logger.error(
        `Failed to publish ${buildResourceLabel(descriptor)}:`,
        error
      );
      return {
        descriptor,
        action: 'put' as const,
        status: 'failed' as const,
        error: error instanceof Error ? error : new Error(String(error)),
      };
    }
  });

  const taskResults = await runParallel(tasks, 5);

  return taskResults.map((tr, index) => {
    if (tr.status === 'fulfilled' && tr.value) {
      return tr.value;
    } else {
      // Should not happen given error handling above, but be defensive
      const descriptor = descriptors[index];
      if (!descriptor) {
        throw new Error('No descriptor found for failed task');
      }
      return {
        descriptor,
        action: 'put' as const,
        status: 'failed' as const,
        error: tr.reason || new Error('Unknown error'),
      };
    }
  });
}

function filterApiRevisionsHandledByRootApis(
  descriptors: ResourceDescriptor[]
): ResourceDescriptor[] {
  const rootApiNames = new Set<string>();
  for (const descriptor of descriptors) {
    if (descriptor.type !== ResourceType.Api) {
      continue;
    }

    const apiName = getNamePart(descriptor.nameParts, 0);
    if (!isApiRevisionName(apiName)) {
      rootApiNames.add(apiName);
    }
  }

  if (rootApiNames.size === 0) {
    return descriptors;
  }

  return descriptors.filter((descriptor) => {
    if (descriptor.type !== ResourceType.Api) {
      return true;
    }

    const apiName = getNamePart(descriptor.nameParts, 0);
    if (!isApiRevisionName(apiName)) {
      return true;
    }

    return !rootApiNames.has(getApiRootName(apiName));
  });
}

function isApiRevisionName(apiName: string): boolean {
  return apiName.includes(';rev=');
}

function getApiRootName(apiName: string): string {
  return apiName.split(';rev=')[0] ?? apiName;
}

/**
 * Execute DELETE operations in reverse dependency order (tier 4 → tier 1).
 */
async function executeDeletes(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  config: PublishConfig
): Promise<PublishActionResult[]> {
  const deleteDescriptors = await computeDeleteActions(
    client,
    store,
    context,
    config
  );

  if (deleteDescriptors.length === 0) {
    logger.debug('No resources to delete');
    return [];
  }

  logger.debug(`Deleting ${deleteDescriptors.length} unmatched resources`);

  return executeDeletesForDescriptors(client, context, deleteDescriptors);
}

/**
 * Execute DELETE operations for a precomputed descriptor list in reverse dependency order.
 */
async function executeDeletesForDescriptors(
  client: IApimClient,
  context: ApimServiceContext,
  deleteDescriptors: ResourceDescriptor[]
): Promise<PublishActionResult[]> {
  if (deleteDescriptors.length === 0) {
    logger.debug('No resources to delete');
    return [];
  }

  const results: PublishActionResult[] = [];

  // Group by tier
  const tierGroups = new Map<number, ResourceDescriptor[]>();
  for (const descriptor of deleteDescriptors) {
    const tier = getResourceTier(descriptor.type);
    if (!tierGroups.has(tier)) {
      tierGroups.set(tier, []);
    }
    tierGroups.get(tier)!.push(descriptor);
  }

  // Execute in REVERSE tier order (4, 3, 2, 1)
  for (const tier of [4, 3, 2, 1]) {
    const descriptors = tierGroups.get(tier) || [];
    if (descriptors.length === 0) continue;

    logger.debug(`Deleting tier ${tier}: ${descriptors.length} resources`);

    const tierResults = await deleteTier(client, context, descriptors);

    results.push(...tierResults);

    // Output per-resource status lines
    for (const result of tierResults) {
      outputActionStatus(result);
    }
  }

  return results;
}

/**
 * Delete a single tier of resources in parallel.
 */
async function deleteTier(
  client: IApimClient,
  context: ApimServiceContext,
  descriptors: ResourceDescriptor[]
): Promise<PublishActionResult[]> {
  const tasks = descriptors.map((descriptor) => async () => {
    try {
      const deleted = await client.deleteResource(context, descriptor);

      return {
        descriptor,
        action: 'delete' as const,
        status: deleted ? ('success' as const) : ('skipped' as const),
      };
    } catch (error) {
      logger.error(
        `Failed to delete ${buildResourceLabel(descriptor)}:`,
        error
      );
      return {
        descriptor,
        action: 'delete' as const,
        status: 'failed' as const,
        error: error instanceof Error ? error : new Error(String(error)),
      };
    }
  });

  const taskResults = await runParallel(tasks, 5);

  return taskResults.map((tr, index) => {
    if (tr.status === 'fulfilled' && tr.value) {
      return tr.value;
    } else {
      const descriptor = descriptors[index];
      if (!descriptor) {
        throw new Error('No descriptor found for failed task');
      }
      return {
        descriptor,
        action: 'delete' as const,
        status: 'failed' as const,
        error: tr.reason || new Error('Unknown error'),
      };
    }
  });
}

/**
 * Convert ResourcePublishResult to PublishActionResult.
 */
function convertToActionResult(
  result: ResourcePublishResult
): PublishActionResult {
  return {
    descriptor: result.descriptor,
    action: result.action,
    status: result.status,
    error: result.error,
  };
}

/**
 * Output per-resource status line to stdout.
 */
function outputActionStatus(result: PublishActionResult): void {
  const verb = result.action.toUpperCase();
  const path = buildResourcePath(result.descriptor);

  if (result.status === 'success') {
    process.stdout.write(`${verb} ${path}\n`);
  } else if (result.status === 'skipped') {
    process.stdout.write(`SKIP ${path}\n`);
  } else if (result.status === 'failed') {
    process.stderr.write(`ERROR ${verb} ${path}: ${result.error?.message}\n`);
  }
}

/**
 * Build a human-readable path for a resource descriptor.
 */
function buildResourcePath(descriptor: ResourceDescriptor): string {
  const parts: string[] = [descriptor.type.toLowerCase()];

  if (descriptor.workspace) {
    parts.push(`workspace:${descriptor.workspace}`);
  }

  parts.push(...descriptor.nameParts);

  return parts.join('/');
}

/**
 * Determine exit code based on results.
 * Uses standardised constants from exit-codes module.
 */
function determineExitCode(results: PublishActionResult[]): number {
  if (results.length === 0) {
    return EXIT_SUCCESS;
  }

  const successCount = results.filter((r) => r.status === 'success').length;
  const failedCount = results.filter((r) => r.status === 'failed').length;

  if (failedCount === 0) {
    return EXIT_SUCCESS;
  }

  if (successCount > 0) {
    return EXIT_PARTIAL;
  }

  return EXIT_FATAL;
}
