// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
/**
 * Generic resource publisher
 * Read resource from IArtifactStore, apply overrides, PUT via IApimClient.
 * Handles all 33 resource types using ResourceType metadata.
 * MUST preserve opaque JSON per FR-009.
 */

import type { IApimClient } from '../clients/iapim-client.js';
import type { IArtifactStore } from '../clients/iartifact-store.js';
import type {
  ApimServiceContext,
  AssociationEntry,
  ResourceDescriptor,
} from '../models/types.js';
import type { PublishConfig } from '../models/config.js';
import { ResourceType, RESOURCE_TYPE_METADATA, MANAGED_GATEWAY_NAME } from '../models/resource-types.js';
import { applyOverrides } from './override-merger.js';
import { checkKeyVaultSecretAccess } from './keyvault-checker.js';
import {
  getNamePart,
  getResourceDescriptorKey,
  sameResourceDescriptor,
} from '../lib/resource-path.js';
import { isAutoGeneratedId } from '../lib/auto-generated.js';
import { isWorkspaceScope, buildLinkPayload } from '../lib/workspace-link.js';
import { logger } from '../lib/logger.js';
import { REDACTION_MARKER } from './secret-redactor.js';
import { isAssociationReferenceNotFoundError, isLinkAlreadyExistsError } from '../clients/apim-client.js';
import type { OverrideConfig, OverrideSection } from '../models/config.js';
import { buildResourceLabel } from '../lib/resource-uri.js';
import { hasExplicitTypeFilter, resolveWorkspaceFilter, shouldIncludeResource } from './filter-service.js';
import { findSubscriptionTargets } from './transitive-resolver.js';
import { mapDescriptor, toDeployedName } from './env-mapper.js';
import type { EnvMapping } from './env-mapper.js';
import { rewritePolicyRefs } from './policy-ref-rewriter.js';
import type { KnownArtifactSets } from '../models/config.js';

export type { KnownArtifactSets } from '../models/config.js';

export interface ResourcePublishResult {
  descriptor: ResourceDescriptor;
  status: 'success' | 'failed' | 'skipped';
  action: 'put' | 'patch' | 'delete' | 'noop';
  error?: Error;
  relatedResults?: ResourcePublishResult[];
  suppressPrimaryResult?: boolean;
}

export interface PublishEligibility {
  eligible: boolean;
  reason?: string;
}

export interface AssociationPublicationPlan extends PublishEligibility {
  descriptor: ResourceDescriptor;
  deployedDescriptor: ResourceDescriptor;
  target: ResourceDescriptor;
  payload: Record<string, unknown>;
}

/**
 * Build the known artifact name sets from a list of descriptors.
 * Called once per publish run after determinePublishTargets.
 */
export function buildKnownArtifactSets(descriptors: ResourceDescriptor[]): KnownArtifactSets {
  const namedValues = new Set<string>();
  const fragments = new Set<string>();
  const backends = new Set<string>();
  for (const d of descriptors) {
    if (d.nameParts.length > 0) {
      const name = d.nameParts[0];
      if (d.type === ResourceType.NamedValue) namedValues.add(name);
      else if (d.type === ResourceType.PolicyFragment) fragments.add(name);
      else if (d.type === ResourceType.Backend) backends.add(name);
    }
  }
  return { namedValues, fragments, backends };
}

/**
 * Check if a specific property has an explicit override in the given section.
 * Uses case-insensitive resource name matching (matching override-merger behavior).
 */
export function hasExplicitPropertyOverride(
  resourceName: string,
  propertyKey: string,
  section: OverrideSection | undefined,
): boolean {
  return getExplicitPropertyOverride(resourceName, propertyKey, section) !== undefined;
}

/** Return the explicit override value for a property, if any (case-insensitive name match). */
function getExplicitPropertyOverride(
  resourceName: string,
  propertyKey: string,
  section: OverrideSection | undefined,
): unknown {
  if (!section) return undefined;
  const lowerName = resourceName.toLowerCase();
  const matchingKey = Object.keys(section).find((k) => k.toLowerCase() === lowerName);
  if (!matchingKey) return undefined;
  const properties = section[matchingKey]?.properties as Record<string, unknown> | undefined;
  if (!properties || !Object.hasOwn(properties, propertyKey)) return undefined;
  return properties[propertyKey];
}

/**
 * True when the environment override explicitly supplies the LEGACY auth
 * representation (oAuth2/openid) without also supplying the collections.
 * Collection or metadata-only overrides keep the default collection precedence.
 */
export function prefersLegacyAuthOverride(
  resourceName: string,
  section: OverrideSection | undefined,
): boolean {
  const overrideAuth = getExplicitPropertyOverride(resourceName, 'authenticationSettings', section);
  if (!overrideAuth || typeof overrideAuth !== 'object') return false;
  const auth = overrideAuth as Record<string, unknown>;

  const suppliesLegacy = auth.oAuth2 != null || auth.openid != null;
  const suppliesCollections =
    (Array.isArray(auth.oAuth2AuthenticationSettings) && auth.oAuth2AuthenticationSettings.length > 0) ||
    (Array.isArray(auth.openidAuthenticationSettings) && auth.openidAuthenticationSettings.length > 0);

  return suppliesLegacy && !suppliesCollections;
}

/**
 * Policy resource types that have external XML content
 */
export const POLICY_TYPES = new Set<ResourceType>([
  ResourceType.ServicePolicy,
  ResourceType.ProductPolicy,
  ResourceType.ApiPolicy,
  ResourceType.ApiOperationPolicy,
  ResourceType.GraphQLResolverPolicy,
]);

/**
 * Association resource types that read from association files
 */
const ASSOCIATION_TYPES = new Map<ResourceType, 'apis' | 'groups'>([
  [ResourceType.ProductApi, 'apis'],
  [ResourceType.ProductGroup, 'groups'],
  [ResourceType.GatewayApi, 'apis'],
]);

/**
 * Maps association resource types to their parent resource types.
 * readAssociation / buildAssociationFilePath expect a Product or Gateway
 * descriptor, not the association child type itself.
 */
const ASSOCIATION_PARENT_TYPES = new Map<ResourceType, ResourceType>([
  [ResourceType.ProductApi, ResourceType.Product],
  [ResourceType.ProductGroup, ResourceType.Product],
  [ResourceType.GatewayApi, ResourceType.Gateway],
]);

/**
 * Wiki resource types that read markdown content
 */
const WIKI_TYPES = new Set<ResourceType>([
  ResourceType.ApiWiki,
  ResourceType.ProductWiki,
]);

/**
 * Normalize API authenticationSettings for PUT.
 *
 * APIM's GET returns both the legacy singular fields (oAuth2, openid) and the
 * newer collections (oAuth2AuthenticationSettings, openidAuthenticationSettings),
 * but PUT rejects payloads containing both: "Cannot use OAuth2AuthenticationSettings
 * in combination with OAuth2 nor openid". Keep the collections (a superset of the
 * singular fields) when they are non-empty; otherwise keep the singular fields and
 * drop the empty collection keys.
 *
 * When `preferLegacyFields` is set (the environment override explicitly provides
 * authenticationSettings), non-null legacy fields win over extracted collections —
 * otherwise the override would be silently discarded.
 */
export function normalizeApiAuthenticationSettings(
  json: Record<string, unknown>,
  options?: { preferLegacyFields?: boolean }
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  const auth = props?.authenticationSettings as Record<string, unknown> | undefined;
  if (!auth) {
    return json;
  }

  const {
    oAuth2,
    openid,
    oAuth2AuthenticationSettings,
    openidAuthenticationSettings,
    ...rest
  } = auth;

  const hasLegacyValues = oAuth2 != null || openid != null;
  const hasCollections =
    (Array.isArray(oAuth2AuthenticationSettings) && oAuth2AuthenticationSettings.length > 0) ||
    (Array.isArray(openidAuthenticationSettings) && openidAuthenticationSettings.length > 0);

  const normalizedAuth: Record<string, unknown> = { ...rest };
  if (hasCollections && !(options?.preferLegacyFields && hasLegacyValues)) {
    if (Array.isArray(oAuth2AuthenticationSettings) && oAuth2AuthenticationSettings.length > 0) {
      normalizedAuth.oAuth2AuthenticationSettings = oAuth2AuthenticationSettings;
    }
    if (Array.isArray(openidAuthenticationSettings) && openidAuthenticationSettings.length > 0) {
      normalizedAuth.openidAuthenticationSettings = openidAuthenticationSettings;
    }
  } else {
    if (oAuth2 !== undefined) normalizedAuth.oAuth2 = oAuth2;
    if (openid !== undefined) normalizedAuth.openid = openid;
  }

  return { ...json, properties: { ...props, authenticationSettings: normalizedAuth } };
}

/**
 * Publish a single resource: read from store, apply overrides, PUT to APIM.
 * Preserves opaque JSON (FR-009). Uses applyOverrides for env-specific values.
 * Returns 'skipped' if resource file doesn't exist in store.
 */
export async function publishResource(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  allowedDescriptors?: ResourceDescriptor[]
): Promise<ResourcePublishResult> {
  let attemptedPut = false;
  try {
    // The built-in "managed" gateway cannot be created/updated as a resource;
    // only its API assignments are manageable. Skip any managed Gateway resource
    // PUT (its GatewayApi associations are still published via the branch below).
    if (descriptor.type === ResourceType.Gateway && getNamePart(descriptor.nameParts, 0) === MANAGED_GATEWAY_NAME) {
      return { descriptor, status: 'skipped', action: 'noop' };
    }

    // Handle association types (ProductApi, ProductGroup, GatewayApi)
    const associationType = ASSOCIATION_TYPES.get(descriptor.type);
    if (associationType) {
      return await publishAssociation(
        client,
        store,
        context,
        descriptor,
        config,
        associationType,
        allowedDescriptors
      );
    }

    if (descriptor.type === ResourceType.ApiTag) {
      const eligibility = await evaluateResourceEligibility(
        store,
        descriptor,
        config
      );
      if (!eligibility.eligible) {
        logger.warn(
          `Skipping ApiTag association "${descriptor.nameParts.join('/')}": ${eligibility.reason}`
        );
        return {
          descriptor,
          status: 'skipped',
          action: 'noop',
        };
      }
    }

    // Handle workspace ApiTag — uses link endpoint with link payload.
    // In service scope, ApiTag is a regular PUT with the tag JSON; in workspace
    // scope it becomes a link resource at `tags/{tag}/apiLinks/{api}`.
    if (descriptor.type === ResourceType.ApiTag && (descriptor.workspace || isWorkspaceScope(context))) {
      return await publishWorkspaceApiTagLink(client, context, descriptor, config);
    }

    // Handle wiki types
    if (WIKI_TYPES.has(descriptor.type)) {
      return await publishWiki(client, store, context, descriptor, config);
    }

    // Handle policy types — artifact is policy.xml (raw XML), not a JSON info file
    if (POLICY_TYPES.has(descriptor.type)) {
      return await publishPolicy(client, store, context, descriptor, config);
    }

    // Read resource JSON from store
    let json = await store.readResource(config.sourceDir, descriptor);
    if (!json) {
      return {
        descriptor,
        status: 'skipped',
        action: 'noop',
      };
    }

    // Rewrite MCP tool operationIds against the target service before overrides
    // so explicit override values win unchanged.
    if (descriptor.type === ResourceType.Api) {
      json = normalizeMcpToolOperationIds(json, context, config.envMapping);
    }

    // Apply overrides (deep merge, preserves opaque structure)
    json = applyOverrides(descriptor, json, config.overrides);

    // For Logger resources, rewrite named value references in credentials.
    // APIM resolves {{ref}} by displayName, not resource name. Old extracts
    // stored {{name}}; rewrite to {{displayName}} for APIM compatibility.
    if (descriptor.type === ResourceType.Logger) {
      json = await rewriteNamedValueReferences(json, store, config.sourceDir, descriptor, config.overrides, config.envMapping);
    }

    // API operations: enforce explicit empty strings for text fields when omitted.
    // APIM may synthesize description from displayName when description is absent,
    // causing extract/publish round-trip drift.
    if (descriptor.type === ResourceType.ApiOperation) {
      json = normalizeApiOperationTextFields(json);
    }

    // For KeyVault-backed NamedValues:
    //   1. Strip properties.value — APIM must not receive both keyVault and value
    //      in the same PUT body, as it causes indefinite provisioning or rejection.
    //   2. Pre-flight access check — verify the managed identity has GET access
    //      to the secret before attempting the PUT. Surfaces permission errors
    //      early and fails fast instead of polling until timeout.
    if (descriptor.type === ResourceType.NamedValue) {
      // Affix displayName when envMapping applies and user hasn't set an explicit override.
      // APIM resolves {{ref}} tokens by displayName, so the deployed displayName must
      // match the affixed name used elsewhere (descriptor name, policy refs, etc.).
      if (config.envMapping?.appliesTo.has(ResourceType.NamedValue) === true) {
        const canonicalName = getNamePart(descriptor.nameParts, 0);
        const hasDisplayNameOverride = hasExplicitPropertyOverride(
          canonicalName,
          'displayName',
          config.overrides?.namedValues,
        );
        if (!hasDisplayNameOverride) {
          const props = json.properties as Record<string, unknown> | undefined;
          const currentDisplayName =
            typeof props?.displayName === 'string' ? props.displayName : canonicalName;
          const deployedDisplayName = toDeployedName(
            currentDisplayName,
            ResourceType.NamedValue,
            config.envMapping,
          );
          json = {
            ...json,
            properties: { ...(props ?? {}), displayName: deployedDisplayName },
          };
        }
      }

      const props = json.properties as Record<string, unknown> | undefined;
      const kvBlock = props?.keyVault as Record<string, unknown> | undefined;
      if (kvBlock != null) {
        const { value: _omit, ...propsWithoutValue } = props!;
        json = { ...json, properties: propsWithoutValue };

        const secretIdentifier = kvBlock.secretIdentifier as string | undefined;
        const identityClientId = kvBlock.identityClientId as string | undefined;
        if (secretIdentifier) {
          await checkKeyVaultSecretAccess(secretIdentifier, identityClientId, {
            subscriptionId: context.subscriptionId,
            resourceGroup: context.resourceGroup,
            serviceName: context.serviceName,
          });
        }
      }

      // Guard: reject secret named values that still contain the redaction
      // marker after overrides. This prevents publishing placeholder secrets
      // (e.g., auto-generated named values where the override didn't provide
      // a real value or keyVault reference). Check the current json since
      // KeyVault-backed values have already had 'value' stripped above.
      const currentProps = json.properties as Record<string, unknown> | undefined;
      if (currentProps?.secret === true) {
        const currentValue = currentProps.value as string | undefined;
        if (currentValue === REDACTION_MARKER) {
          logger.warn(
            `Skipping named value '${getNamePart(descriptor.nameParts, 0)}': ` +
            `secret value is still redacted. Provide a 'value' or 'keyVault' override.`
          );
          return {
            descriptor,
            status: 'skipped',
            action: 'noop',
          };
        }
      }
    }

    // Normalize Subscription scope.
    // APIM stores scope as a full ARM resource path (e.g.
    // "/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.ApiManagement/service/{svc}/apis")
    // but the PUT endpoint requires a relative APIM path (e.g. "/apis" or
    // "/apis/{apiId}" or "/products/{productId}").  Strip the service base path
    // prefix when it is present so that the publish round-trip works correctly.
    // HOWEVER: Skip publishing subscriptions with root-level scope (e.g. the built-in
    // "master" subscription), as APIM treats these as read-only system resources
    // and returns ValidationError when attempting to update them.
    if (descriptor.type === ResourceType.Subscription) {
      const subscriptionName = getNamePart(descriptor.nameParts, 0);
      const eligibility = await evaluateResourceEligibility(
        store,
        descriptor,
        config,
        json
      );
      if (!eligibility.eligible) {
        logger.warn(
          `Skipping subscription "${subscriptionName}": ${eligibility.reason}`
        );
        return {
          descriptor,
          status: 'skipped',
          action: 'noop',
        };
      }

      json = normalizeSubscriptionScope(
        json,
        context,
        descriptor.workspace,
        config.envMapping
      );
    }

    // ApiRelease: normalize properties.apiId from source ARM path to target ARM path.
    // APIM stores apiId as the full source ARM resource path, e.g.:
    //   /subscriptions/{src-sub}/resourceGroups/{src-rg}/providers/
    //   Microsoft.ApiManagement/service/{src-svc}/apis/my-api;rev=2
    // The PUT to the target service must reference the target service path,
    // otherwise APIM rejects the request with a validation error.
    if (descriptor.type === ResourceType.ApiRelease) {
      json = normalizeApiReleaseApiId(json, context, config.envMapping);
    }

    if (descriptor.type === ResourceType.Api) {
      json = normalizeApiVersionSetId(
        json,
        context,
        descriptor.workspace,
        config.envMapping
      );
    }

    if (descriptor.type === ResourceType.Backend) {
      json = normalizeBackendPoolServices(json, context, config.envMapping);
    }

    // API Revisions (e.g., "my-api;rev=2") need sourceApiId so APIM knows which
    // base API to copy structure from. Also strip null properties that cause
    // validation errors in APIM's revision creation.
    if (descriptor.type === ResourceType.Api) {
      const apiName = getNamePart(descriptor.nameParts, 0);
      json = normalizeApiAuthenticationSettings(json, {
        preferLegacyFields: prefersLegacyAuthOverride(apiName, config.overrides?.apis),
      });
      if (apiName.includes(';rev=')) {
        const baseApiName = apiName.split(';rev=')[0];
        const props = json.properties as Record<string, unknown> | undefined;
        const cleanProps: Record<string, unknown> = {};
        for (const [key, val] of Object.entries(props ?? {})) {
          if (val !== null) cleanProps[key] = val;
        }
        const deployedBaseApiName = config.envMapping
          ? toDeployedName(baseApiName, ResourceType.Api, config.envMapping)
          : baseApiName;
        cleanProps.sourceApiId = `/subscriptions/${context.subscriptionId}/resourceGroups/${context.resourceGroup}/providers/Microsoft.ApiManagement/service/${context.serviceName}/apis/${deployedBaseApiName}`;
        // Preserve source current-revision intent. APIM can implicitly promote a
        // created revision to current if isCurrent is omitted; default to false
        // unless the extracted artifact explicitly set it.
        if (!Object.hasOwn(cleanProps, 'isCurrent')) {
          cleanProps.isCurrent = false;
        }
        // Revision creation copies apiRevisionDescription from the current
        // revision via sourceApiId; send an explicit empty string when absent so
        // the copy cannot inherit it. (properties.description must NOT be sent —
        // APIM rejects changing Description for non-current revisions.)
        if (!Object.hasOwn(cleanProps, 'apiRevisionDescription')) {
          cleanProps.apiRevisionDescription = '';
        }
        if (
          Object.hasOwn(cleanProps, 'description') &&
          hasExplicitPropertyOverride(apiName, 'description', config.overrides?.apis)
        ) {
          logger.warn(
            `Ignoring 'description' override for revision '${apiName}': ` +
            `APIM only accepts description changes on the current revision.`
          );
        }
        delete cleanProps.description;
        json = { ...json, properties: cleanProps };
      }
    }

    json = applyApiPathPrefix(json, descriptor, config);

    // For PolicyFragment: rewrite cross-resource refs in properties.value (policy XML)
    if (descriptor.type === ResourceType.PolicyFragment && config.envMapping && config.knownArtifactSets) {
      const props = json.properties as Record<string, unknown> | undefined;
      if (typeof props?.value === 'string') {
        const rewrittenXml = rewritePolicyRefs(props.value, config.envMapping, config.knownArtifactSets);
        json = { ...json, properties: { ...props, value: rewrittenXml } };
      }
    }

    // Apply env-mapping: affix descriptor name segments before PUT
    const deployedDescriptor = config.envMapping
      ? mapDescriptor(descriptor, config.envMapping)
      : descriptor;

    // PUT to APIM
    attemptedPut = true;
    await client.putResource(context, deployedDescriptor, json);

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: attemptedPut ? 'put' : 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Publish association resource (ProductApi, ProductGroup, GatewayApi)
 */
async function publishAssociation(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  associationType: 'apis' | 'groups',
  allowedDescriptors?: ResourceDescriptor[]
): Promise<ResourcePublishResult> {
  try {
    const plans = await planAssociationPublications(
      store,
      context,
      descriptor,
      config,
      associationType,
      allowedDescriptors
    );

    const relatedResults: ResourcePublishResult[] = [];
    for (const plan of plans) {
      if (!plan.eligible) {
        logger.warn(
          `Skipping ${descriptor.type} association "${plan.descriptor.nameParts.join('/')}": ${plan.reason}`
        );
        relatedResults.push({
          descriptor: plan.descriptor,
          status: 'skipped',
          action: 'noop',
        });
        continue;
      }
      try {
        await client.putResource(context, plan.deployedDescriptor, plan.payload);
        relatedResults.push({
          descriptor: plan.descriptor,
          status: 'success',
          action: 'put',
        });
      } catch (error) {
        // 409 means the link already exists — desired state is in place.
        if (isLinkAlreadyExistsError(error)) {
          relatedResults.push({
            descriptor: plan.descriptor,
            status: 'success',
            action: 'put',
          });
          continue;
        }
        // The referenced API/group is absent on the target (filtered out or
        // failed to publish). Skip this single link with a warning instead of
        // aborting the whole association, so other present entries still link.
        if (isAssociationReferenceNotFoundError(error)) {
          logger.warn(
            `Skipping ${associationType} association '${getNamePart(plan.descriptor.nameParts, 1)}' on ` +
            `'${getNamePart(descriptor.nameParts, 0)}': referenced resource not found on target`
          );
          relatedResults.push({
            descriptor: plan.descriptor,
            status: 'skipped',
            action: 'noop',
          });
          continue;
        }
        relatedResults.push({
          descriptor: plan.descriptor,
          status: 'failed',
          action: 'put',
          error: error instanceof Error ? error : new Error(String(error)),
        });
        break;
      }
    }

    const failedResult = relatedResults.find((result) => result.status === 'failed');
    return {
      descriptor,
      status: failedResult ? 'failed' : 'success',
      action: 'noop',
      error: failedResult?.error,
      relatedResults,
      suppressPrimaryResult: true,
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

export async function planAssociationPublications(
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  associationType?: 'apis' | 'groups',
  allowedDescriptors?: ResourceDescriptor[]
): Promise<AssociationPublicationPlan[]> {
  const resolvedAssociationType = associationType ?? ASSOCIATION_TYPES.get(descriptor.type);
  const parentType = ASSOCIATION_PARENT_TYPES.get(descriptor.type);
  if (!resolvedAssociationType || !parentType) {
    return [];
  }

  const parentName = getNamePart(descriptor.nameParts, 0);
  const parentDescriptor: ResourceDescriptor = {
    type: parentType,
    nameParts: [parentName],
    workspace: descriptor.workspace,
  };
  const entries = await store.readAssociation(
    config.sourceDir,
    parentDescriptor,
    resolvedAssociationType
  );
  const plans: AssociationPublicationPlan[] = [];
  const seen = new Set<string>();

  for (const entry of entries) {
    const plan = await buildAssociationPublicationPlan(
      store,
      context,
      descriptor.type,
      parentName,
      descriptor.workspace,
      entry,
      config,
      allowedDescriptors
    );
    const key = getResourceDescriptorKey(plan.descriptor);
    if (!seen.has(key)) {
      seen.add(key);
      plans.push(plan);
    }
  }

  return plans;
}

async function buildAssociationPublicationPlan(
  store: IArtifactStore,
  context: ApimServiceContext,
  type: ResourceType,
  parentName: string,
  workspace: string | undefined,
  entry: AssociationEntry,
  config: PublishConfig,
  allowedDescriptors?: ResourceDescriptor[]
): Promise<AssociationPublicationPlan> {
  const descriptor: ResourceDescriptor = {
    type,
    nameParts: [parentName, entry.name],
    workspace,
    ...(entry.scope ? { targetScope: entry.scope } : {}),
  };
  const target: ResourceDescriptor = {
    type: type === ResourceType.ProductGroup ? ResourceType.Group : ResourceType.Api,
    nameParts: [entry.name],
    workspace: entry.scope === 'service' ? undefined : workspace,
  };
  const eligibility = await evaluateAssociationEligibility(
    store,
    target,
    config,
    allowedDescriptors
  );
  const metadata = RESOURCE_TYPE_METADATA[type];
  const workspaceScoped = !!workspace || isWorkspaceScope(context);
  const segment = target.type === ResourceType.Group ? 'groups' : 'apis';
  const deployedDescriptor = config.envMapping
    ? mapDescriptor(descriptor, config.envMapping)
    : descriptor;
  const deployedTarget = config.envMapping
    ? mapDescriptor(target, config.envMapping)
    : target;
  const payload = workspaceScoped && metadata.workspaceLinkIdProperty
    ? buildLinkPayload(
        context,
        metadata.workspaceLinkIdProperty,
        segment,
        getNamePart(deployedTarget.nameParts, 0),
        deployedDescriptor.workspace,
        entry.scope
      )
    : {};

  return { descriptor, deployedDescriptor, target, payload, ...eligibility };
}

export async function evaluateAssociationEligibility(
  store: IArtifactStore,
  target: ResourceDescriptor,
  config: PublishConfig,
  allowedDescriptors?: ResourceDescriptor[]
): Promise<PublishEligibility> {
  if (!config.filter) {
    return { eligible: true };
  }

  const effectiveFilter = target.workspace
    ? resolveWorkspaceFilter(target.workspace, config.filter)
    : config.filter;
  if (effectiveFilter && !shouldIncludeResource(target, effectiveFilter)) {
    return { eligible: false, reason: 'target is excluded by the filter' };
  }

  if (allowedDescriptors) {
    if (
      allowedDescriptors.some((allowed) => sameResourceDescriptor(allowed, target))
    ) {
      return { eligible: true };
    }

    if (config.commitId) {
      const exists = (await store.readResource(config.sourceDir, target)) !== undefined;
      return exists
        ? { eligible: true }
        : { eligible: false, reason: 'target was never extracted' };
    }

    if (hasExplicitTypeFilter(target.type, effectiveFilter)) {
      return { eligible: false, reason: 'target is unavailable in the publish set' };
    }

    return { eligible: true };
  }

  if (hasExplicitTypeFilter(target.type, effectiveFilter)) {
    const exists = (await store.readResource(config.sourceDir, target)) !== undefined;
    return exists
      ? { eligible: true }
      : { eligible: false, reason: 'target was never extracted' };
  }

  return { eligible: true };
}

export async function resolveAssociationDeleteDescriptor(
  client: IApimClient,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor
): Promise<ResourceDescriptor | undefined> {
  if (
    !descriptor.workspace ||
    ![
      ResourceType.ProductApi,
      ResourceType.ProductGroup,
      ResourceType.ProductTag,
      ResourceType.ApiTag,
    ].includes(descriptor.type)
  ) {
    return descriptor;
  }

  const linkProperty =
    RESOURCE_TYPE_METADATA[descriptor.type].workspaceLinkIdProperty;
  if (!linkProperty) {
    return descriptor;
  }

  const isTagParent =
    descriptor.type === ResourceType.ProductTag ||
    descriptor.type === ResourceType.ApiTag;
  const parent: ResourceDescriptor = isTagParent
    ? {
        type: ResourceType.Tag,
        nameParts: [getNamePart(descriptor.nameParts, 1)],
        workspace: descriptor.workspace,
      }
    : {
        type: ResourceType.Product,
        nameParts: [getNamePart(descriptor.nameParts, 0)],
        workspace: descriptor.workspace,
      };
  const expectedTarget = isTagParent
    ? getNamePart(descriptor.nameParts, 0)
    : getNamePart(descriptor.nameParts, 1);

  for await (const link of client.listResources(context, descriptor.type, parent)) {
    const properties = link.properties as Record<string, unknown> | undefined;
    const targetId = properties?.[linkProperty];
    const linkName = link.name;
    if (
      typeof targetId !== 'string' ||
      typeof linkName !== 'string' ||
      getArmResourceName(targetId).toLowerCase() !== expectedTarget.toLowerCase() ||
      (descriptor.targetScope !== undefined &&
        getAssociationTargetScope(targetId) !== descriptor.targetScope)
    ) {
      continue;
    }

    return {
      type: descriptor.type,
      nameParts: isTagParent
        ? [linkName, getNamePart(descriptor.nameParts, 1)]
        : [getNamePart(descriptor.nameParts, 0), linkName],
      workspace: descriptor.workspace,
      ...(descriptor.targetScope ? { targetScope: descriptor.targetScope } : {}),
    };
  }

  function getAssociationTargetScope(resourceId: string): 'service' | 'workspace' {
    return /\/workspaces\/[^/]+\//i.test(resourceId) ? 'workspace' : 'service';
  }

  return undefined;
}

function getArmResourceName(resourceId: string): string {
  const segment = resourceId.split('/').filter(Boolean).at(-1) ?? '';
  try {
    return decodeURIComponent(segment);
  } catch {
    return segment;
  }
}

export async function evaluateResourceEligibility(
  store: IArtifactStore,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  json?: Record<string, unknown>
): Promise<PublishEligibility> {
  if (descriptor.type === ResourceType.ApiTag) {
    const target: ResourceDescriptor = {
      type: ResourceType.Tag,
      nameParts: [getNamePart(descriptor.nameParts, 1)],
      workspace: descriptor.workspace,
    };
    return evaluateAssociationEligibility(store, target, config);
  }

  if (descriptor.type !== ResourceType.Subscription || !json) {
    return { eligible: true };
  }

  const properties = json.properties as Record<string, unknown> | undefined;
  const scope = properties?.scope as string | undefined;
  if (
    scope &&
    (scope.endsWith('/') || (!scope.includes('/apis') && !scope.includes('/products')))
  ) {
    return { eligible: false, reason: 'root-scoped subscriptions are managed by APIM' };
  }

  if (isAutoGeneratedProductSubscription(getNamePart(descriptor.nameParts, 0), scope)) {
    return { eligible: false, reason: 'auto-generated product subscription' };
  }

  for (const target of findSubscriptionTargets(json, descriptor.workspace)) {
    const eligibility = await evaluateAssociationEligibility(
      store,
      target,
      config
    );
    if (!eligibility.eligible) {
      return {
        eligible: false,
        reason: `${target.type} target "${target.nameParts.join('/')}" ${eligibility.reason}`,
      };
    }
  }

  return { eligible: true };
}

/**
 * Publish wiki resource (ApiWiki, ProductWiki)
 */
async function publishWiki(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<ResourcePublishResult> {
  let attemptedPut = false;
  try {
    const wikiContent = await store.readContent(
      config.sourceDir,
      descriptor,
      'specification'
    );

    if (!wikiContent) {
      return {
        descriptor,
        status: 'skipped',
        action: 'noop',
      };
    }

    // Build wiki payload
    const payload: Record<string, unknown> = {
      properties: {
        documents: [
          {
            documentId: 'default',
            content: wikiContent.content,
          },
        ],
      },
    };

    const deployedDescriptor = config.envMapping
      ? mapDescriptor(descriptor, config.envMapping)
      : descriptor;
    attemptedPut = true;
    await client.putResource(context, deployedDescriptor, payload);

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: attemptedPut ? 'put' : 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Publish policy resource (ServicePolicy, ApiPolicy, ProductPolicy, ApiOperationPolicy,
 * GraphQLResolverPolicy). The artifact on disk is a raw policy.xml file; there is no
 * separate JSON info file for these types. Reads the XML and PUTs it with format=rawxml.
 */
async function publishPolicy(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<ResourcePublishResult> {
  let attemptedPut = false;
  try {
    const policyContent = await store.readContent(
      config.sourceDir,
      descriptor,
      'policy'
    );

    if (!policyContent) {
      return {
        descriptor,
        status: 'skipped',
        action: 'noop',
      };
    }

    // Fail-safe guard: extracted policies don't currently carry separate metadata
    // indicating prior redaction, so marker detection is a deliberate content
    // check to block publishing placeholder secrets.
    const payload: Record<string, unknown> = {
      properties: {
        value: policyContent.content,
        format: 'rawxml',
      },
    };

    // Apply overrides (e.g., format: xml) before PUT — matches Toolkit behavior
    let mergedPayload = applyOverrides(descriptor, payload, config.overrides);

    // Rewrite policy XML references from canonical → deployed names
    if (config.envMapping && config.knownArtifactSets) {
      const mProps = mergedPayload.properties as Record<string, unknown> | undefined;
      const mValue = mProps?.value;
      if (typeof mValue === 'string') {
        const rewrittenXml = rewritePolicyRefs(mValue, config.envMapping, config.knownArtifactSets);
        mergedPayload = {
          ...mergedPayload,
          properties: { ...(mergedPayload.properties as object), value: rewrittenXml },
        };
      }
    }

    // Marker check runs AFTER overrides and rewriting: an override may legitimately
    // replace the policy value with clean content, so only the merged
    // (about-to-be-published) value is authoritative for redaction detection.
    const mergedProps = mergedPayload.properties as Record<string, unknown> | undefined;
    const mergedValue = mergedProps?.value;
    if (typeof mergedValue === 'string' && mergedValue.includes(REDACTION_MARKER)) {
      throw new Error(
        `Cannot publish ${buildResourceLabel(descriptor)}: policy contains '${REDACTION_MARKER}'. ` +
        'Replace inline secrets with named values before publish: ' +
        'https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-properties'
      );
    }

    // Apply env-mapping: affix descriptor name segments before PUT
    const deployedDescriptor = config.envMapping
      ? mapDescriptor(descriptor, config.envMapping)
      : descriptor;
    attemptedPut = true;
    await client.putResource(context, deployedDescriptor, mergedPayload);

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: attemptedPut ? 'put' : 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Normalise the `properties.scope` field of a Subscription resource.
 *
 * APIM returns scope as a full ARM resource path on GET, e.g.:
 *   /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.ApiManagement/service/{svc}/apis
 *
 * The PUT endpoint requires a relative APIM path, e.g.:
 *   /apis
 *   /apis/{apiId}
 *   /products/{productId}
 *
 * Strip the service base ARM path prefix when it is present so that the
 * extract → publish round-trip works without manual edits.
 */
function normalizeSubscriptionScope(
  json: Record<string, unknown>,
  context: ApimServiceContext,
  workspace?: string,
  envMapping?: EnvMapping
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) return json;

  const scope = props.scope as string | undefined;
  if (!scope) return json;

  // The ARM path prefix lives between "management.azure.com" and the first
  // APIM-relative segment.  Derive it from baseUrl by stripping the protocol+host.
  const armPathPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');

  const localScopeMatch = scope.match(/^\/(apis|products)\/([^/]+)$/i);
  if (localScopeMatch?.[1] && localScopeMatch[2]) {
    const segment = localScopeMatch[1].toLowerCase();
    const type = segment === 'apis' ? ResourceType.Api : ResourceType.Product;
    const name = envMapping
      ? toDeployedName(localScopeMatch[2], type, envMapping)
      : localScopeMatch[2];
    const relativeScope = `/${segment}/${name}`;
    const normalizedScope = workspace
      ? `${armPathPrefix}/workspaces/${
          envMapping
            ? toDeployedName(workspace, ResourceType.Workspace, envMapping)
            : workspace
        }${relativeScope}`
      : relativeScope;
    return {
      ...json,
      properties: { ...props, scope: normalizedScope },
    };
  }

  const serviceScopeMatch = scope.match(
    /^\/subscriptions\/[^/]+\/resourceGroups\/[^/]+\/providers\/Microsoft\.ApiManagement\/service\/[^/]+(\/.*)?$/i
  );
  if (serviceScopeMatch) {
    let relativeScope = serviceScopeMatch[1] || '/';

    // Affix the target resource name when envMapping applies.
    if (envMapping && relativeScope !== '/') {
      if (relativeScope.startsWith('/apis/')) {
        const apiName = relativeScope.slice('/apis/'.length);
        if (apiName) {
          relativeScope = `/apis/${toDeployedName(apiName, ResourceType.Api, envMapping)}`;
        }
      } else if (relativeScope.startsWith('/products/')) {
        const productName = relativeScope.slice('/products/'.length);
        if (productName) {
          relativeScope = `/products/${toDeployedName(productName, ResourceType.Product, envMapping)}`;
        }
      } else {
        const workspaceTarget = relativeScope.match(
          /^(\/workspaces\/[^/]+\/)(apis|products)\/([^/]+)$/i
        );
        if (workspaceTarget?.[1] && workspaceTarget[2] && workspaceTarget[3]) {
          const workspaceName = workspaceTarget[1].split('/')[2] ?? '';
          const deployedWorkspace = toDeployedName(
            workspaceName,
            ResourceType.Workspace,
            envMapping
          );
          const segment = workspaceTarget[2].toLowerCase();
          const type = segment === 'apis' ? ResourceType.Api : ResourceType.Product;
          relativeScope =
            `/workspaces/${deployedWorkspace}/${segment}/${
              toDeployedName(workspaceTarget[3], type, envMapping)
            }`;
        }
      }
    }

    const normalizedScope = relativeScope.startsWith('/workspaces/')
      ? `${armPathPrefix}${relativeScope}`
      : relativeScope;
    return {
      ...json,
      properties: { ...props, scope: normalizedScope },
    };
  }

  return json;
}

export function applyApiPathPrefix(
  json: Record<string, unknown>,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Record<string, unknown> {
  if (descriptor.type !== ResourceType.Api || config.envMapping?.apiPathPrefix === undefined) {
    return json;
  }

  const canonicalApiName = getNamePart(descriptor.nameParts, 0).split(';rev=')[0];
  if (hasExplicitPropertyOverride(canonicalApiName, 'path', config.overrides?.apis)) {
    return json;
  }

  const props = json.properties as Record<string, unknown> | undefined;
  if (typeof props?.path !== 'string') {
    return json;
  }

  const rawPath = props.path;
  const prefix = config.envMapping.apiPathPrefix;
  const path =
    prefix.endsWith('/') && rawPath.startsWith('/')
      ? prefix + rawPath.slice(1)
      : prefix + rawPath;
  return { ...json, properties: { ...props, path } };
}

/**
 * Normalise the `properties.apiId` field of an ApiRelease resource.
 *
 * APIM returns apiId as a full ARM resource path that includes the source
 * service coordinates, e.g.:
 *   /subscriptions/{src-sub}/resourceGroups/{src-rg}/providers/
 *   Microsoft.ApiManagement/service/{src-svc}/apis/my-api;rev=2
 *
 * The PUT to the target service must reference the TARGET service path;
 * otherwise APIM rejects the request because the apiId does not match the
 * service being written to. Rebuild the apiId using the target ARM prefix
 * derived from the publish context.
 */
function normalizeApiReleaseApiId(
  json: Record<string, unknown>,
  context: ApimServiceContext,
  envMapping?: EnvMapping
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) return json;

  const apiId = props.apiId as string | undefined;
  if (!apiId) return json;

  // The target ARM prefix for this service (no https:// host, no trailing slash)
  const targetArmPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');

  // Extract the /apis/... suffix and rebuild with the target ARM prefix.
  // The suffix includes the full API name, e.g. "/apis/my-api;rev=2".
  const apisIndex = apiId.indexOf('/apis/');
  if (apisIndex !== -1) {
    const rawApisSuffix = apiId.slice(apisIndex); // e.g. "/apis/my-api;rev=2"
    let apisSuffix = rawApisSuffix;

    if (envMapping) {
      // Extract api name from "/apis/<name>" possibly with ";rev=N"
      const afterApis = rawApisSuffix.slice('/apis/'.length);
      const revSepIdx = afterApis.indexOf(';rev=');
      const baseApiName = revSepIdx !== -1 ? afterApis.slice(0, revSepIdx) : afterApis;
      const revSuffix = revSepIdx !== -1 ? afterApis.slice(revSepIdx) : '';
      const deployedName = toDeployedName(baseApiName, ResourceType.Api, envMapping);
      apisSuffix = `/apis/${deployedName}${revSuffix}`;
    }

    return {
      ...json,
      properties: { ...props, apiId: targetArmPrefix + apisSuffix },
    };
  }

  return json;
}

export function normalizeApiVersionSetId(
  json: Record<string, unknown>,
  context: ApimServiceContext,
  workspace?: string,
  envMapping?: EnvMapping
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  const versionSetId = props?.apiVersionSetId;
  if (typeof versionSetId !== 'string') {
    return json;
  }

  const versionSetName = getArmResourceName(versionSetId);
  if (!versionSetName) {
    return json;
  }

  const targetArmPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');
  const deployedVersionSet = envMapping
    ? toDeployedName(versionSetName, ResourceType.VersionSet, envMapping)
    : versionSetName;
  const deployedWorkspace = workspace
    ? envMapping
      ? toDeployedName(workspace, ResourceType.Workspace, envMapping)
      : workspace
    : undefined;
  const targetId = deployedWorkspace
    ? `${targetArmPrefix}/workspaces/${deployedWorkspace}/apiVersionSets/${deployedVersionSet}`
    : `${targetArmPrefix}/apiVersionSets/${deployedVersionSet}`;

  return {
    ...json,
    properties: { ...props, apiVersionSetId: targetId },
  };
}

function normalizeBackendPoolServices(
  json: Record<string, unknown>,
  context: ApimServiceContext,
  envMapping?: EnvMapping
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  const pool = props?.pool as Record<string, unknown> | undefined;
  if (!pool || !Array.isArray(pool.services)) {
    return json;
  }

  const targetArmPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');
  const services = pool.services.map((service): unknown => {
    if (!service || typeof service !== 'object') {
      return service;
    }

    const typedService = service as Record<string, unknown>;
    const id = typedService.id;
    if (typeof id !== 'string') {
      return typedService;
    }

    const workspaceMatch = id.match(/\/workspaces\/([^/]+)\/backends\/([^/]+)$/i);
    const serviceMatch = id.match(/\/backends\/([^/]+)$/i);
    const backendName = getArmResourceName(id);
    if (!backendName || (!workspaceMatch && !serviceMatch)) {
      return typedService;
    }

    const deployedBackend = envMapping
      ? toDeployedName(backendName, ResourceType.Backend, envMapping)
      : backendName;
    const sourceWorkspace = workspaceMatch?.[1]
      ? getArmResourceName(`/workspaces/${workspaceMatch[1]}`)
      : undefined;
    const deployedWorkspace = sourceWorkspace
      ? envMapping
        ? toDeployedName(sourceWorkspace, ResourceType.Workspace, envMapping)
        : sourceWorkspace
      : undefined;
    const targetId = deployedWorkspace
      ? `${targetArmPrefix}/workspaces/${deployedWorkspace}/backends/${deployedBackend}`
      : `${targetArmPrefix}/backends/${deployedBackend}`;

    return { ...typedService, id: targetId };
  });

  return {
    ...json,
    properties: {
      ...props,
      pool: { ...pool, services },
    },
  };
}

/**
 * Normalise MCP tool operationIds for MCP APIs.
 *
 * Extracted artifacts store operationId as full source ARM IDs. Rebuild each
 * operationId to target service ARM prefix so APIM validates MCP tools against
 * existing operations in the target instance.
 */
export function normalizeMcpToolOperationIds(
  json: Record<string, unknown>,
  context: ApimServiceContext,
  envMapping?: EnvMapping
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) return json;

  const mcpTools = props.mcpTools;
  if (!Array.isArray(mcpTools) || mcpTools.length === 0) return json;

  const targetArmPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');
  const normalizedTools = mcpTools.map((tool): unknown => {
    if (!tool || typeof tool !== 'object') {
      return tool;
    }
    const typedTool = tool as Record<string, unknown>;
    const operationId = typedTool.operationId;
    if (typeof operationId !== 'string') {
      return typedTool;
    }

    const operationsIndex = operationId.indexOf('/apis/');
    if (operationsIndex === -1) {
      return typedTool;
    }

    const rebuiltOpId = `${targetArmPrefix}${operationId.slice(operationsIndex)}`;
    let finalOpId = rebuiltOpId;

    if (envMapping) {
      // Affix the api name segment (between /apis/ and /operations/)
      const apisIdx = rebuiltOpId.indexOf('/apis/');
      const opsIdx = rebuiltOpId.indexOf('/operations/', apisIdx !== -1 ? apisIdx : 0);
      if (apisIdx !== -1 && opsIdx !== -1) {
        const apiName = rebuiltOpId.slice(apisIdx + '/apis/'.length, opsIdx);
        const deployedApiName = toDeployedName(apiName, ResourceType.Api, envMapping);
        finalOpId =
          rebuiltOpId.slice(0, apisIdx + '/apis/'.length) +
          deployedApiName +
          rebuiltOpId.slice(opsIdx);
      }
    }

    return {
      ...typedTool,
      operationId: finalOpId,
    };
  });

  return {
    ...json,
    properties: {
      ...props,
      mcpTools: normalizedTools,
    },
  };
}

function normalizeApiOperationTextFields(
  json: Record<string, unknown>
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) {
    return json;
  }

  const normalizedProps: Record<string, unknown> = {
    ...props,
  };

  if (normalizedProps.displayName == null) {
    normalizedProps.displayName = '';
  }

  if (normalizedProps.description == null) {
    normalizedProps.description = '';
  }

  return {
    ...json,
    properties: normalizedProps,
  };
}

function isAutoGeneratedProductSubscription(
  subscriptionName: string,
  scope?: string
): boolean {
  if (!scope || !isAutoGeneratedId(subscriptionName)) {
    return false;
  }

  return scope.includes('/products/');
}

/**
 * Publish an ApiTag as a workspace link resource.
 * Workspace scope uses `tags/{tag}/apiLinks/{api}` with a link payload body.
 */
async function publishWorkspaceApiTagLink(
  client: IApimClient,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<ResourcePublishResult> {
  let attemptedPut = false;
  try {
    const canonicalApiName = getNamePart(descriptor.nameParts, 0);
    const deployedApiName = config.envMapping
      ? toDeployedName(canonicalApiName, ResourceType.Api, config.envMapping)
      : canonicalApiName;
    const meta = RESOURCE_TYPE_METADATA[ResourceType.ApiTag];
    if (!meta.workspaceLinkIdProperty) {
      throw new Error(`Missing workspaceLinkIdProperty in metadata for ${ResourceType.ApiTag}`);
    }
    const deployedDescriptor = config.envMapping
      ? mapDescriptor(descriptor, config.envMapping)
      : descriptor;
    const payload = buildLinkPayload(
      context,
      meta.workspaceLinkIdProperty,
      'apis',
      deployedApiName,
      deployedDescriptor.workspace
    );

    try {
      attemptedPut = true;
      await client.putResource(context, deployedDescriptor, payload);
    } catch (error) {
      // 409 means the tag/api link already exists — desired state is in place.
      if (!isLinkAlreadyExistsError(error)) {
        throw error;
      }
    }

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: attemptedPut ? 'put' : 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Rewrite named value references in Logger credentials from {{name}} to
 * {{displayName}}.
 *
 * APIM resolves {{ref}} placeholders by named value displayName, not resource
 * name. Older extracts normalized references to {{name}} which causes APIM to
 * reject the PUT with "Properties specified are missing". This function looks
 * up each referenced named value's artifact to find its displayName and
 * rewrites the reference.
 *
 * References that already use displayName (or don't match any named value
 * artifact) are left unchanged.
 */
async function rewriteNamedValueReferences(
  json: Record<string, unknown>,
  store: IArtifactStore,
  sourceDir: string,
  descriptor: ResourceDescriptor,
  overrides?: OverrideConfig,
  envMapping?: EnvMapping,
): Promise<Record<string, unknown>> {
  const props = json.properties as Record<string, unknown> | undefined;
  const credentials = props?.credentials;
  if (!props || !credentials || typeof credentials !== 'object') {
    return json;
  }

  // Find all {{ref}} tokens in credentials
  const credStr = JSON.stringify(credentials);
  const refPattern = /\{\{([^}]+)\}\}/g;
  const rewriteMap = new Map<string, string>();

  let match;
  while ((match = refPattern.exec(credStr)) !== null) {
    const ref = match[1];
    if (rewriteMap.has(ref)) continue;

    // Try to read the named value artifact by this ref as a resource name
    const nvDescriptor: ResourceDescriptor = {
      type: ResourceType.NamedValue,
      nameParts: [ref],
      ...(descriptor.workspace ? { workspace: descriptor.workspace } : {}),
    };
    let nvJson = await store.readResource(sourceDir, nvDescriptor);
    if (nvJson) {
      // Apply any named value overrides so displayName reflects user config
      nvJson = applyOverrides(nvDescriptor, nvJson, overrides);
      const nvProps = nvJson.properties as Record<string, unknown> | undefined;
      let displayName = nvProps?.displayName as string | undefined;

      // If envMapping applies to NamedValue and no explicit displayName override,
      // use the affixed displayName so {{token}} refs resolve on the shared APIM.
      if (envMapping?.appliesTo.has(ResourceType.NamedValue)) {
        const hasDisplayNameOverride = hasExplicitPropertyOverride(
          ref,
          'displayName',
          overrides?.namedValues,
        );
        if (!hasDisplayNameOverride) {
          const baseDisplayName = displayName ?? ref;
          displayName = toDeployedName(baseDisplayName, ResourceType.NamedValue, envMapping);
        }
      }

      if (displayName && displayName !== ref) {
        rewriteMap.set(ref, displayName);
      }
    } else if (isAutoGeneratedId(ref)) {
      // A 24-char hex ref with no matching artifact likely means the named
      // value was filtered out or deleted. Warn so the user knows the logger
      // credential reference cannot be resolved.
      logger.warn(
        `Logger '${getNamePart(descriptor.nameParts, 0)}' references named value '${ref}' ` +
        `but no matching artifact exists. The logger may fail to publish. ` +
        `Provide a credentials override or include the named value artifact.`
      );
    }
  }

  if (rewriteMap.size === 0) return json;

  // Rewrite {{name}} → {{displayName}} in credentials
  const rewrittenCredentials = rewriteRefs(credentials, rewriteMap);
  logger.debug(
    `Rewrote named value references in Logger '${getNamePart(descriptor.nameParts, 0)}' credentials: ` +
    [...rewriteMap.entries()].map(([n, d]) => `{{${n}}} → {{${d}}}`).join(', ')
  );

  return {
    ...json,
    properties: {
      ...props,
      credentials: rewrittenCredentials,
    },
  };
}

/**
 * Recursively rewrite {{ref}} tokens in a value using the provided map.
 */
function rewriteRefs(
  value: unknown,
  rewriteMap: Map<string, string>
): unknown {
  if (typeof value === 'string') {
    return value.replace(/\{\{([^}]+)\}\}/g, (match, ref: string) => {
      const replacement = rewriteMap.get(ref);
      return replacement ? `{{${replacement}}}` : match;
    });
  }

  if (Array.isArray(value)) {
    return value.map((item) => rewriteRefs(item, rewriteMap));
  }

  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      out[key] = rewriteRefs(child, rewriteMap);
    }
    return out;
  }

  return value;
}
