// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
/**
 * Generic resource publisher
 * Read resource from IArtifactStore, apply overrides, PUT via IApimClient.
 * Handles all 33 resource types using ResourceType metadata.
 * MUST preserve opaque JSON per FR-009.
 */

import type { IApimClient } from '../clients/iapim-client.js';
import type { IArtifactStore } from '../clients/iartifact-store.js';
import type { ApimServiceContext, ResourceDescriptor } from '../models/types.js';
import type { PublishConfig } from '../models/config.js';
import { ResourceType, RESOURCE_TYPE_METADATA } from '../models/resource-types.js';
import { applyOverrides } from './override-merger.js';
import { checkKeyVaultSecretAccess } from './keyvault-checker.js';
import { getNamePart } from '../lib/resource-path.js';
import { isAutoGeneratedId } from '../lib/auto-generated.js';
import { isWorkspaceScope, buildLinkPayload } from '../lib/workspace-link.js';
import { logger } from '../lib/logger.js';
import { REDACTION_MARKER } from './secret-redactor.js';
import { isLinkAlreadyExistsError } from '../clients/apim-client.js';
import type { OverrideConfig } from '../models/config.js';
import { buildResourceLabel } from '../lib/resource-uri.js';

export interface ResourcePublishResult {
  descriptor: ResourceDescriptor;
  status: 'success' | 'failed' | 'skipped';
  action: 'put' | 'delete' | 'noop';
  error?: Error;
}

/**
 * Policy resource types that have external XML content
 */
const POLICY_TYPES = new Set<ResourceType>([
  ResourceType.ServicePolicy,
  ResourceType.ProductPolicy,
  ResourceType.ApiPolicy,
  ResourceType.ApiOperationPolicy,
  ResourceType.GraphQLResolverPolicy,
]);

/**
 * Association resource types that read from association files
 */
const ASSOCIATION_TYPES = new Map<ResourceType, 'apis' | 'groups'>([
  [ResourceType.ProductApi, 'apis'],
  [ResourceType.ProductGroup, 'groups'],
  [ResourceType.GatewayApi, 'apis'],
]);

/**
 * Maps association resource types to their parent resource types.
 * readAssociation / buildAssociationFilePath expect a Product or Gateway
 * descriptor, not the association child type itself.
 */
const ASSOCIATION_PARENT_TYPES = new Map<ResourceType, ResourceType>([
  [ResourceType.ProductApi, ResourceType.Product],
  [ResourceType.ProductGroup, ResourceType.Product],
  [ResourceType.GatewayApi, ResourceType.Gateway],
]);

/**
 * Wiki resource types that read markdown content
 */
const WIKI_TYPES = new Set<ResourceType>([
  ResourceType.ApiWiki,
  ResourceType.ProductWiki,
]);

/**
 * Publish a single resource: read from store, apply overrides, PUT to APIM.
 * Preserves opaque JSON (FR-009). Uses applyOverrides for env-specific values.
 * Returns 'skipped' if resource file doesn't exist in store.
 */
export async function publishResource(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<ResourcePublishResult> {
  try {
    // Handle association types (ProductApi, ProductGroup, GatewayApi)
    const associationType = ASSOCIATION_TYPES.get(descriptor.type);
    if (associationType) {
      return await publishAssociation(
        client,
        store,
        context,
        descriptor,
        config,
        associationType
      );
    }

    // Handle workspace ApiTag — uses link endpoint with link payload.
    // In service scope, ApiTag is a regular PUT with the tag JSON; in workspace
    // scope it becomes a link resource at `tags/{tag}/apiLinks/{api}`.
    if (descriptor.type === ResourceType.ApiTag && (descriptor.workspace || isWorkspaceScope(context))) {
      return await publishWorkspaceApiTagLink(client, context, descriptor);
    }

    // Handle wiki types
    if (WIKI_TYPES.has(descriptor.type)) {
      return await publishWiki(client, store, context, descriptor, config);
    }

    // Handle policy types — artifact is policy.xml (raw XML), not a JSON info file
    if (POLICY_TYPES.has(descriptor.type)) {
      return await publishPolicy(client, store, context, descriptor, config);
    }

    // Read resource JSON from store
    let json = await store.readResource(config.sourceDir, descriptor);
    if (!json) {
      return {
        descriptor,
        status: 'skipped',
        action: 'noop',
      };
    }

    // Rewrite MCP tool operationIds against the target service before overrides
    // so explicit override values win unchanged.
    if (descriptor.type === ResourceType.Api) {
      json = normalizeMcpToolOperationIds(json, context);
    }

    // Apply overrides (deep merge, preserves opaque structure)
    json = applyOverrides(descriptor, json, config.overrides);

    // For Logger resources, rewrite named value references in credentials.
    // APIM resolves {{ref}} by displayName, not resource name. Old extracts
    // stored {{name}}; rewrite to {{displayName}} for APIM compatibility.
    if (descriptor.type === ResourceType.Logger) {
      json = await rewriteNamedValueReferences(json, store, config.sourceDir, descriptor, config.overrides);
    }

    // API operations: enforce explicit empty strings for text fields when omitted.
    // APIM may synthesize description from displayName when description is absent,
    // causing extract/publish round-trip drift.
    if (descriptor.type === ResourceType.ApiOperation) {
      json = normalizeApiOperationTextFields(json);
    }

    // For KeyVault-backed NamedValues:
    //   1. Strip properties.value — APIM must not receive both keyVault and value
    //      in the same PUT body, as it causes indefinite provisioning or rejection.
    //   2. Pre-flight access check — verify the managed identity has GET access
    //      to the secret before attempting the PUT. Surfaces permission errors
    //      early and fails fast instead of polling until timeout.
    if (descriptor.type === ResourceType.NamedValue) {
      const props = json.properties as Record<string, unknown> | undefined;
      const kvBlock = props?.keyVault as Record<string, unknown> | undefined;
      if (kvBlock != null) {
        const { value: _omit, ...propsWithoutValue } = props!;
        json = { ...json, properties: propsWithoutValue };

        const secretIdentifier = kvBlock.secretIdentifier as string | undefined;
        const identityClientId = kvBlock.identityClientId as string | undefined;
        if (secretIdentifier) {
          await checkKeyVaultSecretAccess(secretIdentifier, identityClientId, {
            subscriptionId: context.subscriptionId,
            resourceGroup: context.resourceGroup,
            serviceName: context.serviceName,
          });
        }
      }

      // Guard: reject secret named values that still contain the redaction
      // marker after overrides. This prevents publishing placeholder secrets
      // (e.g., auto-generated named values where the override didn't provide
      // a real value or keyVault reference). Check the current json since
      // KeyVault-backed values have already had 'value' stripped above.
      const currentProps = json.properties as Record<string, unknown> | undefined;
      if (currentProps?.secret === true) {
        const currentValue = currentProps.value as string | undefined;
        if (currentValue === REDACTION_MARKER) {
          logger.warn(
            `Skipping named value '${getNamePart(descriptor.nameParts, 0)}': ` +
            `secret value is still redacted. Provide a 'value' or 'keyVault' override.`
          );
          return {
            descriptor,
            status: 'skipped',
            action: 'noop',
          };
        }
      }
    }

    // Normalize Subscription scope.
    // APIM stores scope as a full ARM resource path (e.g.
    // "/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.ApiManagement/service/{svc}/apis")
    // but the PUT endpoint requires a relative APIM path (e.g. "/apis" or
    // "/apis/{apiId}" or "/products/{productId}").  Strip the service base path
    // prefix when it is present so that the publish round-trip works correctly.
    // HOWEVER: Skip publishing subscriptions with root-level scope (e.g. the built-in
    // "master" subscription), as APIM treats these as read-only system resources
    // and returns ValidationError when attempting to update them.
    if (descriptor.type === ResourceType.Subscription) {
      const props = json.properties as Record<string, unknown> | undefined;
      const scope = props?.scope as string | undefined;
      const subscriptionName = getNamePart(descriptor.nameParts, 0);
      
      // Built-in master subscription has scope ending with the service path (no /apis or /products suffix)
      // Skip it since APIM doesn't allow updates to built-in subscriptions
      if (scope && (scope.endsWith('/') || (!scope.includes('/apis') && !scope.includes('/products')))) {
        return {
          descriptor,
          status: 'skipped',
          action: 'noop',
        };
      }

      if (isAutoGeneratedProductSubscription(subscriptionName, scope)) {
        return {
          descriptor,
          status: 'skipped',
          action: 'noop',
        };
      }

      json = normalizeSubscriptionScope(json, context);
    }

    // ApiRelease: normalize properties.apiId from source ARM path to target ARM path.
    // APIM stores apiId as the full source ARM resource path, e.g.:
    //   /subscriptions/{src-sub}/resourceGroups/{src-rg}/providers/
    //   Microsoft.ApiManagement/service/{src-svc}/apis/my-api;rev=2
    // The PUT to the target service must reference the target service path,
    // otherwise APIM rejects the request with a validation error.
    if (descriptor.type === ResourceType.ApiRelease) {
      json = normalizeApiReleaseApiId(json, context);
    }

    // API Revisions (e.g., "my-api;rev=2") need sourceApiId so APIM knows which
    // base API to copy structure from. Also strip null properties that cause
    // validation errors in APIM's revision creation.
    if (descriptor.type === ResourceType.Api) {
      const apiName = getNamePart(descriptor.nameParts, 0);
      if (apiName.includes(';rev=')) {
        const baseApiName = apiName.split(';rev=')[0];
        const props = json.properties as Record<string, unknown> | undefined;
        const cleanProps: Record<string, unknown> = {};
        for (const [key, val] of Object.entries(props ?? {})) {
          if (val !== null) cleanProps[key] = val;
        }
        cleanProps.sourceApiId = `/subscriptions/${context.subscriptionId}/resourceGroups/${context.resourceGroup}/providers/Microsoft.ApiManagement/service/${context.serviceName}/apis/${baseApiName}`;
        // Preserve source current-revision intent. APIM can implicitly promote a
        // created revision to current if isCurrent is omitted; default to false
        // unless the extracted artifact explicitly set it.
        if (!Object.hasOwn(cleanProps, 'isCurrent')) {
          cleanProps.isCurrent = false;
        }
        json = { ...json, properties: cleanProps };
      }
    }

    // PUT to APIM
    await client.putResource(context, descriptor, json);

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Publish association resource (ProductApi, ProductGroup, GatewayApi)
 */
async function publishAssociation(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig,
  associationType: 'apis' | 'groups'
): Promise<ResourcePublishResult> {
  try {
    // buildAssociationFilePath (called inside readAssociation) only accepts
    // Product or Gateway descriptors — not the association child types
    // (ProductApi, ProductGroup, GatewayApi).  Derive the parent descriptor.
    const parentType = ASSOCIATION_PARENT_TYPES.get(descriptor.type)!;
    const parentDescriptor: ResourceDescriptor = {
      type: parentType,
      nameParts: [getNamePart(descriptor.nameParts, 0)],
      workspace: descriptor.workspace,
    };
    const entries = await store.readAssociation(
      config.sourceDir,
      parentDescriptor,
      associationType
    );

    // Create association for each name
    for (const entry of entries) {
      const assocDescriptor: ResourceDescriptor = {
        type: descriptor.type,
        nameParts: [getNamePart(descriptor.nameParts, 0), entry.name],
      };
      try {
        // PUT empty body for association (APIM uses PUT to create association)
        await client.putResource(context, assocDescriptor, {});
      } catch (error) {
        // 409 means the link already exists — desired state is in place.
        if (!isLinkAlreadyExistsError(error)) {
          throw error;
        }
      }
    }

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Publish wiki resource (ApiWiki, ProductWiki)
 */
async function publishWiki(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<ResourcePublishResult> {
  try {
    const wikiContent = await store.readContent(
      config.sourceDir,
      descriptor,
      'specification'
    );

    if (!wikiContent) {
      return {
        descriptor,
        status: 'skipped',
        action: 'noop',
      };
    }

    // Build wiki payload
    const payload: Record<string, unknown> = {
      properties: {
        documents: [
          {
            documentId: 'default',
            content: wikiContent.content,
          },
        ],
      },
    };

    await client.putResource(context, descriptor, payload);

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Publish policy resource (ServicePolicy, ApiPolicy, ProductPolicy, ApiOperationPolicy,
 * GraphQLResolverPolicy). The artifact on disk is a raw policy.xml file; there is no
 * separate JSON info file for these types. Reads the XML and PUTs it with format=rawxml.
 */
async function publishPolicy(
  client: IApimClient,
  store: IArtifactStore,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor,
  config: PublishConfig
): Promise<ResourcePublishResult> {
  try {
    const policyContent = await store.readContent(
      config.sourceDir,
      descriptor,
      'policy'
    );

    if (!policyContent) {
      return {
        descriptor,
        status: 'skipped',
        action: 'noop',
      };
    }

    // Fail-safe guard: extracted policies don't currently carry separate metadata
    // indicating prior redaction, so marker detection is a deliberate content
    // check to block publishing placeholder secrets.
    if (policyContent.content.includes(REDACTION_MARKER)) {
      throw new Error(
        `Cannot publish ${buildResourceLabel(descriptor)}: policy contains '${REDACTION_MARKER}'. ` +
        'Replace inline secrets with named values before publish: ' +
        'https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-properties'
      );
    }

    const payload: Record<string, unknown> = {
      properties: {
        value: policyContent.content,
        format: 'rawxml',
      },
    };

    // Apply overrides (e.g., format: xml) before PUT — matches Toolkit behavior
    const mergedPayload = applyOverrides(descriptor, payload, config.overrides);

    await client.putResource(context, descriptor, mergedPayload);

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Normalise the `properties.scope` field of a Subscription resource.
 *
 * APIM returns scope as a full ARM resource path on GET, e.g.:
 *   /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.ApiManagement/service/{svc}/apis
 *
 * The PUT endpoint requires a relative APIM path, e.g.:
 *   /apis
 *   /apis/{apiId}
 *   /products/{productId}
 *
 * Strip the service base ARM path prefix when it is present so that the
 * extract → publish round-trip works without manual edits.
 */
function normalizeSubscriptionScope(
  json: Record<string, unknown>,
  context: ApimServiceContext
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) return json;

  const scope = props.scope as string | undefined;
  if (!scope) return json;

  // The ARM path prefix lives between "management.azure.com" and the first
  // APIM-relative segment.  Derive it from baseUrl by stripping the protocol+host.
  const armPathPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');

  if (scope.startsWith(armPathPrefix)) {
    const relativeScope = scope.slice(armPathPrefix.length) || '/';
    return {
      ...json,
      properties: { ...props, scope: relativeScope },
    };
  }

  return json;
}

/**
 * Normalise the `properties.apiId` field of an ApiRelease resource.
 *
 * APIM returns apiId as a full ARM resource path that includes the source
 * service coordinates, e.g.:
 *   /subscriptions/{src-sub}/resourceGroups/{src-rg}/providers/
 *   Microsoft.ApiManagement/service/{src-svc}/apis/my-api;rev=2
 *
 * The PUT to the target service must reference the TARGET service path;
 * otherwise APIM rejects the request because the apiId does not match the
 * service being written to. Rebuild the apiId using the target ARM prefix
 * derived from the publish context.
 */
function normalizeApiReleaseApiId(
  json: Record<string, unknown>,
  context: ApimServiceContext
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) return json;

  const apiId = props.apiId as string | undefined;
  if (!apiId) return json;

  // The target ARM prefix for this service (no https:// host, no trailing slash)
  const targetArmPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');

  // Extract the /apis/... suffix and rebuild with the target ARM prefix.
  // The suffix includes the full API name, e.g. "/apis/my-api;rev=2".
  const apisIndex = apiId.indexOf('/apis/');
  if (apisIndex !== -1) {
    const apisSuffix = apiId.slice(apisIndex);
    return {
      ...json,
      properties: { ...props, apiId: targetArmPrefix + apisSuffix },
    };
  }

  return json;
}

/**
 * Normalise MCP tool operationIds for MCP APIs.
 *
 * Extracted artifacts store operationId as full source ARM IDs. Rebuild each
 * operationId to target service ARM prefix so APIM validates MCP tools against
 * existing operations in the target instance.
 */
export function normalizeMcpToolOperationIds(
  json: Record<string, unknown>,
  context: ApimServiceContext
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) return json;

  const mcpTools = props.mcpTools;
  if (!Array.isArray(mcpTools) || mcpTools.length === 0) return json;

  const targetArmPrefix = context.baseUrl.replace(/^https?:\/\/[^/]+/, '');
  const normalizedTools = mcpTools.map((tool): unknown => {
    if (!tool || typeof tool !== 'object') {
      return tool;
    }
    const typedTool = tool as Record<string, unknown>;
    const operationId = typedTool.operationId;
    if (typeof operationId !== 'string') {
      return typedTool;
    }

    const operationsIndex = operationId.indexOf('/apis/');
    if (operationsIndex === -1) {
      return typedTool;
    }

    return {
      ...typedTool,
      operationId: `${targetArmPrefix}${operationId.slice(operationsIndex)}`,
    };
  });

  return {
    ...json,
    properties: {
      ...props,
      mcpTools: normalizedTools,
    },
  };
}

function normalizeApiOperationTextFields(
  json: Record<string, unknown>
): Record<string, unknown> {
  const props = json.properties as Record<string, unknown> | undefined;
  if (!props) {
    return json;
  }

  const normalizedProps: Record<string, unknown> = {
    ...props,
  };

  if (normalizedProps.displayName == null) {
    normalizedProps.displayName = '';
  }

  if (normalizedProps.description == null) {
    normalizedProps.description = '';
  }

  return {
    ...json,
    properties: normalizedProps,
  };
}

function isAutoGeneratedProductSubscription(
  subscriptionName: string,
  scope?: string
): boolean {
  if (!scope || !isAutoGeneratedId(subscriptionName)) {
    return false;
  }

  return scope.includes('/products/');
}

/**
 * Publish an ApiTag as a workspace link resource.
 * Workspace scope uses `tags/{tag}/apiLinks/{api}` with a link payload body.
 */
async function publishWorkspaceApiTagLink(
  client: IApimClient,
  context: ApimServiceContext,
  descriptor: ResourceDescriptor
): Promise<ResourcePublishResult> {
  try {
    const apiName = getNamePart(descriptor.nameParts, 0);
    const meta = RESOURCE_TYPE_METADATA[ResourceType.ApiTag];
    if (!meta.workspaceLinkIdProperty) {
      throw new Error(`Missing workspaceLinkIdProperty in metadata for ${ResourceType.ApiTag}`);
    }
    const payload = buildLinkPayload(context, meta.workspaceLinkIdProperty, 'apis', apiName, descriptor.workspace);

    try {
      await client.putResource(context, descriptor, payload);
    } catch (error) {
      // 409 means the tag/api link already exists — desired state is in place.
      if (!isLinkAlreadyExistsError(error)) {
        throw error;
      }
    }

    return {
      descriptor,
      status: 'success',
      action: 'put',
    };
  } catch (error) {
    return {
      descriptor,
      status: 'failed',
      action: 'noop',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

/**
 * Rewrite named value references in Logger credentials from {{name}} to
 * {{displayName}}.
 *
 * APIM resolves {{ref}} placeholders by named value displayName, not resource
 * name. Older extracts normalized references to {{name}} which causes APIM to
 * reject the PUT with "Properties specified are missing". This function looks
 * up each referenced named value's artifact to find its displayName and
 * rewrites the reference.
 *
 * References that already use displayName (or don't match any named value
 * artifact) are left unchanged.
 */
async function rewriteNamedValueReferences(
  json: Record<string, unknown>,
  store: IArtifactStore,
  sourceDir: string,
  descriptor: ResourceDescriptor,
  overrides?: OverrideConfig,
): Promise<Record<string, unknown>> {
  const props = json.properties as Record<string, unknown> | undefined;
  const credentials = props?.credentials;
  if (!props || !credentials || typeof credentials !== 'object') {
    return json;
  }

  // Find all {{ref}} tokens in credentials
  const credStr = JSON.stringify(credentials);
  const refPattern = /\{\{([^}]+)\}\}/g;
  const rewriteMap = new Map<string, string>();

  let match;
  while ((match = refPattern.exec(credStr)) !== null) {
    const ref = match[1];
    if (rewriteMap.has(ref)) continue;

    // Try to read the named value artifact by this ref as a resource name
    const nvDescriptor: ResourceDescriptor = {
      type: ResourceType.NamedValue,
      nameParts: [ref],
      ...(descriptor.workspace ? { workspace: descriptor.workspace } : {}),
    };
    let nvJson = await store.readResource(sourceDir, nvDescriptor);
    if (nvJson) {
      // Apply any named value overrides so displayName reflects user config
      nvJson = applyOverrides(nvDescriptor, nvJson, overrides);
      const nvProps = nvJson.properties as Record<string, unknown> | undefined;
      const displayName = nvProps?.displayName as string | undefined;
      if (displayName && displayName !== ref) {
        rewriteMap.set(ref, displayName);
      }
    } else if (isAutoGeneratedId(ref)) {
      // A 24-char hex ref with no matching artifact likely means the named
      // value was filtered out or deleted. Warn so the user knows the logger
      // credential reference cannot be resolved.
      logger.warn(
        `Logger '${getNamePart(descriptor.nameParts, 0)}' references named value '${ref}' ` +
        `but no matching artifact exists. The logger may fail to publish. ` +
        `Provide a credentials override or include the named value artifact.`
      );
    }
  }

  if (rewriteMap.size === 0) return json;

  // Rewrite {{name}} → {{displayName}} in credentials
  const rewrittenCredentials = rewriteRefs(credentials, rewriteMap);
  logger.debug(
    `Rewrote named value references in Logger '${getNamePart(descriptor.nameParts, 0)}' credentials: ` +
    [...rewriteMap.entries()].map(([n, d]) => `{{${n}}} → {{${d}}}`).join(', ')
  );

  return {
    ...json,
    properties: {
      ...props,
      credentials: rewrittenCredentials,
    },
  };
}

/**
 * Recursively rewrite {{ref}} tokens in a value using the provided map.
 */
function rewriteRefs(
  value: unknown,
  rewriteMap: Map<string, string>
): unknown {
  if (typeof value === 'string') {
    return value.replace(/\{\{([^}]+)\}\}/g, (match, ref: string) => {
      const replacement = rewriteMap.get(ref);
      return replacement ? `{{${replacement}}}` : match;
    });
  }

  if (Array.isArray(value)) {
    return value.map((item) => rewriteRefs(item, rewriteMap));
  }

  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      out[key] = rewriteRefs(child, rewriteMap);
    }
    return out;
  }

  return value;
}
