import { describe, it, expect } from 'vitest';
import { isAutoGeneratedId } from '../../../src/lib/auto-generated.js';

describe('auto-generated', () => {
  describe('isAutoGeneratedId', () => {
    it('should return true for 24-char lowercase hex IDs', () => {
      expect(isAutoGeneratedId('69f15c3c10a45d29d855583a')).toBe(true);
      expect(isAutoGeneratedId('69f16ad1ee7da61d543198f7')).toBe(true);
      expect(isAutoGeneratedId('000000000000000000000000')).toBe(true);
      expect(isAutoGeneratedId('ffffffffffffffffffffffff')).toBe(true);
    });

    it('should return false for human-readable schema names', () => {
      expect(isAutoGeneratedId('src-rest-schema-item')).toBe(false);
      expect(isAutoGeneratedId('my-schema')).toBe(false);
      expect(isAutoGeneratedId('PetSchema')).toBe(false);
    });

    it('should return false for human-readable named value names', () => {
      expect(isAutoGeneratedId('src-nv-plain')).toBe(false);
      expect(isAutoGeneratedId('src-nv-secret')).toBe(false);
      expect(isAutoGeneratedId('my-api-key')).toBe(false);
    });

    it('should return false for IDs with wrong length', () => {
      expect(isAutoGeneratedId('69f15c3c10a45d29d85558')).toBe(false); // 23 chars
      expect(isAutoGeneratedId('69f15c3c10a45d29d855583aa')).toBe(false); // 25 chars
      expect(isAutoGeneratedId('')).toBe(false);
    });

    it('should return false for IDs with uppercase hex chars', () => {
      expect(isAutoGeneratedId('69F15C3C10A45D29D855583A')).toBe(false);
      expect(isAutoGeneratedId('69f15c3c10a45d29d855583A')).toBe(false);
    });

    it('should return false for IDs with non-hex characters', () => {
      expect(isAutoGeneratedId('69f15c3c10a45d29d855583g')).toBe(false);
      expect(isAutoGeneratedId('69f15c3c10a45d29d855583-')).toBe(false);
    });
  });
});
