/**
 * Unit tests for T-CMP-03: compare-normalizer.ts
 */

import { describe, it, expect } from 'vitest';
import {
  normalizeResource,
  normalizeValue,
  normalizeString,
  buildResourceMap,
  isAutoGeneratedName,
  getResourceName,
  getArmPathFromBaseUrl,
  splitAtProviders,
  NormalizeContext,
} from '../../../src/lib/compare-normalizer.js';
import { ApimServiceContext } from '../../../src/models/types.js';

const srcCtx: ApimServiceContext = {
  subscriptionId: 'src-sub-id',
  resourceGroup: 'src-rg',
  serviceName: 'src-apim',
  apiVersion: '2024-05-01',
  baseUrl: 'https://management.azure.com/subscriptions/src-sub-id/resourceGroups/src-rg/providers/Microsoft.ApiManagement/service/src-apim',
};

const tgtCtx: ApimServiceContext = {
  subscriptionId: 'tgt-sub-id',
  resourceGroup: 'tgt-rg',
  serviceName: 'tgt-apim',
  apiVersion: '2024-05-01',
  baseUrl: 'https://management.azure.com/subscriptions/tgt-sub-id/resourceGroups/tgt-rg/providers/Microsoft.ApiManagement/service/tgt-apim',
};

const ctx: NormalizeContext = { source: srcCtx, target: tgtCtx };

// ── normalizeResource ─────────────────────────────────────────────────────────

describe('normalizeResource', () => {
  it('strips top-level ARM envelope fields', () => {
    const resource = {
      id: '/subscriptions/src-sub-id/resourceGroups/src-rg/providers/Microsoft.ApiManagement/service/src-apim/apis/petstore',
      type: 'Microsoft.ApiManagement/service/apis',
      name: 'petstore',
      systemData: { createdAt: '2024-01-01' },
      etag: '"abc123"',
      properties: { displayName: 'Petstore' },
    };

    const result = normalizeResource(resource, ctx);

    expect(result).not.toHaveProperty('id');
    expect(result).not.toHaveProperty('type');
    expect(result).not.toHaveProperty('name');
    expect(result).not.toHaveProperty('systemData');
    expect(result).not.toHaveProperty('etag');
    expect(result).toHaveProperty('properties');
  });

  it('strips read-only root properties from properties bag', () => {
    const resource = {
      properties: {
        displayName: 'Test API',
        provisioningState: 'Succeeded',
        createdAtUtc: '2024-01-01T00:00:00Z',
        lastModifiedDate: '2024-01-02T00:00:00Z',
        isCurrent: true,
        isOnline: true,
        stateComment: '',
        createdDate: '2024-01-01',
      },
    };

    const result = normalizeResource(resource, ctx) as { properties: Record<string, unknown> };

    expect(result.properties).toHaveProperty('displayName');
    expect(result.properties).not.toHaveProperty('provisioningState');
    expect(result.properties).not.toHaveProperty('createdAtUtc');
    expect(result.properties).not.toHaveProperty('lastModifiedDate');
    expect(result.properties).not.toHaveProperty('isCurrent');
    expect(result.properties).not.toHaveProperty('isOnline');
    expect(result.properties).not.toHaveProperty('stateComment');
    expect(result.properties).not.toHaveProperty('createdDate');
  });

  it('keeps non-properties top-level fields (e.g. location, sku)', () => {
    const resource = {
      location: 'eastus',
      sku: { name: 'Developer', capacity: 1 },
    };

    const result = normalizeResource(resource, ctx);
    expect(result).toHaveProperty('location');
    expect(result).toHaveProperty('sku');
  });
});

// ── normalizeValue ────────────────────────────────────────────────────────────

describe('normalizeValue', () => {
  it('returns null unchanged', () => {
    expect(normalizeValue(null, ctx)).toBeNull();
  });

  it('returns undefined unchanged', () => {
    expect(normalizeValue(undefined, ctx)).toBeUndefined();
  });

  it('returns numbers unchanged', () => {
    expect(normalizeValue(42, ctx)).toBe(42);
  });

  it('returns booleans unchanged', () => {
    expect(normalizeValue(true, ctx)).toBe(true);
  });

  it('normalizes strings', () => {
    const result = normalizeValue(
      '/subscriptions/src-sub-id/resourceGroups/src-rg/providers/Microsoft.ApiManagement/service/src-apim',
      ctx,
    );
    expect(result).toBe(
      '/subscriptions/{{sub}}/resourceGroups/{{rg}}/providers/Microsoft.ApiManagement/service/{{apim-name}}',
    );
  });

  it('sorts array elements for order-independent comparison', () => {
    const arr = [{ val: 'b' }, { val: 'a' }, { val: 'c' }];
    const result = normalizeValue(arr, ctx) as unknown[];
    const json = result.map((x) => JSON.stringify(x));
    expect(json).toEqual([...json].sort());
  });

  it('strips timestamp properties at any depth', () => {
    const obj = {
      lastStatus: { timeStampUtc: '2024-01-01' },
      createdDateTime: '2024-01-01',
      displayName: 'Keep me',
    };
    const result = normalizeValue(obj, ctx) as Record<string, unknown>;
    expect(result).not.toHaveProperty('lastStatus');
    expect(result).not.toHaveProperty('createdDateTime');
    expect(result).toHaveProperty('displayName');
  });

  it('strips read-only root properties when isRoot=true', () => {
    const props = {
      displayName: 'API',
      provisioningState: 'Succeeded',
    };
    const result = normalizeValue(props, ctx, true) as Record<string, unknown>;
    expect(result).not.toHaveProperty('provisioningState');
    expect(result).toHaveProperty('displayName');
  });

  it('does NOT strip root-only properties when isRoot=false', () => {
    const props = {
      displayName: 'API',
      provisioningState: 'Succeeded',
    };
    const result = normalizeValue(props, ctx, false) as Record<string, unknown>;
    // provisioningState is only stripped at root
    expect(result).toHaveProperty('provisioningState');
  });

  it('strips request/response ignored properties on objects with representations', () => {
    const obj = {
      description: 'This should be stripped',
      representations: [{ contentType: 'application/json' }],
      statusCode: 200,
    };
    const result = normalizeValue(obj, ctx) as Record<string, unknown>;
    expect(result).not.toHaveProperty('description');
    expect(result).toHaveProperty('statusCode');
  });

  it('strips representation ignored properties on objects with contentType', () => {
    const obj = {
      contentType: 'application/json',
      description: 'remove',
      schemaId: 'remove',
      typeName: 'remove',
      sample: 'keep',
    };
    const result = normalizeValue(obj, ctx) as Record<string, unknown>;
    expect(result).not.toHaveProperty('description');
    expect(result).not.toHaveProperty('schemaId');
    expect(result).not.toHaveProperty('typeName');
    expect(result).toHaveProperty('sample');
  });
});

// ── normalizeString ───────────────────────────────────────────────────────────

describe('normalizeString', () => {
  it('replaces source APIM full ARM path', () => {
    const s = '/subscriptions/src-sub-id/resourceGroups/src-rg/providers/Microsoft.ApiManagement/service/src-apim/apis/petstore';
    expect(normalizeString(s, ctx)).toBe(
      '/subscriptions/{{sub}}/resourceGroups/{{rg}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/apis/petstore',
    );
  });

  it('replaces target APIM full ARM path', () => {
    const s = '/subscriptions/tgt-sub-id/resourceGroups/tgt-rg/providers/Microsoft.ApiManagement/service/tgt-apim/apis/petstore';
    expect(normalizeString(s, ctx)).toBe(
      '/subscriptions/{{sub}}/resourceGroups/{{rg}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/apis/petstore',
    );
  });

  it('replaces subscription+RG path (no provider)', () => {
    const s = '/subscriptions/src-sub-id/resourceGroups/src-rg/providers/Microsoft.KeyVault/vaults/myVault';
    expect(normalizeString(s, ctx)).toBe(
      '/subscriptions/{{sub}}/resourceGroups/{{rg}}/providers/Microsoft.KeyVault/vaults/myVault',
    );
  });

  it('replaces subscription only', () => {
    const s = '/subscriptions/src-sub-id/other';
    expect(normalizeString(s, ctx)).toBe('/subscriptions/{{sub}}/other');
  });

  it('replaces service name in any position', () => {
    expect(normalizeString('Display name: src-apim instance', ctx)).toBe(
      'Display name: {{apim-name}} instance',
    );
  });

  it('normalizes Key Vault URIs', () => {
    expect(normalizeString('https://my-vault.vault.azure.net/secrets/mykey', ctx)).toBe(
      'https://{{keyvault}}.vault.azure.net/secrets/mykey',
    );
  });

  it('normalizes Key Vault secret prefixes (src-/tgt-)', () => {
    expect(normalizeString('https://vault.vault.azure.net/secrets/src-mykey', ctx)).toBe(
      'https://{{keyvault}}.vault.azure.net/secrets/{{prefix}}-mykey',
    );
  });

  it('normalizes App Insights resource IDs', () => {
    expect(
      normalizeString('/providers/Microsoft.Insights/components/my-appinsights/foo', ctx),
    ).toBe('/providers/Microsoft.Insights/components/{{appinsights}}/foo');
  });

  it('normalizes Event Hub namespace IDs', () => {
    expect(
      normalizeString('/providers/Microsoft.EventHub/namespaces/my-eventhub/foo', ctx),
    ).toBe('/providers/Microsoft.EventHub/namespaces/{{eventhub}}/foo');
  });

  it('replaces 24-char hex auto-generated IDs', () => {
    expect(normalizeString('schema-id:abcdef0123456789abcdef01', ctx)).toBe(
      'schema-id:{{auto-id}}',
    );
  });

  it('replaces GUID-format IDs', () => {
    expect(normalizeString('id:12345678-1234-1234-1234-123456789abc', ctx)).toBe(
      'id:{{guid}}',
    );
  });
});

// ── isAutoGeneratedName ───────────────────────────────────────────────────────

describe('isAutoGeneratedName', () => {
  it('returns true for 24-char lowercase hex', () => {
    expect(isAutoGeneratedName('abcdef0123456789abcdef01')).toBe(true);
  });

  it('returns true for UUID format', () => {
    expect(isAutoGeneratedName('12345678-1234-1234-1234-123456789abc')).toBe(true);
  });

  it('returns false for regular names', () => {
    expect(isAutoGeneratedName('petstore')).toBe(false);
    expect(isAutoGeneratedName('my-api')).toBe(false);
    expect(isAutoGeneratedName('echo-api')).toBe(false);
  });

  it('returns false for 24-char mixed-case (not valid hex)', () => {
    expect(isAutoGeneratedName('ABCDEF0123456789ABCDEF01')).toBe(false);
  });
});

// ── buildResourceMap ──────────────────────────────────────────────────────────

describe('buildResourceMap', () => {
  it('returns empty map for empty input', () => {
    const map = buildResourceMap([], ctx);
    expect(map.size).toBe(0);
  });

  it('keys resources by last segment of id', () => {
    const items = [
      { id: '/subs/s/rg/r/providers/x/apis/petstore', properties: {} },
      { id: '/subs/s/rg/r/providers/x/apis/swagger', properties: {} },
    ];
    const map = buildResourceMap(items, ctx);
    expect(map.has('petstore')).toBe(true);
    expect(map.has('swagger')).toBe(true);
  });

  it('excludes names in excludeNames set', () => {
    const items = [
      { id: '/apis/echo-api', properties: {} },
      { id: '/apis/petstore', properties: {} },
    ];
    const map = buildResourceMap(items, ctx, new Set(['echo-api']));
    expect(map.has('echo-api')).toBe(false);
    expect(map.has('petstore')).toBe(true);
  });

  it('keys auto-generated names by sorted position', () => {
    const items = [
      { id: '/schemas/abcdef0123456789abcdef01', properties: { value: 'b' } },
      { id: '/schemas/abcdef0123456789abcdef02', properties: { value: 'a' } },
    ];
    const map = buildResourceMap(items, ctx);
    // Both are auto-generated — should have positional keys
    expect(map.has('{{auto-id-0}}')).toBe(true);
    expect(map.has('{{auto-id-1}}')).toBe(true);
    // Should be sorted — value 'a' sorts before 'b'
    const item0 = map.get('{{auto-id-0}}') as Record<string, unknown>;
    const props0 = item0['properties'] as Record<string, unknown>;
    expect(props0['value']).toBe('a');
  });

  it('mixes regular and auto-generated names', () => {
    const items = [
      { id: '/apis/petstore', properties: {} },
      { id: '/schemas/abcdef0123456789abcdef01', properties: {} },
    ];
    const map = buildResourceMap(items, ctx);
    expect(map.has('petstore')).toBe(true);
    expect(map.has('{{auto-id-0}}')).toBe(true);
  });
});

// ── getResourceName ───────────────────────────────────────────────────────────

describe('getResourceName', () => {
  it('returns last segment of id', () => {
    expect(getResourceName({ id: '/a/b/c/myResource' })).toBe('myResource');
  });

  it('falls back to name property', () => {
    expect(getResourceName({ name: 'myResource' })).toBe('myResource');
  });

  it('returns undefined when neither id nor name is present', () => {
    expect(getResourceName({})).toBeUndefined();
  });
});

// ── getArmPathFromBaseUrl ─────────────────────────────────────────────────────

describe('getArmPathFromBaseUrl', () => {
  it('extracts path from an Azure public cloud baseUrl', () => {
    expect(getArmPathFromBaseUrl(
      'https://management.azure.com/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apim1',
    )).toBe('/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apim1');
  });

  it('extracts path from an Azure China cloud baseUrl', () => {
    expect(getArmPathFromBaseUrl(
      'https://management.chinacloudapi.cn/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apim1',
    )).toBe('/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apim1');
  });

  it('extracts path from a US Gov cloud baseUrl', () => {
    expect(getArmPathFromBaseUrl(
      'https://management.usgovcloudapi.net/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apim1',
    )).toBe('/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apim1');
  });
});

// ── splitAtProviders ──────────────────────────────────────────────────────────

describe('splitAtProviders', () => {
  it('returns sub+RG path from full APIM ARM path', () => {
    expect(splitAtProviders(
      '/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.ApiManagement/service/apim1',
    )).toBe('/subscriptions/sub1/resourceGroups/rg1');
  });

  it('returns empty string when /providers/ is absent', () => {
    expect(splitAtProviders('/subscriptions/sub1')).toBe('');
  });
});
