<#
.SYNOPSIS
  Master orchestrator for the extract→publish round-trip integration test.

.DESCRIPTION
  Single entry point that deploys source + target APIM instances, extracts from
  source, publishes to target, compares the two, and tears down. Works both
  locally and in CI (writes to GITHUB_OUTPUT when available).

  A unique 6-character ID is auto-generated for resource group naming to avoid
  conflicts when tests run in parallel (e.g., different branches or CI jobs).
  Resource names inside the groups (APIM, Key Vault, Event Hub, App Insights)
  are auto-generated by Bicep using uniqueString(resourceGroup().id).

  Exit codes:
    0 — all phases passed
    1 — verification diff detected
    2 — deployment, extract, or publish error

.PARAMETER HardDelete
  When specified, performs a hard-delete (purge) of APIM instances on teardown.
  This prevents soft-deleted APIM instances from blocking reuse of the same names.

.EXAMPLE
  # Full run (auto-generates unique resource group and resource names)
  .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com

  # Full run with explicit resource groups (resource names still auto-generated)
  .\run-roundtrip-test.ps1 -SourceResourceGroup rg-src -TargetResourceGroup rg-tgt -PublisherEmail admin@contoso.com

  # Keep resources after test for debugging
  .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com -SkipTeardown

  # Hard-delete APIM instances on teardown (purge from soft-delete)
  .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com -HardDelete
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$SourceResourceGroup,

    [Parameter()]
    [string]$TargetResourceGroup,

    [ValidateSet('Developer', 'Premium', 'StandardV2', 'PremiumV2')]
    [string]$SkuName = 'StandardV2',

    [string]$Location = 'eastus2',

    [ValidateSet('Info', 'Verbose', 'Debug')]
    [string]$LogLevel = 'Verbose',

    [Parameter(Mandatory)]
    [string]$PublisherEmail,

    [string]$ExtractOutputDir = './extracted-artifacts',

    [switch]$SkipTeardown,

    [switch]$HardDelete
)

$ErrorActionPreference = 'Stop'
$VerbosePreference = if ($LogLevel -in @('Verbose', 'Debug')) { 'Continue' } else { 'SilentlyContinue' }
$DebugPreference = if ($LogLevel -eq 'Debug') { 'Continue' } else { 'SilentlyContinue' }

# Default to hard-delete on teardown unless explicitly disabled.
if (-not $PSBoundParameters.ContainsKey('HardDelete')) {
    $HardDelete = $true
}

# ---------------------------------------------------------------------------
# Generate unique identifier for resource group naming
# ---------------------------------------------------------------------------

# Generate a date-based ID with random suffix to avoid naming conflicts across parallel runs
# Format: {yyyyMMddHHmmss}-{xxx} - timestamp for traceability + random suffix for uniqueness
# Resource names inside the RG (APIM, KeyVault, etc.) are handled by Bicep using uniqueString()
$timestamp = Get-Date -Format "yyyyMMddHHmmss"
$random = -join ((97..122) | Get-Random -Count 3 | ForEach-Object { [char]$_ })
$UniqueId = "$timestamp-$random"  # e.g., 20260427153042-abc
Write-Host "🔑 Generated unique ID: $UniqueId"

# Write UniqueId to GitHub Actions output for CI traceability
if ($env:GITHUB_OUTPUT) {
    "unique_id=$UniqueId" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
}

# Apply defaults with UniqueId suffix to avoid resource group naming conflicts
if (-not $SourceResourceGroup) {
    $SourceResourceGroup = "bvt-$UniqueId-src-rg"
}
if (-not $TargetResourceGroup) {
    $TargetResourceGroup = "bvt-$UniqueId-tgt-rg"
}

Write-Host "   Source RG: $SourceResourceGroup"
Write-Host "   Target RG: $TargetResourceGroup"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

$overallTimer = [System.Diagnostics.Stopwatch]::StartNew()

function Write-Phase([string]$emoji, [string]$message) {
    $ts = $overallTimer.Elapsed.ToString('hh\:mm\:ss')
    Write-Host ""
    Write-Host "$emoji [$ts] $message"
    Write-Host ("-" * 60)
}

function Write-PhaseEnd([string]$emoji, [string]$message) {
    $ts = $overallTimer.Elapsed.ToString('hh\:mm\:ss')
    Write-Host "$emoji [$ts] $message"
}

function Write-GithubOutput([string]$key, [string]$value) {
    if ($env:GITHUB_OUTPUT) {
        "$key=$value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    }
}

function Invoke-Teardown {
    if ($SkipTeardown) {
        Write-Host "⏭️  Teardown skipped (-SkipTeardown)"
        return
    }
    Write-Phase "🧹" "TEARDOWN — Deleting resource groups"
    
    # Capture APIM names before deletion for potential hard-delete
    $sourceApimName = $null
    $targetApimName = $null
    
    if ($HardDelete) {
        # Query APIM instances in each resource group before deletion
        $sourceApimName = az apim list --resource-group $SourceResourceGroup --query "[0].name" -o tsv 2>$null
        $targetApimName = az apim list --resource-group $TargetResourceGroup --query "[0].name" -o tsv 2>$null
        
        if ($sourceApimName) {
            Write-Host "   Found source APIM: $sourceApimName"
        }
        if ($targetApimName) {
            Write-Host "   Found target APIM: $targetApimName"
        }
    }
    
    Write-Host "   Deleting $SourceResourceGroup..."
    az group delete --name $SourceResourceGroup --yes --no-wait 2>$null
    Write-Host "   Deleting $TargetResourceGroup..."
    az group delete --name $TargetResourceGroup --yes --no-wait 2>$null
    
    if ($HardDelete) {
        Write-Host "   ⏳ Waiting for resource group deletions to complete for hard-delete..."
        
        # Wait for resource groups to be deleted (APIM moves to soft-delete state)
        $maxWaitMinutes = 15
        $waited = 0
        $interval = 30
        
        while ($waited -lt ($maxWaitMinutes * 60)) {
            $srcExists = (az group exists --name $SourceResourceGroup -o tsv 2>$null) -eq 'true'
            $tgtExists = (az group exists --name $TargetResourceGroup -o tsv 2>$null) -eq 'true'
            
            if (-not $srcExists -and -not $tgtExists) {
                Write-Host "   ✅ Resource groups deleted"
                break
            }
            
            Write-Host "   ... waiting for resource group deletion (${waited}s elapsed)"
            Start-Sleep -Seconds $interval
            $waited += $interval
        }
        
        # Purge soft-deleted APIM instances
        if ($sourceApimName) {
            Write-Host "   🗑️  Purging soft-deleted APIM: $sourceApimName..."
            az apim deletedservice purge --service-name $sourceApimName --location $Location 2>$null
            if ($LASTEXITCODE -eq 0) {
                Write-Host "   ✅ $sourceApimName purged"
            } else {
                Write-Host "   ⚠️  Could not purge $sourceApimName (may not exist in soft-delete)"
            }
        }
        
        if ($targetApimName) {
            Write-Host "   🗑️  Purging soft-deleted APIM: $targetApimName..."
            az apim deletedservice purge --service-name $targetApimName --location $Location 2>$null
            if ($LASTEXITCODE -eq 0) {
                Write-Host "   ✅ $targetApimName purged"
            } else {
                Write-Host "   ⚠️  Could not purge $targetApimName (may not exist in soft-delete)"
            }
        }
        
        Write-PhaseEnd "🧹" "Teardown complete (hard-delete)"
    } else {
        Write-PhaseEnd "🧹" "Teardown initiated (async deletions)"
    }
}

# ---------------------------------------------------------------------------
# Pre-flight: Validate Azure CLI auth
# ---------------------------------------------------------------------------

Write-Phase "🔐" "PRE-FLIGHT — Validating Azure CLI authentication"

$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Error "Not logged in to Azure CLI. Run 'az login' first."
    exit 2
}

$subscriptionId = $account.id
Write-Host "   Subscription: $($account.name) ($subscriptionId)"
Write-PhaseEnd "🔐" "Azure CLI authenticated"

# ---------------------------------------------------------------------------
# Resolve sibling script paths
# ---------------------------------------------------------------------------

$deploySourceScript      = Join-Path $PSScriptRoot 'Deploy-SourceApim.ps1'
$targetBicepFile         = Join-Path $PSScriptRoot 'target-apim.bicep'
$compareScript           = Join-Path $PSScriptRoot 'Compare-ApimInstance.ps1'

foreach ($requiredFile in @($deploySourceScript, $targetBicepFile, $compareScript)) {
    if (-not (Test-Path $requiredFile)) {
        Write-Error "Required file not found: $requiredFile"
        exit 2
    }
}

# ---------------------------------------------------------------------------
# Transcript files for deployment jobs (Start-Transcript captures all output)
# ---------------------------------------------------------------------------

$logsDir = Join-Path $PSScriptRoot 'logs'
if (-not (Test-Path $logsDir)) {
    New-Item -ItemType Directory -Path $logsDir -Force | Out-Null
}
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$sourceLogFile = Join-Path $logsDir "source-deploy-$UniqueId-$timestamp.log"
$targetLogFile = Join-Path $logsDir "target-deploy-$UniqueId-$timestamp.log"

# ---------------------------------------------------------------------------
# Storage for deployment outputs
# ---------------------------------------------------------------------------

$sourceOutputs = $null
$targetOutputs = $null
$exitCode = 0

try {
    # -----------------------------------------------------------------------
    # Phase 1: Deploy
    # -----------------------------------------------------------------------
    Write-Phase "🚀" "PHASE 1 — Deploy source and target APIM instances (parallel)"
    $deployTimer = [System.Diagnostics.Stopwatch]::StartNew()

    # --- Source deployment job ---
    $sourceJob = Start-Job -Name 'DeploySource' -ScriptBlock {
                param($script, $rg, $sku, $loc, $email, $transcriptFile, $logLevel)
                $ErrorActionPreference = 'Stop'
                Start-Transcript -Path $transcriptFile -Force | Out-Null
                try {
                    $scriptArgs = @{
                        ResourceGroupName = $rg
                        SkuName           = $sku
                        Location          = $loc
                        PublisherEmail    = $email
                    }
                    switch ($logLevel) {
                        'Verbose' { $scriptArgs.Verbose = $true }
                        'Debug'   { $scriptArgs.Debug = $true }
                    }
                    $result = & $script @scriptArgs
                    if (-not $result -or -not $result.apimServiceName) {
                        throw "Source deployment returned no outputs"
                    }
                    return $result
                } finally {
                    Stop-Transcript | Out-Null
                }
    } -ArgumentList $deploySourceScript, $SourceResourceGroup, $SkuName, $Location, $PublisherEmail, $sourceLogFile, $LogLevel
    Write-Host "   ▶ Source deployment started"

    # --- Target deployment job ---
    $targetJob = Start-Job -Name 'DeployTarget' -ScriptBlock {
                param($rg, $sku, $loc, $email, $bicep, $transcriptFile)
                $ErrorActionPreference = 'Stop'
                Start-Transcript -Path $transcriptFile -Force | Out-Null
                try {
                    Write-Host "Starting target APIM deployment..."
                    Write-Host "Resource Group: $rg"
                    Write-Host "SKU: $sku"
                    Write-Host "Location: $loc"
                    
                    Write-Host "Creating resource group..."
                    az group create --name $rg --location $loc --output none
                    if ($LASTEXITCODE -ne 0) { 
                        throw "Failed to create target resource group" 
                    }
                    
                    Write-Host "Deploying target-apim.bicep (this takes 30-45 minutes)..."
                    $raw = az deployment group create `
                        --resource-group $rg `
                        --name "target-apim-$(Get-Date -Format 'yyyyMMddHHmmss')" `
                        --template-file $bicep `
                        --parameters skuName=$sku location=$loc publisherEmail=$email `
                        --output json
                    if ($LASTEXITCODE -ne 0) { 
                        throw "Target APIM deployment failed" 
                    }
                    $result = $raw | ConvertFrom-Json
                    if (-not $result.properties.outputs) {
                        throw "Target deployment returned no outputs"
                    }
                    Write-Host "✅ Target APIM deployed successfully: $($result.properties.outputs.apimServiceName.value)"
                    return $result.properties.outputs
                } finally {
                    Stop-Transcript | Out-Null
                }
    } -ArgumentList $TargetResourceGroup, $SkuName, $Location, $PublisherEmail, $targetBicepFile, $targetLogFile
    Write-Host "   ▶ Target deployment started"

    # --- Wait for jobs with real-time log streaming ---
    $jobs = @($sourceJob, $targetJob)
    Write-Host ""
    Write-Host "   ⏳ Waiting for deployments to complete (streaming logs)..."
    Write-Host ""
            
    # Track last read position for each log file
    $sourceLastPos = 0
    $targetLastPos = 0
    
    while (($jobs | Where-Object { $_.State -eq 'Running' }).Count -gt 0) {
        # Stream new content from source log
        if (Test-Path $sourceLogFile) {
            $content = Get-Content $sourceLogFile -Raw -ErrorAction SilentlyContinue
            if ($content -and $content.Length -gt $sourceLastPos) {
                $newContent = $content.Substring($sourceLastPos)
                $newContent -split "`n" | Where-Object { $_.Trim() } | ForEach-Object {
                    Write-Host "   [SRC] $_"
                }
                $sourceLastPos = $content.Length
            }
        }
        
        # Stream new content from target log
        if (Test-Path $targetLogFile) {
            $content = Get-Content $targetLogFile -Raw -ErrorAction SilentlyContinue
            if ($content -and $content.Length -gt $targetLastPos) {
                $newContent = $content.Substring($targetLastPos)
                $newContent -split "`n" | Where-Object { $_.Trim() } | ForEach-Object {
                    Write-Host "   [TGT] $_"
                }
                $targetLastPos = $content.Length
            }
        }
        
        Start-Sleep -Seconds 5
    }
    
    # Final flush of any remaining log content
    if (Test-Path $sourceLogFile) {
        $content = Get-Content $sourceLogFile -Raw -ErrorAction SilentlyContinue
        if ($content -and $content.Length -gt $sourceLastPos) {
            $newContent = $content.Substring($sourceLastPos)
            $newContent -split "`n" | Where-Object { $_.Trim() } | ForEach-Object {
                Write-Host "   [SRC] $_"
            }
        }
    }
    if (Test-Path $targetLogFile) {
        $content = Get-Content $targetLogFile -Raw -ErrorAction SilentlyContinue
        if ($content -and $content.Length -gt $targetLastPos) {
            $newContent = $content.Substring($targetLastPos)
            $newContent -split "`n" | Where-Object { $_.Trim() } | ForEach-Object {
                Write-Host "   [TGT] $_"
            }
        }
    }
    
    Write-Host ""

    # --- Check source result ---
    if ($sourceJob.State -eq 'Failed') {
        Write-Host "❌ Source deployment failed:"
        # Capture both output and error streams from the failed job
        $jobOutput = Receive-Job $sourceJob -ErrorAction SilentlyContinue 2>&1
        if ($jobOutput) { $jobOutput | ForEach-Object { Write-Host "   $_" } }
        # Also check job's error record for terminating errors
        if ($sourceJob.ChildJobs[0].Error) {
            $sourceJob.ChildJobs[0].Error | ForEach-Object { Write-Host "   $_" }
        }
        $exitCode = 2
    } else {
        $sourceOutputs = Receive-Job $sourceJob
        Write-Host "   ✅ Source deployed: $($sourceOutputs.apimServiceName)"
    }
    Remove-Job $sourceJob

    # --- Check target result ---
    if ($targetJob.State -eq 'Failed') {
        Write-Host "❌ Target deployment failed:"
        # Capture both output and error streams from the failed job
        $jobOutput = Receive-Job $targetJob -ErrorAction SilentlyContinue 2>&1
        if ($jobOutput) { $jobOutput | ForEach-Object { Write-Host "   $_" } }
        # Also check job's error record for terminating errors
        if ($targetJob.ChildJobs[0].Error) {
            $targetJob.ChildJobs[0].Error | ForEach-Object { Write-Host "   $_" }
        }
        $exitCode = 2
    } else {
        $targetOutputs = Receive-Job $targetJob
        Write-Host "   ✅ Target deployed: $($targetOutputs.apimServiceName.value)"
    }
    Remove-Job $targetJob

    $deployTimer.Stop()
    $deployDuration = $deployTimer.Elapsed.ToString('hh\:mm\:ss')
    Write-GithubOutput 'deploy_duration' $deployDuration

    if ($exitCode -ne 0) {
        Write-Host "❌ Deployment phase failed — aborting"
        Invoke-Teardown
        exit $exitCode
    }

    Write-PhaseEnd "🚀" "PHASE 1 complete — both instances deployed ($deployDuration)"

    # Resolve source identifiers (from deploy outputs)
    $sourceSubId   = if ($sourceOutputs -and $sourceOutputs.subscriptionId) { $sourceOutputs.subscriptionId } else { $subscriptionId }
    $sourceRg      = if ($sourceOutputs -and $sourceOutputs.resourceGroup) { $sourceOutputs.resourceGroup } else { $SourceResourceGroup }
    $sourceName    = if ($sourceOutputs -and $sourceOutputs.apimServiceName) { $sourceOutputs.apimServiceName } else {
        # Query APIM instance from resource group
        $apimName = az apim list --resource-group $SourceResourceGroup --query "[0].name" -o tsv 2>$null
        if (-not $apimName) {
            Write-Host "❌ No APIM instance found in resource group $SourceResourceGroup"
            exit 2
        }
        $apimName
    }

    # Resolve target identifiers (target outputs are Bicep-style .value properties)
    $targetSubId   = if ($targetOutputs -and $targetOutputs.subscriptionId.value) { $targetOutputs.subscriptionId.value } else { $subscriptionId }
    $targetRg      = if ($targetOutputs -and $targetOutputs.resourceGroupName.value) { $targetOutputs.resourceGroupName.value } else { $TargetResourceGroup }
    $targetName    = if ($targetOutputs -and $targetOutputs.apimServiceName.value) { $targetOutputs.apimServiceName.value } else {
        # Query APIM instance from resource group
        $apimName = az apim list --resource-group $TargetResourceGroup --query "[0].name" -o tsv 2>$null
        if (-not $apimName) {
            Write-Host "❌ No APIM instance found in resource group $TargetResourceGroup"
            exit 2
        }
        $apimName
    }

    # -----------------------------------------------------------------------
    # Phase 2: Extract
    # -----------------------------------------------------------------------
    Write-Phase "📥" "PHASE 2 — Extract from source APIM"
    $extractTimer = [System.Diagnostics.Stopwatch]::StartNew()

    # Clean extract output directory to avoid stale artifacts
    if (Test-Path $ExtractOutputDir) {
        Remove-Item -Path $ExtractOutputDir -Recurse -Force
        Write-Host "   Cleaned previous extract output"
    }

    Write-Host "   Source: $sourceName (sub: $sourceSubId, rg: $sourceRg)"
    Write-Host "   Output: $ExtractOutputDir"

    npx apiops extract `
        --subscription-id $sourceSubId `
        --resource-group $sourceRg `
        --service-name $sourceName `
        --output $ExtractOutputDir

    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ Extract failed (exit code $LASTEXITCODE)"
        $exitCode = 2
        Invoke-Teardown
        exit $exitCode
    }

    # Verify output directory has content
    $extractedFiles = Get-ChildItem -Path $ExtractOutputDir -Recurse -File -ErrorAction SilentlyContinue
    if (-not $extractedFiles -or $extractedFiles.Count -eq 0) {
        Write-Host "❌ Extract produced no files in $ExtractOutputDir"
        $exitCode = 2
        Invoke-Teardown
        exit $exitCode
    }

    $extractTimer.Stop()
    $extractDuration = $extractTimer.Elapsed.ToString('hh\:mm\:ss')
    Write-GithubOutput 'extract_duration' $extractDuration
    Write-PhaseEnd "📥" "PHASE 2 complete — extracted $($extractedFiles.Count) files ($extractDuration)"

    # -----------------------------------------------------------------------
    # Phase 2.1: Validate extracted artifacts
    # -----------------------------------------------------------------------
    Write-Phase "🔎" "PHASE 2.1 — Validate extracted artifact structure"
    $validateTimer = [System.Diagnostics.Stopwatch]::StartNew()

    $manifestFile = Join-Path $PSScriptRoot 'expected-structure.json'
    $validateScript = Join-Path $PSScriptRoot 'Test-ExtractedArtifact.ps1'

    $validateArgs = @{
        ExtractedDir  = $ExtractOutputDir
        ManifestFile  = $manifestFile
        SkuName       = $SkuName
    }
    switch ($LogLevel) {
        'Verbose' { $validateArgs.Verbose = $true }
        'Debug'   { $validateArgs.Debug = $true }
    }
    & $validateScript @validateArgs

    $validateExitCode = $LASTEXITCODE
    $validateTimer.Stop()
    $validateDuration = $validateTimer.Elapsed.ToString('hh\:mm\:ss')

    if ($validateExitCode -ne 0) {
        Write-Host "❌ Artifact validation failed (exit code $validateExitCode)"
        $exitCode = if ($validateExitCode -eq 2) { 2 } else { 1 }
        Write-GithubOutput 'validate_result' 'fail'
        # Don't abort — continue with round-trip to see if ARM comparison also catches issues
        Write-Host "⚠️  Continuing with round-trip despite validation failures..."
    } else {
        Write-PhaseEnd "🔎" "PHASE 2.1 complete — artifact validation passed ($validateDuration)"
        Write-GithubOutput 'validate_result' 'pass'
    }

    Write-Host ""

    # -----------------------------------------------------------------------
    # Phase 2.5: Generate override config for target environment
    # -----------------------------------------------------------------------
    Write-Phase "🔧" "PHASE 2.5 — Generate override config for target environment"

    # Gather target infrastructure details for overrides
    $targetKvUri = if ($targetOutputs) { $targetOutputs.keyVaultUri.value } else {
        $kvInfo = az keyvault list --resource-group $targetRg --query "[0].properties.vaultUri" -o tsv
        $kvInfo
    }
    $targetAiResourceId = if ($targetOutputs) { $targetOutputs.appInsightsResourceId.value } else {
        az monitor app-insights component show --resource-group $targetRg --query "[0].id" -o tsv
    }
    $targetAiKey = if ($targetOutputs) { $targetOutputs.appInsightsInstrumentationKey.value } else {
        az monitor app-insights component show --resource-group $targetRg --query "[0].instrumentationKey" -o tsv
    }
    $targetEhNs = if ($targetOutputs) { $targetOutputs.eventHubNamespaceName.value } else {
        az eventhubs namespace list --resource-group $targetRg --query "[0].name" -o tsv
    }

    # Get Event Hub connection string (can't be output from Bicep)
    $targetEhConnStr = az eventhubs namespace authorization-rule keys list `
        --resource-group $targetRg `
        --namespace-name $targetEhNs `
        --name 'tgt-eh-send' `
        --query 'primaryConnectionString' -o tsv

    if (-not $targetEhConnStr) {
        Write-Host "   ⚠️  Could not get Event Hub connection string — EH logger override will be empty"
    }

    # Target Event Hub entity name (hardcoded in target-apim.bicep)
    $targetEhName = 'tgt-eh-logs'

    $overrideFile = Join-Path $ExtractOutputDir '.overrides.yaml'
    $overrideYaml = @"
namedValues:
  src-nv-keyvault:
    keyVault:
      secretIdentifier: "${targetKvUri}secrets/tgt-secret-value"

loggers:
  src-logger-appinsights:
    resourceId: "$targetAiResourceId"
    credentials:
      instrumentationKey: "$targetAiKey"
  src-logger-eventhub:
    credentials:
      name: "$targetEhName"
      connectionString: "$targetEhConnStr"
"@

    $overrideYaml | Set-Content -Path $overrideFile -Encoding utf8
    Write-Host "   Override config written to: $overrideFile"
    Write-PhaseEnd "🔧" "PHASE 2.5 complete — override config generated"

    # -----------------------------------------------------------------------
    # Phase 3: Publish
    # -----------------------------------------------------------------------
    Write-Phase "📤" "PHASE 3 — Publish to target APIM"
    $publishTimer = [System.Diagnostics.Stopwatch]::StartNew()

    Write-Host "   Target: $targetName (sub: $targetSubId, rg: $targetRg)"
    Write-Host "   Input:  $ExtractOutputDir"

    npx apiops publish `
        --subscription-id $targetSubId `
        --resource-group $targetRg `
        --service-name $targetName `
        --source $ExtractOutputDir `
        --overrides $overrideFile

    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ Publish failed (exit code $LASTEXITCODE)"
        $exitCode = 2
        Invoke-Teardown
        exit $exitCode
    }

    $publishTimer.Stop()
    $publishDuration = $publishTimer.Elapsed.ToString('hh\:mm\:ss')
    Write-GithubOutput 'publish_duration' $publishDuration
    Write-PhaseEnd "📤" "PHASE 3 complete — published to target ($publishDuration)"

    # -----------------------------------------------------------------------
    # Phase 4: Verify
    # -----------------------------------------------------------------------
    Write-Phase "🔍" "PHASE 4 — Compare source and target APIM instances"
    $verifyTimer = [System.Diagnostics.Stopwatch]::StartNew()

    $compareArgs = @{
        SourceSubscriptionId = $sourceSubId
        SourceResourceGroup  = $sourceRg
        SourceApimName       = $sourceName
        TargetSubscriptionId = $targetSubId
        TargetResourceGroup  = $targetRg
        TargetApimName       = $targetName
    }
    switch ($LogLevel) {
        'Verbose' { $compareArgs.Verbose = $true }
        'Debug'   { $compareArgs.Debug = $true }
    }
    & $compareScript @compareArgs

    $verifyExitCode = $LASTEXITCODE
    $verifyTimer.Stop()
    $verifyDuration = $verifyTimer.Elapsed.ToString('hh\:mm\:ss')
    Write-GithubOutput 'verify_duration' $verifyDuration

    if ($verifyExitCode -eq 1) {
        Write-Host "❌ Verification found differences"
        $exitCode = 1
        Write-GithubOutput 'result' 'fail'
    } elseif ($verifyExitCode -ge 2) {
        Write-Host "❌ Verification encountered an error (exit code $verifyExitCode)"
        $exitCode = 2
        Write-GithubOutput 'result' 'error'
    } else {
        Write-PhaseEnd "🔍" "PHASE 4 complete — instances match ($verifyDuration)"
        Write-GithubOutput 'result' 'pass'
    }

} finally {
    # -----------------------------------------------------------------------
    # Phase 5: Teardown (always runs)
    # -----------------------------------------------------------------------
    Invoke-Teardown
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

$overallTimer.Stop()
$totalDuration = $overallTimer.Elapsed.ToString('hh\:mm\:ss')
Write-GithubOutput 'total_duration' $totalDuration

Write-Host ""
Write-Host "============================================================"
if ($exitCode -eq 0) {
    Write-Host "✅ ROUND-TRIP TEST PASSED ($totalDuration)"
} elseif ($exitCode -eq 1) {
    Write-Host "❌ ROUND-TRIP TEST FAILED — verification diff ($totalDuration)"
} else {
    Write-Host "❌ ROUND-TRIP TEST FAILED — infrastructure error ($totalDuration)"
}
Write-Host "============================================================"
Write-Host ""

exit $exitCode
