# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
<#
.SYNOPSIS
    Master orchestrator for the 7-phase round-trip integration workflow.
.DESCRIPTION
    Single entry point that runs the full round-trip sequence:
        1) deploy source + target APIM instances,
        2) extract from source,
        3) validate extracted artifact structure,
        4) generate target environment overrides,
        5) publish artifacts to target,
        6) compare source and target,
        7) teardown.

    Works both locally and in CI (writes to GITHUB_OUTPUT when available).

    A unique timestamp + random suffix is auto-generated for resource group and
    APIM names by default to avoid collisions when tests run in parallel.
    Supporting resource names inside each group are generated by Bicep.

  Exit codes:
    0 — all phases passed
    1 — extract validation failed or verification diff detected
    2 — deployment, extract, publish, or teardown error

.EXAMPLE
    # Full run (auto-generates unique resource group and APIM names)
    .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com

    # Full run with explicit resource groups (APIM names still auto-generated)
    .\run-roundtrip-test.ps1 -SourceResourceGroup rg-src -TargetResourceGroup rg-tgt -PublisherEmail admin@contoso.com

    # Keep resources after test for debugging
    .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com -SkipTeardown
#>

#requires -Version 7.0

[CmdletBinding()]
param(
    [Parameter()]
    [string]$SourceResourceGroup,

    [Parameter()]
    [string]$TargetResourceGroup,

    [Parameter()]
    [string]$SourceApimName,

    [Parameter()]
    [string]$TargetApimName,

    [Parameter()]
    [string]$SourceSubscriptionId,

    [Parameter()]
    [string]$TargetSubscriptionId,

    [ValidateSet('Developer', 'Premium', 'Standard', 'StandardV2', 'PremiumV2')]
    [string]$SkuName = 'StandardV2',

    [string]$Location = 'centralus',

    [ValidateSet('Info', 'Verbose', 'Debug')]
    [string]$LogLevel = 'Verbose',

    [Parameter()]
    [string]$PublisherEmail = 'publisher@example.com',

    [string]$ExtractOutputDir = "$PSScriptRoot/extracted-artifacts",

    [switch]$SkipTeardown
)

$ErrorActionPreference = 'Stop'

$scriptArgModule = Join-Path $PSScriptRoot 'modules/ScriptRuntime.psm1'
Import-Module $scriptArgModule -Force

$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$random = -join ((97..122) | Get-Random -Count 3 | ForEach-Object { [char]$_ })
$uniqueId = "$timestamp-$random"

if (-not $SourceResourceGroup) {
    $SourceResourceGroup = "bvt-$uniqueId-src-rg"
}
if (-not $TargetResourceGroup) {
    $TargetResourceGroup = "bvt-$uniqueId-tgt-rg"
}
if (-not $SourceApimName) {
    $SourceApimName = "bvt-$timestamp$random-src-apim"
}
if (-not $TargetApimName) {
    $TargetApimName = "bvt-$timestamp$random-tgt-apim"
}

if (-not $SourceSubscriptionId) {
    $SourceSubscriptionId = $env:SOURCE_SUBSCRIPTION_ID
}
if (-not $TargetSubscriptionId) {
    $TargetSubscriptionId = $env:TARGET_SUBSCRIPTION_ID
}

$extractOutputDirValue = Get-BoundParameterValueOrNull -BoundParameters $PSBoundParameters -Name 'ExtractOutputDir'
$skuNameValue = Get-BoundParameterValueOrNull -BoundParameters $PSBoundParameters -Name 'SkuName'
$locationValue = Get-BoundParameterValueOrNull -BoundParameters $PSBoundParameters -Name 'Location'

# Verify scripts for all phases available
$phase1DeployScript = Join-Path $PSScriptRoot 'phases/run-phase1-deploy.ps1'
$phase2ExtractScript = Join-Path $PSScriptRoot 'phases/run-phase2-extract.ps1'
$phase3ValidateExtractScript = Join-Path $PSScriptRoot 'phases/run-phase3-validate-extract.ps1'
$phase4CreateOverridesScript = Join-Path $PSScriptRoot 'phases/run-phase4-create-overrides.ps1'
$phase5PublishScript = Join-Path $PSScriptRoot 'phases/run-phase5-publish.ps1'
$phase6CompareScript = Join-Path $PSScriptRoot 'phases/run-phase6-compare.ps1'
$phase7TeardownScript = Join-Path $PSScriptRoot 'phases/run-phase7-teardown.ps1'

foreach ($requiredFile in @($phase1DeployScript, $phase2ExtractScript, $phase3ValidateExtractScript, $phase4CreateOverridesScript, $phase5PublishScript, $phase6CompareScript, $phase7TeardownScript)) {
    if (-not (Test-Path $requiredFile)) {
        Write-Error "Required file not found: $requiredFile"
        exit 2
    }
}
$exitCode = 0
$currentPhase = 'phase-setup'

try {
    # Phase 1: Deploy source apim instance and minimal target apim instance
    $currentPhase = 'phase1-deploy'
    $phase1Args = @{
        SourceResourceGroup = $SourceResourceGroup
        TargetResourceGroup = $TargetResourceGroup
        SourceApimName      = $SourceApimName
        TargetApimName      = $TargetApimName
        Location            = $Location
        PublisherEmail      = $PublisherEmail
        LogLevel            = $LogLevel
    }
    Add-ArgumentIfSet -Hashtable $phase1Args -Key 'SkuName' -Value $skuNameValue
    Add-ArgumentIfSet -Hashtable $phase1Args -Key 'SourceSubscriptionId' -Value $SourceSubscriptionId
    Add-ArgumentIfSet -Hashtable $phase1Args -Key 'TargetSubscriptionId' -Value $TargetSubscriptionId
    $global:LASTEXITCODE = 0
    $phase1Output = & $phase1DeployScript @phase1Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    # Update values based on deployment output.
    $SourceSubscriptionId = $phase1Output.sourceSubscriptionId
    $TargetSubscriptionId = $phase1Output.targetSubscriptionId
    $SourceResourceGroup = $phase1Output.sourceResourceGroup
    $TargetResourceGroup = $phase1Output.targetResourceGroup
    $SourceApimName = $phase1Output.sourceApimName
    $TargetApimName = $phase1Output.targetApimName
    $SkuName = $phase1Output.skuName
    $Location = $phase1Output.location

    # Phase 2: `apiops extract`
    $currentPhase = 'phase2-extract'
    $phase2Args = @{
        SourceResourceGroup = $SourceResourceGroup
        SourceApimName      = $SourceApimName
        SourceSubscriptionId = $SourceSubscriptionId
        LogLevel            = $LogLevel
    }
    Add-ArgumentIfSet -Hashtable $phase2Args -Key 'ExtractOutputDir' -Value $extractOutputDirValue
    $global:LASTEXITCODE = 0
    & $phase2ExtractScript @phase2Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    # Phase 3: Validate `apiops extract`
    $currentPhase = 'phase3-validate-extract'
    $phase3Args = @{
        SkuName = $SkuName
        LogLevel = $LogLevel
    }
    Add-ArgumentIfSet -Hashtable $phase3Args -Key 'ExtractOutputDir' -Value $extractOutputDirValue
    $global:LASTEXITCODE = 0
    & $phase3ValidateExtractScript @phase3Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    # Phase 4: Generate target environment overrides
    $currentPhase = 'phase4-create-overrides'
    $phase4Args = @{
        TargetResourceGroup = $TargetResourceGroup
        TargetSubscriptionId = $TargetSubscriptionId
        LogLevel = $LogLevel
    }
    Add-ArgumentIfSet -Hashtable $phase4Args -Key 'ExtractOutputDir' -Value $extractOutputDirValue
    $global:LASTEXITCODE = 0
    $overrideFile = & $phase4CreateOverridesScript @phase4Args

    if ($LASTEXITCODE -ne 0 -or -not $overrideFile) {
        $exitCode = $LASTEXITCODE
        if ($exitCode -eq 0) {
            $exitCode = 2
        }
        exit $exitCode
    }

    $overrideFile = [string]$overrideFile

    # Phase 5: Publish extracted artifacts to target
    $currentPhase = 'phase5-publish'
    $phase5Args = @{
        TargetResourceGroup = $TargetResourceGroup
        TargetApimName      = $TargetApimName
        TargetSubscriptionId = $TargetSubscriptionId
        OverrideFile        = $overrideFile
        LogLevel = $LogLevel
    }
    Add-ArgumentIfSet -Hashtable $phase5Args -Key 'ExtractOutputDir' -Value $extractOutputDirValue
    $global:LASTEXITCODE = 0
    & $phase5PublishScript @phase5Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    # Phase 6: Compare source and target APIM instances
    $currentPhase = 'phase6-compare'
    $phase6Args = @{
        SourceResourceGroup = $SourceResourceGroup
        SourceApimName      = $SourceApimName
        TargetResourceGroup = $TargetResourceGroup
        TargetApimName      = $TargetApimName
        SourceSubscriptionId = $SourceSubscriptionId
        TargetSubscriptionId = $TargetSubscriptionId
        LogLevel = $LogLevel
    }
    $global:LASTEXITCODE = 0
    & $phase6CompareScript @phase6Args

    $exitCode = $LASTEXITCODE
}
catch {
    $errorMessage = $_.Exception.Message
    Write-Host "❌ Round-trip failed during $currentPhase" -ForegroundColor Red
    Write-Host "   $errorMessage" -ForegroundColor Red

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
    } else {
        $exitCode = 2
    }
}
finally {
    # Phase 7: Teardown apim instances and supporting resources
    $phase7Args = @{
        SourceResourceGroup = $SourceResourceGroup
        TargetResourceGroup = $TargetResourceGroup
        Location            = $Location
        SkipTeardown        = $SkipTeardown
    }
    Add-ArgumentIfSet -Hashtable $phase7Args -Key 'SourceSubscriptionId' -Value $SourceSubscriptionId
    Add-ArgumentIfSet -Hashtable $phase7Args -Key 'TargetSubscriptionId' -Value $TargetSubscriptionId

    & $phase7TeardownScript @phase7Args
}

exit $exitCode
