<#
.SYNOPSIS
    Master orchestrator for the 5-phase round-trip integration workflow.
.DESCRIPTION
    Single entry point that runs the full round-trip sequence:
        1) deploy source + target APIM instances,
        2) extract from source and validate extracted artifact structure,
        3) publish artifacts to target,
        4) compare source and target,
        5) teardown.

    Works both locally and in CI (writes to GITHUB_OUTPUT when available).

    A unique timestamp + random suffix is auto-generated for resource group and
    APIM names by default to avoid collisions when tests run in parallel.
    Supporting resource names inside each group are generated by Bicep.

  Exit codes:
    0 — all phases passed
    1 — extract validation failed or verification diff detected
    2 — deployment, extract, or publish error

.PARAMETER HardDelete
    Controls whether teardown waits for resource group deletion and purges
    soft-deleted APIM instances. Defaults to $true.

.EXAMPLE
    # Full run (auto-generates unique resource group and APIM names)
    .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com

    # Full run with explicit resource groups (APIM names still auto-generated)
    .\run-roundtrip-test.ps1 -SourceResourceGroup rg-src -TargetResourceGroup rg-tgt -PublisherEmail admin@contoso.com

    # Keep resources after test for debugging
    .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com -SkipTeardown

    # Disable hard-delete behavior on teardown (no purge wait)
    .\run-roundtrip-test.ps1 -PublisherEmail admin@contoso.com -HardDelete:$false
#>

#requires -Version 7.0

[CmdletBinding()]
param(
    [Parameter()]
    [string]$SourceResourceGroup,

    [Parameter()]
    [string]$TargetResourceGroup,

    [Parameter()]
    [string]$SourceApimName,

    [Parameter()]
    [string]$TargetApimName,

    [Parameter()]
    [string]$SourceSubscriptionId,

    [Parameter()]
    [string]$TargetSubscriptionId,

    [ValidateSet('Developer', 'Premium', 'StandardV2', 'PremiumV2')]
    [string]$SkuName = 'StandardV2',

    [string]$Location = 'eastus2',

    [ValidateSet('Info', 'Verbose', 'Debug')]
    [string]$LogLevel = 'Verbose',

    [Parameter()]
    [string]$PublisherEmail = 'publisher@example.com',

    [string]$ExtractOutputDir,

    [switch]$SkipTeardown,

    [switch]$HardDelete
)

$ErrorActionPreference = 'Stop'

if (-not $PSBoundParameters.ContainsKey('HardDelete')) {
    $HardDelete = $true
}

$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$random = -join ((97..122) | Get-Random -Count 3 | ForEach-Object { [char]$_ })
$uniqueId = "$timestamp-$random"

if (-not $SourceResourceGroup) {
    $SourceResourceGroup = "bvt-$uniqueId-src-rg"
}
if (-not $TargetResourceGroup) {
    $TargetResourceGroup = "bvt-$uniqueId-tgt-rg"
}
if (-not $SourceApimName) {
    $SourceApimName = "bvt-$timestamp$random-src-apim"
}
if (-not $TargetApimName) {
    $TargetApimName = "bvt-$timestamp$random-tgt-apim"
}

if (-not $SourceSubscriptionId) {
    $SourceSubscriptionId = $env:SOURCE_SUBSCRIPTION_ID
}
if (-not $TargetSubscriptionId) {
    $TargetSubscriptionId = $env:TARGET_SUBSCRIPTION_ID
}

$phase1Script = Join-Path $PSScriptRoot 'run-roundtrip-phase1-deploy.ps1'
$phase2Script = Join-Path $PSScriptRoot 'run-roundtrip-phase2-extract.ps1'
$phase3Script = Join-Path $PSScriptRoot 'run-roundtrip-phase3-validate-extract.ps1'
$phase4Script = Join-Path $PSScriptRoot 'run-roundtrip-phase4-publish.ps1'
$phase5Script = Join-Path $PSScriptRoot 'run-roundtrip-phase5-compare.ps1'
$phase6Script = Join-Path $PSScriptRoot 'run-roundtrip-phase6-teardown.ps1'

foreach ($requiredFile in @($phase1Script, $phase2Script, $phase3Script, $phase4Script, $phase5Script, $phase6Script)) {
    if (-not (Test-Path $requiredFile)) {
        Write-Error "Required file not found: $requiredFile"
        exit 2
    }
}

$exitCode = 0

try {
    $phase1Args = @{
        SourceResourceGroup = $SourceResourceGroup
        TargetResourceGroup = $TargetResourceGroup
        SourceApimName      = $SourceApimName
        TargetApimName      = $TargetApimName
        SkuName             = $SkuName
        Location            = $Location
        LogLevel            = $LogLevel
        PublisherEmail      = $PublisherEmail
    }
    if (-not [string]::IsNullOrWhiteSpace($SourceSubscriptionId)) {
        $phase1Args.SourceSubscriptionId = $SourceSubscriptionId
    }
    if (-not [string]::IsNullOrWhiteSpace($TargetSubscriptionId)) {
        $phase1Args.TargetSubscriptionId = $TargetSubscriptionId
    }
    & $phase1Script @phase1Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    $phase2Args = @{
        SourceResourceGroup = $SourceResourceGroup
        SourceApimName      = $SourceApimName
        SkuName             = $SkuName
        LogLevel            = $LogLevel
    }
    if (-not [string]::IsNullOrWhiteSpace($SourceSubscriptionId)) {
        $phase2Args.SourceSubscriptionId = $SourceSubscriptionId
    }
    if ($PSBoundParameters.ContainsKey('ExtractOutputDir')) {
        $phase2Args.ExtractOutputDir = $ExtractOutputDir
    }
    & $phase2Script @phase2Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    $phase3Args = @{
        SkuName   = $SkuName
        LogLevel  = $LogLevel
    }
    if ($PSBoundParameters.ContainsKey('ExtractOutputDir')) {
        $phase3Args.ExtractOutputDir = $ExtractOutputDir
    }
    & $phase3Script @phase3Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    $phase4Args = @{
        TargetResourceGroup = $TargetResourceGroup
        TargetApimName      = $TargetApimName
        LogLevel            = $LogLevel
    }
    if (-not [string]::IsNullOrWhiteSpace($TargetSubscriptionId)) {
        $phase4Args.TargetSubscriptionId = $TargetSubscriptionId
    }
    if ($PSBoundParameters.ContainsKey('ExtractOutputDir')) {
        $phase4Args.ExtractOutputDir = $ExtractOutputDir
    }
    & $phase4Script @phase4Args

    if ($LASTEXITCODE -ne 0) {
        $exitCode = $LASTEXITCODE
        exit $exitCode
    }

    $phase5Args = @{
        SourceResourceGroup = $SourceResourceGroup
        SourceApimName      = $SourceApimName
        TargetResourceGroup = $TargetResourceGroup
        TargetApimName      = $TargetApimName
        LogLevel            = $LogLevel
    }
    if (-not [string]::IsNullOrWhiteSpace($SourceSubscriptionId)) {
        $phase5Args.SourceSubscriptionId = $SourceSubscriptionId
    }
    if (-not [string]::IsNullOrWhiteSpace($TargetSubscriptionId)) {
        $phase5Args.TargetSubscriptionId = $TargetSubscriptionId
    }
    & $phase5Script @phase5Args

    $exitCode = $LASTEXITCODE
}
finally {
    & $phase6Script `
        -SourceResourceGroup $SourceResourceGroup `
        -TargetResourceGroup $TargetResourceGroup `
        -Location $Location `
        -HardDelete:$HardDelete `
        -SkipTeardown:$SkipTeardown
}

exit $exitCode
