# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#requires -Version 7.0
<#
.SYNOPSIS
    Phase 5 — Publish artifacts to target APIM.
.DESCRIPTION
    Ensures the override file exists, then runs the apiops publish command
    against the target APIM instance.

.PARAMETER TargetSubscriptionId
    Optional subscription ID for the target APIM instance.

.PARAMETER TargetResourceGroup
    Target APIM resource group.

.PARAMETER TargetApimName
    Target APIM instance name.

.PARAMETER LogLevel
    Logging verbosity passed to apiops and helper commands.

.PARAMETER OverrideFile
    Path to the override file generated by phase 4.

.PARAMETER ExtractOutputDir
    Directory containing the extracted artifacts and generated overrides.

.EXAMPLE
    .\run-phase5-publish.ps1 -TargetResourceGroup rg-tgt -TargetApimName tgt-apim
#>

[CmdletBinding()]
param(
    [string]$TargetSubscriptionId,

    [Parameter(Mandatory)]
    [string]$TargetResourceGroup,

    [Parameter(Mandatory)]
    [string]$TargetApimName,

    [ValidateSet('Info', 'Verbose', 'Debug')]
    [string]$LogLevel = 'Verbose',

    [string]$OverrideFile,

    [string]$ExtractOutputDir = "$PSScriptRoot/extracted-artifacts",

    # When set, publish with --delete-unmatched so resources present in the
    # target but absent from the extracted artifacts are removed.
    [switch]$TestDeleteUnmatched
)

$ErrorActionPreference = 'Stop'
$VerbosePreference = if ($LogLevel -in @('Verbose', 'Debug')) { 'Continue' } else { 'SilentlyContinue' }
$DebugPreference = if ($LogLevel -eq 'Debug') { 'Continue' } else { 'SilentlyContinue' }

$maskingModule = Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) 'shared/modules/LogMasking.psm1'
$scriptArgModule = Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) 'shared/modules/ScriptRuntime.psm1'
$apiopsCliModule = Join-Path (Split-Path $PSScriptRoot -Parent) 'modules/ApiopsCli.psm1'

foreach ($requiredFile in @($maskingModule, $scriptArgModule, $apiopsCliModule)) {
    if (-not (Test-Path $requiredFile)) {
        Write-Error "Required file not found: $requiredFile"
        exit 2
    }
}

if (-not (Test-Path $ExtractOutputDir)) {
    Write-Error "ExtractOutputDir not found: $ExtractOutputDir — run the extract step first"
    exit 2
}

Import-Module $maskingModule -Force
Import-Module $scriptArgModule -Force
Import-Module $apiopsCliModule -Force

$apiopsLogLevel = Get-ApiopsLogLevel -ScriptLogLevel $LogLevel
$apiopsAuthArgs = Get-ApiopsAuthArgs
$targetSubscriptionIdValue = Get-BoundParameterValueOrNull -BoundParameters $PSBoundParameters -Name 'TargetSubscriptionId'
$overrideFileValue = Get-BoundParameterValueOrNull -BoundParameters $PSBoundParameters -Name 'OverrideFile'

if ([string]::IsNullOrWhiteSpace($overrideFileValue)) {
    Write-Error 'OverrideFile not provided — run phase 4 first and pass the returned override path to phase 5'
    exit 2
}

if (-not (Test-Path $overrideFileValue)) {
    Write-Error "OverrideFile not found: $overrideFileValue"
    exit 2
}

$overrideFile = (Resolve-Path $overrideFileValue).Path

Write-Host "📤 Publish — Publish artifacts to target APIM"
$deleteUnmatchedArg = @()
if ($TestDeleteUnmatched) {
    Write-Host "🧹 --delete-unmatched enabled — unmatched target resources will be removed"
    $deleteUnmatchedArg = @('--delete-unmatched')
}
$subscriptionArg = if (-not [string]::IsNullOrWhiteSpace($targetSubscriptionIdValue)) { @('--subscription-id', $targetSubscriptionIdValue) } else { @() }

$replacements = @{
    $TargetResourceGroup = Protect-ResourceGroupName -Value $TargetResourceGroup
    $TargetApimName      = Protect-ApimName -Value $TargetApimName
}
Add-ArgumentIfSet -Hashtable $replacements -Key $targetSubscriptionIdValue -Value (Protect-SubscriptionId -Value $targetSubscriptionIdValue)
Add-ArgumentIfSet -Hashtable $replacements -Key $overrideFile -Value '.overrides.yaml'

apiops publish `
    --resource-group $TargetResourceGroup `
    --service-name   $TargetApimName `
    --source         $ExtractOutputDir `
    --overrides      $overrideFile `
    --log-level      $apiopsLogLevel `
    @deleteUnmatchedArg @subscriptionArg @apiopsAuthArgs 2>&1 |
    Protect-Secret -Replacements $replacements |
    Out-Host
$publishExitCode = $LASTEXITCODE

if ($publishExitCode -ne 0) {
    Write-Host "❌ Publish failed (exit code $publishExitCode)"
    exit 2
}

exit 0